In [1]:
import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

Saving data_tanggal_kembar.csv to data_tanggal_kembar.csv

In [2]:
import io

nama_file = next(iter(uploaded))

df = pd.read_csv(
    io.BytesIO(uploaded[nama_file]),
    encoding="utf-8"
)

print("Jumlah data:", len(df))
print("Jumlah kolom:", len(df.columns))

display(df.head())

Jumlah data: 234
Jumlah kolom: 32

,type,id,url,twitterUrl,text,source,retweetCount,replyCount,likeCount,quoteCount,...,card,place,entities,reply_to_user_results,quoted_tweet_results,quoted_tweet,retweeted_tweet,isConversationControlled,searchTermIndex,isQuote
0,tweet,2110049779162153142,https://x.com/aryaaawyz_/status/21100497791621...,https://twitter.com/aryaaawyz_/status/21100497...,@afrkml ak kemarin beli 3 hp di shopee aman am...,NaN,0,0,0,0,...,NaN,{},"{'user_mentions': [{'id_str': '978646566', 'in...","{'rest_id': '978646566', 'result': {'__typenam...",NaN,NaN,NaN,False,0,NaN
1,tweet,2110037673167737100,https://x.com/gigjle/status/2110037673167737100,https://twitter.com/gigjle/status/211003767316...,close yaa! timaacii yang sudah ikutan dan mera...,NaN,0,0,0,0,...,NaN,{},{},NaN,"{'rest_id': '2108850227147067419', 'result': {...","{'type': 'tweet', 'id': '2108850227147067419',...",NaN,False,0,True
2,tweet,2110037344552186209,https://x.com/delouvrekh/status/21100373445521...,https://twitter.com/delouvrekh/status/21100373...,btw kalo abis tanggal kembar emang gini yaa? s...,NaN,0,0,0,0,...,NaN,{},{},NaN,NaN,NaN,NaN,False,0,NaN
3,tweet,2110010539950899311,https://x.com/tirtaannas/status/21100105399508...,https://twitter.com/tirtaannas/status/21100105...,Ya onlen kan banyak diskonannyaa terus byk bon...,NaN,0,1,0,0,...,NaN,{},{},NaN,"{'rest_id': '2109964198101086224', 'result': {...","{'type': 'tweet', 'id': '2109964198101086224',...",NaN,False,0,True
4,tweet,2110004575105388837,https://x.com/urveeey/status/2110004575105388837,https://twitter.com/urveeey/status/21100045751...,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",NaN,0,1,0,0,...,NaN,{},"{'user_mentions': [{'id_str': '576064289', 'in...","{'rest_id': '576064289', 'result': {'__typenam...",NaN,NaN,NaN,False,0,NaN

In [3]:
df = pd.read_csv(
    io.BytesIO(uploaded[nama_file]),
    encoding="latin-1"
)

display(df.head())

,ï»¿type,id,url,twitterUrl,text,source,retweetCount,replyCount,likeCount,quoteCount,...,card,place,entities,reply_to_user_results,quoted_tweet_results,quoted_tweet,retweeted_tweet,isConversationControlled,searchTermIndex,isQuote
0,tweet,2110049779162153142,https://x.com/aryaaawyz_/status/21100497791621...,https://twitter.com/aryaaawyz_/status/21100497...,@afrkml ak kemarin beli 3 hp di shopee aman am...,NaN,0,0,0,0,...,NaN,{},"{'user_mentions': [{'id_str': '978646566', 'in...","{'rest_id': '978646566', 'result': {'__typenam...",NaN,NaN,NaN,False,0,NaN
1,tweet,2110037673167737100,https://x.com/gigjle/status/2110037673167737100,https://twitter.com/gigjle/status/211003767316...,close yaa! timaacii yang sudah ikutan dan mera...,NaN,0,0,0,0,...,NaN,{},{},NaN,"{'rest_id': '2108850227147067419', 'result': {...","{'type': 'tweet', 'id': '2108850227147067419',...",NaN,False,0,True
2,tweet,2110037344552186209,https://x.com/delouvrekh/status/21100373445521...,https://twitter.com/delouvrekh/status/21100373...,btw kalo abis tanggal kembar emang gini yaa? s...,NaN,0,0,0,0,...,NaN,{},{},NaN,NaN,NaN,NaN,False,0,NaN
3,tweet,2110010539950899311,https://x.com/tirtaannas/status/21100105399508...,https://twitter.com/tirtaannas/status/21100105...,Ya onlen kan banyak diskonannyaa terus byk bon...,NaN,0,1,0,0,...,NaN,{},{},NaN,"{'rest_id': '2109964198101086224', 'result': {...","{'type': 'tweet', 'id': '2109964198101086224',...",NaN,False,0,True
4,tweet,2110004575105388837,https://x.com/urveeey/status/2110004575105388837,https://twitter.com/urveeey/status/21100045751...,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",NaN,0,1,0,0,...,NaN,{},"{'user_mentions': [{'id_str': '576064289', 'in...","{'rest_id': '576064289', 'result': {'__typenam...",NaN,NaN,NaN,False,0,NaN

In [4]:
print("Nama kolom:")
print(df.columns.tolist())

print("\nInformasi dataset:")
df.info()

print("\nJumlah data kosong:")
display(df.isnull().sum())

print("\nJumlah baris duplikat:")
print(df.duplicated().sum())

Nama kolom:
['ï»¿type', 'id', 'url', 'twitterUrl', 'text', 'source', 'retweetCount', 'replyCount', 'likeCount', 'quoteCount', 'viewCount', 'createdAt', 'lang', 'bookmarkCount', 'isReply', 'inReplyToId', 'conversationId', 'inReplyToUserId', 'inReplyToUsername', 'isPinned', 'author', 'extendedEntities', 'card', 'place', 'entities', 'reply_to_user_results', 'quoted_tweet_results', 'quoted_tweet', 'retweeted_tweet', 'isConversationControlled', 'searchTermIndex', 'isQuote']

Informasi dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ï»¿type                   234 non-null    object
 1   id                        234 non-null    int64
 2   url                       234 non-null    object
 3   twitterUrl                234 non-null    object
 4   text                      234 non-null    object
 5   source                    0 non-null      float64
 6   retweetCount              234 non-null    int64
 7   replyCount                234 non-null    int64
 8   likeCount                 234 non-null    int64
 9   quoteCount                234 non-null    int64
 10  viewCount                 234 non-null    int64
 11  createdAt                 234 non-null    object
 12  lang                      234 non-null    object
 13  bookmarkCount             234 non-null    int64
 14  isReply                   234 non-null    bool
 15  inReplyToId               67 non-null     float64
 16  conversationId            234 non-null    int64
 17  inReplyToUserId           67 non-null     float64
 18  inReplyToUsername         67 non-null     object
 19  isPinned                  234 non-null    bool
 20  author                    234 non-null    object
 21  extendedEntities          234 non-null    object
 22  card                      54 non-null     object
 23  place                     234 non-null    object
 24  entities                  234 non-null    object
 25  reply_to_user_results     67 non-null     object
 26  quoted_tweet_results      18 non-null     object
 27  quoted_tweet              18 non-null     object
 28  retweeted_tweet           0 non-null      float64
 29  isConversationControlled  234 non-null    bool
 30  searchTermIndex           234 non-null    int64
 31  isQuote                   18 non-null     object
dtypes: bool(3), float64(4), int64(9), object(16)
memory usage: 53.8+ KB

Jumlah data kosong:

ï»¿type                       0
id                            0
url                           0
twitterUrl                    0
text                          0
source                      234
retweetCount                  0
replyCount                    0
likeCount                     0
quoteCount                    0
viewCount                     0
createdAt                     0
lang                          0
bookmarkCount                 0
isReply                       0
inReplyToId                 167
conversationId                0
inReplyToUserId             167
inReplyToUsername           167
isPinned                      0
author                        0
extendedEntities              0
card                        180
place                         0
entities                      0
reply_to_user_results       167
quoted_tweet_results        216
quoted_tweet                216
retweeted_tweet             234
isConversationControlled      0
searchTermIndex               0
isQuote                     216
dtype: int64

Jumlah baris duplikat:
0

In [7]:
# 1. Rapikan nama kolom
df.columns = (
    df.columns
    .str.replace("ï»¿", "", regex=False)
    .str.strip()
)

# 2. Periksa nama kolom setelah diperbaiki
print("Nama kolom setelah diperbaiki:")
print(df.columns.tolist())

# 3. Hapus kolom yang seluruh isinya kosong
kolom_kosong = [
    kolom for kolom in df.columns
    if df[kolom].isna().all()
]

print("\nKolom yang dihapus:", kolom_kosong)

df = df.drop(columns=kolom_kosong)

# 4. Buat salinan teks asli
df["original_text"] = df["text"].copy()

print("\nUkuran dataset setelah dirapikan:", df.shape)

display(df.head())

Nama kolom setelah diperbaiki:
['type', 'id', 'url', 'twitterUrl', 'text', 'source', 'retweetCount', 'replyCount', 'likeCount', 'quoteCount', 'viewCount', 'createdAt', 'lang', 'bookmarkCount', 'isReply', 'inReplyToId', 'conversationId', 'inReplyToUserId', 'inReplyToUsername', 'isPinned', 'author', 'extendedEntities', 'card', 'place', 'entities', 'reply_to_user_results', 'quoted_tweet_results', 'quoted_tweet', 'retweeted_tweet', 'isConversationControlled', 'searchTermIndex', 'isQuote']

Kolom yang dihapus: ['source', 'retweeted_tweet']

Ukuran dataset setelah dirapikan: (234, 31)

,type,id,url,twitterUrl,text,retweetCount,replyCount,likeCount,quoteCount,viewCount,...,card,place,entities,reply_to_user_results,quoted_tweet_results,quoted_tweet,isConversationControlled,searchTermIndex,isQuote,original_text
0,tweet,2110049779162153142,https://x.com/aryaaawyz_/status/21100497791621...,https://twitter.com/aryaaawyz_/status/21100497...,@afrkml ak kemarin beli 3 hp di shopee aman am...,0,0,0,0,310,...,NaN,{},"{'user_mentions': [{'id_str': '978646566', 'in...","{'rest_id': '978646566', 'result': {'__typenam...",NaN,NaN,False,0,NaN,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,tweet,2110037673167737100,https://x.com/gigjle/status/2110037673167737100,https://twitter.com/gigjle/status/211003767316...,close yaa! timaacii yang sudah ikutan dan mera...,0,0,0,0,52,...,NaN,{},{},NaN,"{'rest_id': '2108850227147067419', 'result': {...","{'type': 'tweet', 'id': '2108850227147067419',...",False,0,True,close yaa! timaacii yang sudah ikutan dan mera...
2,tweet,2110037344552186209,https://x.com/delouvrekh/status/21100373445521...,https://twitter.com/delouvrekh/status/21100373...,btw kalo abis tanggal kembar emang gini yaa? s...,0,0,0,0,83,...,NaN,{},{},NaN,NaN,NaN,False,0,NaN,btw kalo abis tanggal kembar emang gini yaa? s...
3,tweet,2110010539950899311,https://x.com/tirtaannas/status/21100105399508...,https://twitter.com/tirtaannas/status/21100105...,Ya onlen kan banyak diskonannyaa terus byk bon...,0,1,0,0,159,...,NaN,{},{},NaN,"{'rest_id': '2109964198101086224', 'result': {...","{'type': 'tweet', 'id': '2109964198101086224',...",False,0,True,Ya onlen kan banyak diskonannyaa terus byk bon...
4,tweet,2110004575105388837,https://x.com/urveeey/status/2110004575105388837,https://twitter.com/urveeey/status/21100045751...,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",0,1,0,0,69,...,NaN,{},"{'user_mentions': [{'id_str': '576064289', 'in...","{'rest_id': '576064289', 'result': {'__typenam...",NaN,NaN,False,0,NaN,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."

In [8]:
# Periksa tanggal postingan
df["createdAt"] = pd.to_datetime(
    df["createdAt"],
    errors="coerce",
    utc=True
)

# Ubah ke zona waktu Indonesia
df["tanggal"] = (
    df["createdAt"]
    .dt.tz_convert("Asia/Jakarta")
)

print("Tanggal paling awal:")
print(df["tanggal"].min())

print("\nTanggal paling akhir:")
print(df["tanggal"].max())

print("\nJumlah data berdasarkan bahasa:")
display(df["lang"].value_counts(dropna=False))

print("\nContoh teks postingan:")
display(df[["tanggal", "lang", "text"]].head(10))

Tanggal paling awal:
2026-10-13 07:30:00+07:00

Tanggal paling akhir:
2026-10-14 04:03:00+07:00

Jumlah data berdasarkan bahasa:

/tmp/ipykernel_1519/4012847786.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["createdAt"] = pd.to_datetime(

lang
in    234
Name: count, dtype: int64

Contoh teks postingan:

,tanggal,lang,text
0,2026-10-13 23:47:24+07:00,in,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,2026-10-13 22:59:18+07:00,in,close yaa! timaacii yang sudah ikutan dan mera...
2,2026-10-13 22:58:00+07:00,in,btw kalo abis tanggal kembar emang gini yaa? s...
3,2026-10-13 21:11:29+07:00,in,Ya onlen kan banyak diskonannyaa terus byk bon...
4,2026-10-13 20:47:47+07:00,in,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."
5,2026-10-13 20:30:07+07:00,in,"Syongsok menikah di tanggal kembar, anaknya ke..."
6,2026-10-13 19:44:11+07:00,in,@nattwtij Masama sayangkuuu ð\nKalau beli e...
7,2026-10-13 18:23:10+07:00,in,Ges mau nanyað\nShopee kalian kalau lagi ga...
8,2026-10-13 18:22:48+07:00,in,"Tes kekencangan si Jisulife 10 ini oke sih, ad..."
9,2026-10-13 18:16:05+07:00,in,@riorkha Diskon tanggal kembar oren dong 9.9

In [9]:
print("Jumlah ID duplikat:")
print(df["id"].duplicated().sum())

# Hapus jika ada ID yang benar-benar duplikat
df = df.drop_duplicates(
    subset=["id"],
    keep="first"
)

print("Jumlah data setelah pemeriksaan ID:", len(df))

Jumlah ID duplikat:
0
Jumlah data setelah pemeriksaan ID: 234

In [10]:
# 1. Mengubah createdAt menjadi format tanggal
df["createdAt"] = pd.to_datetime(
    df["createdAt"],
    errors="coerce",
    utc=True
)

# 2. Mengubah waktu ke zona WIB
df["tanggal"] = df["createdAt"].dt.tz_convert(
    "Asia/Jakarta"
)

# 3. Melihat rentang tanggal
print("Tanggal paling awal:")
print(df["tanggal"].min())

print("\nTanggal paling akhir:")
print(df["tanggal"].max())

# 4. Melihat distribusi bahasa
print("\nJumlah data berdasarkan bahasa:")
display(df["lang"].value_counts(dropna=False))

# 5. Melihat 10 contoh postingan
display(
    df[["tanggal", "lang", "text"]].head(10)
)

Tanggal paling awal:
2026-10-13 07:30:00+07:00

Tanggal paling akhir:
2026-10-14 04:03:00+07:00

Jumlah data berdasarkan bahasa:

lang
in    234
Name: count, dtype: int64

,tanggal,lang,text
0,2026-10-13 23:47:24+07:00,in,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,2026-10-13 22:59:18+07:00,in,close yaa! timaacii yang sudah ikutan dan mera...
2,2026-10-13 22:58:00+07:00,in,btw kalo abis tanggal kembar emang gini yaa? s...
3,2026-10-13 21:11:29+07:00,in,Ya onlen kan banyak diskonannyaa terus byk bon...
4,2026-10-13 20:47:47+07:00,in,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."
5,2026-10-13 20:30:07+07:00,in,"Syongsok menikah di tanggal kembar, anaknya ke..."
6,2026-10-13 19:44:11+07:00,in,@nattwtij Masama sayangkuuu ð\nKalau beli e...
7,2026-10-13 18:23:10+07:00,in,Ges mau nanyað\nShopee kalian kalau lagi ga...
8,2026-10-13 18:22:48+07:00,in,"Tes kekencangan si Jisulife 10 ini oke sih, ad..."
9,2026-10-13 18:16:05+07:00,in,@riorkha Diskon tanggal kembar oren dong 9.9

In [11]:
# Menentukan periode penelitian
tanggal_awal = pd.Timestamp(
    "2026-09-13 00:00:00",
    tz="Asia/Jakarta"
)

tanggal_akhir = pd.Timestamp(
    "2026-10-14 23:59:59",
    tz="Asia/Jakarta"
)

# Filter berdasarkan tanggal
df = df[
    (df["tanggal"] >= tanggal_awal) &
    (df["tanggal"] <= tanggal_akhir)
].copy()

print("Jumlah data setelah filter tanggal:", len(df))

print("Tanggal paling awal:", df["tanggal"].min())
print("Tanggal paling akhir:", df["tanggal"].max())

Jumlah data setelah filter tanggal: 234
Tanggal paling awal: 2026-10-13 07:30:00+07:00
Tanggal paling akhir: 2026-10-14 04:03:00+07:00

In [12]:
kata_kunci = [
    "10.10",
    "10/10",
    "10 oktober",
    "tanggal kembar",
    "promo",
    "diskon",
    "voucher",
    "flash sale",
    "gratis ongkir",
    "shopee",
    "tokopedia",
    "lazada",
    "blibli"
]

for kata in kata_kunci:
    jumlah = df["text"].str.contains(
        kata,
        case=False,
        na=False,
        regex=False
    ).sum()

    print(f"{kata}: {jumlah} postingan")

10.10: 18 postingan
10/10: 0 postingan
10 oktober: 0 postingan
tanggal kembar: 25 postingan
promo: 97 postingan
diskon: 79 postingan
voucher: 71 postingan
flash sale: 38 postingan
gratis ongkir: 91 postingan
shopee: 102 postingan
tokopedia: 1 postingan
lazada: 5 postingan
blibli: 0 postingan

In [13]:
# 1. Mengubah createdAt menjadi format tanggal
df["createdAt"] = pd.to_datetime(
    df["createdAt"],
    errors="coerce",
    utc=True
)

# 2. Mengubah waktu ke zona WIB
df["tanggal"] = df["createdAt"].dt.tz_convert(
    "Asia/Jakarta"
)

# 3. Melihat rentang tanggal
print("Tanggal paling awal:")
print(df["tanggal"].min())

print("\nTanggal paling akhir:")
print(df["tanggal"].max())

# 4. Melihat distribusi bahasa
print("\nJumlah data berdasarkan bahasa:")
display(df["lang"].value_counts(dropna=False))

# 5. Melihat 10 contoh postingan
display(
    df[["tanggal", "lang", "text"]].head(10)
)

Tanggal paling awal:
2026-10-13 07:30:00+07:00

Tanggal paling akhir:
2026-10-14 04:03:00+07:00

Jumlah data berdasarkan bahasa:

lang
in    234
Name: count, dtype: int64

,tanggal,lang,text
0,2026-10-13 23:47:24+07:00,in,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,2026-10-13 22:59:18+07:00,in,close yaa! timaacii yang sudah ikutan dan mera...
2,2026-10-13 22:58:00+07:00,in,btw kalo abis tanggal kembar emang gini yaa? s...
3,2026-10-13 21:11:29+07:00,in,Ya onlen kan banyak diskonannyaa terus byk bon...
4,2026-10-13 20:47:47+07:00,in,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."
5,2026-10-13 20:30:07+07:00,in,"Syongsok menikah di tanggal kembar, anaknya ke..."
6,2026-10-13 19:44:11+07:00,in,@nattwtij Masama sayangkuuu ð\nKalau beli e...
7,2026-10-13 18:23:10+07:00,in,Ges mau nanyað\nShopee kalian kalau lagi ga...
8,2026-10-13 18:22:48+07:00,in,"Tes kekencangan si Jisulife 10 ini oke sih, ad..."
9,2026-10-13 18:16:05+07:00,in,@riorkha Diskon tanggal kembar oren dong 9.9

In [15]:
# Simpan salinan data sebelum proses cleaning
df_cleaning = df.copy()

# Pastikan kolom teks tidak kosong
df_cleaning["text"] = df_cleaning["text"].fillna("").astype(str)

print("Jumlah data sebelum cleaning:", len(df_cleaning))

Jumlah data sebelum cleaning: 234

In [16]:
import re

pola_relevan = (
    r"10[.\-/ ]?10|"
    r"tanggal kembar|"
    r"promo|promosi|"
    r"diskon|discount|"
    r"voucher|kupon|"
    r"flash sale|"
    r"gratis ongkir|ongkir|"
    r"shopee|tokopedia|lazada|blibli|"
    r"marketplace|belanja online"
)

df_cleaning["relevansi_awal"] = df_cleaning["text"].str.contains(
    pola_relevan,
    case=False,
    regex=True,
    na=False
)

print("Postingan terindikasi relevan:")
print(df_cleaning["relevansi_awal"].value_counts())

display(
    df_cleaning[["text", "relevansi_awal"]].head(20)
)

Postingan terindikasi relevan:
relevansi_awal
True     217
False     17
Name: count, dtype: int64

                                                 text  relevansi_awal
0   @afrkml ak kemarin beli 3 hp di shopee aman am...            True
1   close yaa! timaacii yang sudah ikutan dan mera...            True
2   btw kalo abis tanggal kembar emang gini yaa? s...            True
3   Ya onlen kan banyak diskonannyaa terus byk bon...            True
4   @delvkd Iya Iannn, pas tanggal kembar wkwkwk J...            True
5   Syongsok menikah di tanggal kembar, anaknya ke...            True
6   @nattwtij Masama sayangkuuu ð\nKalau beli e...            True
7   Ges mau nanyað\nShopee kalian kalau lagi ga...            True
8   Tes kekencangan si Jisulife 10 ini oke sih, ad...            True
9        @riorkha Diskon tanggal kembar oren dong 9.9            True
10  @Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...            True
11  ini pelayanan sebesar xiaomi ngehadapin custom...            True
12  @usedtob3me Ga ada Kak\nBeli tanggal kembar aj...            True
13  siapapun yang menginisiasi tanggal kembar disk...            True
14  @LambeSahamjja emang melemah njir, buktinya ev...            True
15  @snowdropnikita KAN NGENES BARU KEMAREN AJA HA...            True
16  Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKe...            True
17  @usedtob3me Cetaphil bisa murah kalau beli di ...            True
18  Help RT or repost tweet di bawah ini guyss ð¥...            True
19  Hidup tuh jangan terlalu serius, nanti cepat t...            True

In [19]:
#Text Cleaning
#Buat Fungsi Pembersihan Awal
import re
import unicodedata

def clean_text(text):
    text = str(text)

    # 1. Normalisasi karakter dan huruf kecil
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    # 2. Hapus URL dan email
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text)

    # 3. Hapus mention akun, tetapi pertahankan hashtag sebagai kata
    text = re.sub(r"(?<!\w)@\w+", " ", text)
    text = text.replace("#", "")

    # 4. Pertahankan angka, titik, dan persen untuk informasi promo
    # Bersihkan simbol lain
    text = re.sub(r"[^\w\s.%/-]", " ", text)

    # 5. Rapikan spasi
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_cleaning["clean_text"] = df_cleaning["text"].apply(clean_text)

display(
    df_cleaning[["text", "clean_text"]].head(15)
)

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi ga eve...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
10,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...,aku ð â ï tapi aku mau tanyaa deh toko kamu kl...
11,ini pelayanan sebesar xiaomi ngehadapin custom...,ini pelayanan sebesar xiaomi ngehadapin custom...
12,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...,ga ada kak beli tanggal kembar aja aku pake sa...
13,siapapun yang menginisiasi tanggal kembar disk...,siapapun yang menginisiasi tanggal kembar disk...
14,"@LambeSahamjja emang melemah njir, buktinya ev...",emang melemah njir buktinya event tanggal kemb...

In [20]:
normalisasi = {
    "gak": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "enggak": "tidak",
    "gk": "tidak",
    "bgt": "banget",
    "bngt": "banget",
    "murce": "murah",
    "udh": "sudah",
    "udah": "sudah",
    "blm": "belum",
    "tdk": "tidak",
    "krn": "karena",
    "dgn": "dengan",
    "yg": "yang",
    "aja": "saja"
}

def normalize_slang(text):
    words = text.split()
    words = [normalisasi.get(word, word) for word in words]
    return " ".join(words)

df_cleaning["clean_text"] = df_cleaning["clean_text"].apply(normalize_slang)

display(
    df_cleaning[["text", "clean_text"]].head(15)
)

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi tidak ...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
10,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...,aku ð â ï tapi aku mau tanyaa deh toko kamu kl...
11,ini pelayanan sebesar xiaomi ngehadapin custom...,ini pelayanan sebesar xiaomi ngehadapin custom...
12,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...,tidak ada kak beli tanggal kembar saja aku pak...
13,siapapun yang menginisiasi tanggal kembar disk...,siapapun yang menginisiasi tanggal kembar disk...
14,"@LambeSahamjja emang melemah njir, buktinya ev...",emang melemah njir buktinya event tanggal kemb...

In [21]:
df_cleaning.to_csv(
    "data_tanggal_kembar_cleaning_awal.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset cleaning awal berhasil disimpan.")

Dataset cleaning awal berhasil disimpan.

In [22]:
from google.colab import files

files.download("data_tanggal_kembar_cleaning_awal.csv")

In [23]:
print("Jumlah baris:", len(df))
print("Baris yang seluruh kolomnya kosong:", df.isna().all(axis=1).sum())

display(df[["text", "createdAt"]].head(10))

Jumlah baris: 234
Baris yang seluruh kolomnya kosong: 0

                                                text                 createdAt
0  @afrkml ak kemarin beli 3 hp di shopee aman am... 2026-10-13 16:47:24+00:00
1  close yaa! timaacii yang sudah ikutan dan mera... 2026-10-13 15:59:18+00:00
2  btw kalo abis tanggal kembar emang gini yaa? s... 2026-10-13 15:58:00+00:00
3  Ya onlen kan banyak diskonannyaa terus byk bon... 2026-10-13 14:11:29+00:00
4  @delvkd Iya Iannn, pas tanggal kembar wkwkwk J... 2026-10-13 13:47:47+00:00
5  Syongsok menikah di tanggal kembar, anaknya ke... 2026-10-13 13:30:07+00:00
6  @nattwtij Masama sayangkuuu ð\nKalau beli e... 2026-10-13 12:44:11+00:00
7  Ges mau nanyað\nShopee kalian kalau lagi ga... 2026-10-13 11:23:10+00:00
8  Tes kekencangan si Jisulife 10 ini oke sih, ad... 2026-10-13 11:22:48+00:00
9       @riorkha Diskon tanggal kembar oren dong 9.9 2026-10-13 11:16:05+00:00

In [24]:
df_cleaning.to_csv(
    "data_tanggal_kembar_cleaning_awal.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset cleaning awal berhasil disimpan.")

Dataset cleaning awal berhasil disimpan.

In [25]:
from google.colab import files

files.download("data_tanggal_kembar_cleaning_awal.csv")

In [26]:
# Membuat salinan data untuk proses cleaning
df_cleaning = df.copy()

# Memeriksa data kosong
print("Jumlah baris:", len(df_cleaning))
print("Teks kosong:", df_cleaning["text"].isna().sum())

# Melihat contoh teks
display(df_cleaning[["text", "createdAt"]].head(10))

Jumlah baris: 234
Teks kosong: 0

                                                text                 createdAt
0  @afrkml ak kemarin beli 3 hp di shopee aman am... 2026-10-13 16:47:24+00:00
1  close yaa! timaacii yang sudah ikutan dan mera... 2026-10-13 15:59:18+00:00
2  btw kalo abis tanggal kembar emang gini yaa? s... 2026-10-13 15:58:00+00:00
3  Ya onlen kan banyak diskonannyaa terus byk bon... 2026-10-13 14:11:29+00:00
4  @delvkd Iya Iannn, pas tanggal kembar wkwkwk J... 2026-10-13 13:47:47+00:00
5  Syongsok menikah di tanggal kembar, anaknya ke... 2026-10-13 13:30:07+00:00
6  @nattwtij Masama sayangkuuu ð\nKalau beli e... 2026-10-13 12:44:11+00:00
7  Ges mau nanyað\nShopee kalian kalau lagi ga... 2026-10-13 11:23:10+00:00
8  Tes kekencangan si Jisulife 10 ini oke sih, ad... 2026-10-13 11:22:48+00:00
9       @riorkha Diskon tanggal kembar oren dong 9.9 2026-10-13 11:16:05+00:00

In [27]:
import re

df_cleaning = df.copy()
df_cleaning["text"] = df_cleaning["text"].fillna("").astype(str)

pola_relevan = (
    r"10[.\-/ ]?10|tanggal kembar|"
    r"promo|promosi|diskon|discount|"
    r"voucher|kupon|flash sale|gratis ongkir|ongkir|"
    r"shopee|tokopedia|lazada|blibli|"
    r"marketplace|belanja online"
)

df_cleaning["relevansi_awal"] = df_cleaning["text"].str.contains(
    pola_relevan, case=False, regex=True, na=False
)

print(df_cleaning["relevansi_awal"].value_counts())

relevansi_awal
True     217
False     17
Name: count, dtype: int64

In [28]:
import re
import unicodedata

def clean_text(text):
    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    # Menghapus URL dan email
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(
        r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text
    )

    # Menghapus mention
    text = re.sub(r"(?<!\w)@\w+", " ", text)

    # Menghapus simbol hashtag, tetapi mempertahankan kata setelahnya
    text = text.replace("#", "")

    # Menghapus karakter khusus yang tidak diperlukan
    text = re.sub(r"[^\w\s.%/-]", " ", text)

    # Merapikan spasi
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_cleaning["clean_text"] = df_cleaning["text"].apply(clean_text)

display(df_cleaning[["text", "clean_text"]].head(10))

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi ga eve...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9

In [29]:
import re
import unicodedata

def clean_text(text):
    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    # Menghapus URL dan email
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(
        r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text
    )

    # Menghapus mention
    text = re.sub(r"(?<!\w)@\w+", " ", text)

    # Menghapus simbol hashtag, tetapi mempertahankan kata setelahnya
    text = text.replace("#", "")

    # Menghapus karakter khusus yang tidak diperlukan
    text = re.sub(r"[^\w\s.%/-]", " ", text)

    # Merapikan spasi
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_cleaning["clean_text"] = df_cleaning["text"].apply(clean_text)

display(df_cleaning[["text", "clean_text"]].head(10))

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi ga eve...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9

In [30]:
normalisasi = {
    "gak": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "enggak": "tidak",
    "gk": "tidak",
    "tdk": "tidak",
    "bgt": "banget",
    "bngt": "banget",
    "udh": "sudah",
    "udah": "sudah",
    "blm": "belum",
    "krn": "karena",
    "dgn": "dengan",
    "yg": "yang",
    "aja": "saja"
}

def normalize_slang(text):
    words = text.split()
    words = [normalisasi.get(word, word) for word in words]
    return " ".join(words)

df_cleaning["clean_text"] = df_cleaning["clean_text"].apply(normalize_slang)

display(df_cleaning[["text", "clean_text"]].head(10))

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi tidak ...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9

In [31]:
# Menyimpan hasil agar bisa digunakan pada tahap analisis selanjutnya
df_cleaning.to_csv(
    "data_tanggal_kembar_cleaning.csv",
    index=False,
    encoding="utf-8-sig"
)

print("File berhasil disimpan: data_tanggal_kembar_cleaning.csv")

File berhasil disimpan: data_tanggal_kembar_cleaning.csv