In [ ]:
import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

Saving data_tanggal_kembar.csv to data_tanggal_kembar.csv

In [ ]:
import io

nama_file = next(iter(uploaded))

df = pd.read_csv(
    io.BytesIO(uploaded[nama_file]),
    encoding="utf-8"
)

print("Jumlah data:", len(df))
print("Jumlah kolom:", len(df.columns))

display(df.head())

Jumlah data: 234
Jumlah kolom: 32

,type,id,url,twitterUrl,text,source,retweetCount,replyCount,likeCount,quoteCount,...,card,place,entities,reply_to_user_results,quoted_tweet_results,quoted_tweet,retweeted_tweet,isConversationControlled,searchTermIndex,isQuote
0,tweet,2110049779162153142,https://x.com/aryaaawyz_/status/21100497791621...,https://twitter.com/aryaaawyz_/status/21100497...,@afrkml ak kemarin beli 3 hp di shopee aman am...,NaN,0,0,0,0,...,NaN,{},"{'user_mentions': [{'id_str': '978646566', 'in...","{'rest_id': '978646566', 'result': {'__typenam...",NaN,NaN,NaN,False,0,NaN
1,tweet,2110037673167737100,https://x.com/gigjle/status/2110037673167737100,https://twitter.com/gigjle/status/211003767316...,close yaa! timaacii yang sudah ikutan dan mera...,NaN,0,0,0,0,...,NaN,{},{},NaN,"{'rest_id': '2108850227147067419', 'result': {...","{'type': 'tweet', 'id': '2108850227147067419',...",NaN,False,0,True
2,tweet,2110037344552186209,https://x.com/delouvrekh/status/21100373445521...,https://twitter.com/delouvrekh/status/21100373...,btw kalo abis tanggal kembar emang gini yaa? s...,NaN,0,0,0,0,...,NaN,{},{},NaN,NaN,NaN,NaN,False,0,NaN
3,tweet,2110010539950899311,https://x.com/tirtaannas/status/21100105399508...,https://twitter.com/tirtaannas/status/21100105...,Ya onlen kan banyak diskonannyaa terus byk bon...,NaN,0,1,0,0,...,NaN,{},{},NaN,"{'rest_id': '2109964198101086224', 'result': {...","{'type': 'tweet', 'id': '2109964198101086224',...",NaN,False,0,True
4,tweet,2110004575105388837,https://x.com/urveeey/status/2110004575105388837,https://twitter.com/urveeey/status/21100045751...,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",NaN,0,1,0,0,...,NaN,{},"{'user_mentions': [{'id_str': '576064289', 'in...","{'rest_id': '576064289', 'result': {'__typenam...",NaN,NaN,NaN,False,0,NaN

In [ ]:
df = pd.read_csv(
    io.BytesIO(uploaded[nama_file]),
    encoding="latin-1"
)

display(df.head())

,ï»¿type,id,url,twitterUrl,text,source,retweetCount,replyCount,likeCount,quoteCount,...,card,place,entities,reply_to_user_results,quoted_tweet_results,quoted_tweet,retweeted_tweet,isConversationControlled,searchTermIndex,isQuote
0,tweet,2110049779162153142,https://x.com/aryaaawyz_/status/21100497791621...,https://twitter.com/aryaaawyz_/status/21100497...,@afrkml ak kemarin beli 3 hp di shopee aman am...,NaN,0,0,0,0,...,NaN,{},"{'user_mentions': [{'id_str': '978646566', 'in...","{'rest_id': '978646566', 'result': {'__typenam...",NaN,NaN,NaN,False,0,NaN
1,tweet,2110037673167737100,https://x.com/gigjle/status/2110037673167737100,https://twitter.com/gigjle/status/211003767316...,close yaa! timaacii yang sudah ikutan dan mera...,NaN,0,0,0,0,...,NaN,{},{},NaN,"{'rest_id': '2108850227147067419', 'result': {...","{'type': 'tweet', 'id': '2108850227147067419',...",NaN,False,0,True
2,tweet,2110037344552186209,https://x.com/delouvrekh/status/21100373445521...,https://twitter.com/delouvrekh/status/21100373...,btw kalo abis tanggal kembar emang gini yaa? s...,NaN,0,0,0,0,...,NaN,{},{},NaN,NaN,NaN,NaN,False,0,NaN
3,tweet,2110010539950899311,https://x.com/tirtaannas/status/21100105399508...,https://twitter.com/tirtaannas/status/21100105...,Ya onlen kan banyak diskonannyaa terus byk bon...,NaN,0,1,0,0,...,NaN,{},{},NaN,"{'rest_id': '2109964198101086224', 'result': {...","{'type': 'tweet', 'id': '2109964198101086224',...",NaN,False,0,True
4,tweet,2110004575105388837,https://x.com/urveeey/status/2110004575105388837,https://twitter.com/urveeey/status/21100045751...,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",NaN,0,1,0,0,...,NaN,{},"{'user_mentions': [{'id_str': '576064289', 'in...","{'rest_id': '576064289', 'result': {'__typenam...",NaN,NaN,NaN,False,0,NaN

In [ ]:
print("Nama kolom:")
print(df.columns.tolist())

print("\nInformasi dataset:")
df.info()

print("\nJumlah data kosong:")
display(df.isnull().sum())

print("\nJumlah baris duplikat:")
print(df.duplicated().sum())

Nama kolom:
['ï»¿type', 'id', 'url', 'twitterUrl', 'text', 'source', 'retweetCount', 'replyCount', 'likeCount', 'quoteCount', 'viewCount', 'createdAt', 'lang', 'bookmarkCount', 'isReply', 'inReplyToId', 'conversationId', 'inReplyToUserId', 'inReplyToUsername', 'isPinned', 'author', 'extendedEntities', 'card', 'place', 'entities', 'reply_to_user_results', 'quoted_tweet_results', 'quoted_tweet', 'retweeted_tweet', 'isConversationControlled', 'searchTermIndex', 'isQuote']

Informasi dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 32 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ï»¿type                   234 non-null    object
 1   id                        234 non-null    int64
 2   url                       234 non-null    object
 3   twitterUrl                234 non-null    object
 4   text                      234 non-null    object
 5   source                    0 non-null      float64
 6   retweetCount              234 non-null    int64
 7   replyCount                234 non-null    int64
 8   likeCount                 234 non-null    int64
 9   quoteCount                234 non-null    int64
 10  viewCount                 234 non-null    int64
 11  createdAt                 234 non-null    object
 12  lang                      234 non-null    object
 13  bookmarkCount             234 non-null    int64
 14  isReply                   234 non-null    bool
 15  inReplyToId               67 non-null     float64
 16  conversationId            234 non-null    int64
 17  inReplyToUserId           67 non-null     float64
 18  inReplyToUsername         67 non-null     object
 19  isPinned                  234 non-null    bool
 20  author                    234 non-null    object
 21  extendedEntities          234 non-null    object
 22  card                      54 non-null     object
 23  place                     234 non-null    object
 24  entities                  234 non-null    object
 25  reply_to_user_results     67 non-null     object
 26  quoted_tweet_results      18 non-null     object
 27  quoted_tweet              18 non-null     object
 28  retweeted_tweet           0 non-null      float64
 29  isConversationControlled  234 non-null    bool
 30  searchTermIndex           234 non-null    int64
 31  isQuote                   18 non-null     object
dtypes: bool(3), float64(4), int64(9), object(16)
memory usage: 53.8+ KB

Jumlah data kosong:

ï»¿type                       0
id                            0
url                           0
twitterUrl                    0
text                          0
source                      234
retweetCount                  0
replyCount                    0
likeCount                     0
quoteCount                    0
viewCount                     0
createdAt                     0
lang                          0
bookmarkCount                 0
isReply                       0
inReplyToId                 167
conversationId                0
inReplyToUserId             167
inReplyToUsername           167
isPinned                      0
author                        0
extendedEntities              0
card                        180
place                         0
entities                      0
reply_to_user_results       167
quoted_tweet_results        216
quoted_tweet                216
retweeted_tweet             234
isConversationControlled      0
searchTermIndex               0
isQuote                     216
dtype: int64

Jumlah baris duplikat:
0

In [ ]:
# 1. Rapikan nama kolom
df.columns = (
    df.columns
    .str.replace("ï»¿", "", regex=False)
    .str.strip()
)

# 2. Periksa nama kolom setelah diperbaiki
print("Nama kolom setelah diperbaiki:")
print(df.columns.tolist())

# 3. Hapus kolom yang seluruh isinya kosong
kolom_kosong = [
    kolom for kolom in df.columns
    if df[kolom].isna().all()
]

print("\nKolom yang dihapus:", kolom_kosong)

df = df.drop(columns=kolom_kosong)

# 4. Buat salinan teks asli
df["original_text"] = df["text"].copy()

print("\nUkuran dataset setelah dirapikan:", df.shape)

display(df.head())

Nama kolom setelah diperbaiki:
['type', 'id', 'url', 'twitterUrl', 'text', 'source', 'retweetCount', 'replyCount', 'likeCount', 'quoteCount', 'viewCount', 'createdAt', 'lang', 'bookmarkCount', 'isReply', 'inReplyToId', 'conversationId', 'inReplyToUserId', 'inReplyToUsername', 'isPinned', 'author', 'extendedEntities', 'card', 'place', 'entities', 'reply_to_user_results', 'quoted_tweet_results', 'quoted_tweet', 'retweeted_tweet', 'isConversationControlled', 'searchTermIndex', 'isQuote']

Kolom yang dihapus: ['source', 'retweeted_tweet']

Ukuran dataset setelah dirapikan: (234, 31)

,type,id,url,twitterUrl,text,retweetCount,replyCount,likeCount,quoteCount,viewCount,...,card,place,entities,reply_to_user_results,quoted_tweet_results,quoted_tweet,isConversationControlled,searchTermIndex,isQuote,original_text
0,tweet,2110049779162153142,https://x.com/aryaaawyz_/status/21100497791621...,https://twitter.com/aryaaawyz_/status/21100497...,@afrkml ak kemarin beli 3 hp di shopee aman am...,0,0,0,0,310,...,NaN,{},"{'user_mentions': [{'id_str': '978646566', 'in...","{'rest_id': '978646566', 'result': {'__typenam...",NaN,NaN,False,0,NaN,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,tweet,2110037673167737100,https://x.com/gigjle/status/2110037673167737100,https://twitter.com/gigjle/status/211003767316...,close yaa! timaacii yang sudah ikutan dan mera...,0,0,0,0,52,...,NaN,{},{},NaN,"{'rest_id': '2108850227147067419', 'result': {...","{'type': 'tweet', 'id': '2108850227147067419',...",False,0,True,close yaa! timaacii yang sudah ikutan dan mera...
2,tweet,2110037344552186209,https://x.com/delouvrekh/status/21100373445521...,https://twitter.com/delouvrekh/status/21100373...,btw kalo abis tanggal kembar emang gini yaa? s...,0,0,0,0,83,...,NaN,{},{},NaN,NaN,NaN,False,0,NaN,btw kalo abis tanggal kembar emang gini yaa? s...
3,tweet,2110010539950899311,https://x.com/tirtaannas/status/21100105399508...,https://twitter.com/tirtaannas/status/21100105...,Ya onlen kan banyak diskonannyaa terus byk bon...,0,1,0,0,159,...,NaN,{},{},NaN,"{'rest_id': '2109964198101086224', 'result': {...","{'type': 'tweet', 'id': '2109964198101086224',...",False,0,True,Ya onlen kan banyak diskonannyaa terus byk bon...
4,tweet,2110004575105388837,https://x.com/urveeey/status/2110004575105388837,https://twitter.com/urveeey/status/21100045751...,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",0,1,0,0,69,...,NaN,{},"{'user_mentions': [{'id_str': '576064289', 'in...","{'rest_id': '576064289', 'result': {'__typenam...",NaN,NaN,False,0,NaN,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."

In [ ]:
# Periksa tanggal postingan
df["createdAt"] = pd.to_datetime(
    df["createdAt"],
    errors="coerce",
    utc=True
)

# Ubah ke zona waktu Indonesia
df["tanggal"] = (
    df["createdAt"]
    .dt.tz_convert("Asia/Jakarta")
)

print("Tanggal paling awal:")
print(df["tanggal"].min())

print("\nTanggal paling akhir:")
print(df["tanggal"].max())

print("\nJumlah data berdasarkan bahasa:")
display(df["lang"].value_counts(dropna=False))

print("\nContoh teks postingan:")
display(df[["tanggal", "lang", "text"]].head(10))

Tanggal paling awal:
2026-10-13 07:30:00+07:00

Tanggal paling akhir:
2026-10-14 04:03:00+07:00

Jumlah data berdasarkan bahasa:

/tmp/ipykernel_1519/4012847786.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["createdAt"] = pd.to_datetime(

lang
in    234
Name: count, dtype: int64

Contoh teks postingan:

,tanggal,lang,text
0,2026-10-13 23:47:24+07:00,in,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,2026-10-13 22:59:18+07:00,in,close yaa! timaacii yang sudah ikutan dan mera...
2,2026-10-13 22:58:00+07:00,in,btw kalo abis tanggal kembar emang gini yaa? s...
3,2026-10-13 21:11:29+07:00,in,Ya onlen kan banyak diskonannyaa terus byk bon...
4,2026-10-13 20:47:47+07:00,in,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."
5,2026-10-13 20:30:07+07:00,in,"Syongsok menikah di tanggal kembar, anaknya ke..."
6,2026-10-13 19:44:11+07:00,in,@nattwtij Masama sayangkuuu ð\nKalau beli e...
7,2026-10-13 18:23:10+07:00,in,Ges mau nanyað\nShopee kalian kalau lagi ga...
8,2026-10-13 18:22:48+07:00,in,"Tes kekencangan si Jisulife 10 ini oke sih, ad..."
9,2026-10-13 18:16:05+07:00,in,@riorkha Diskon tanggal kembar oren dong 9.9

In [ ]:
print("Jumlah ID duplikat:")
print(df["id"].duplicated().sum())

# Hapus jika ada ID yang benar-benar duplikat
df = df.drop_duplicates(
    subset=["id"],
    keep="first"
)

print("Jumlah data setelah pemeriksaan ID:", len(df))

Jumlah ID duplikat:
0
Jumlah data setelah pemeriksaan ID: 234

In [ ]:
# 1. Mengubah createdAt menjadi format tanggal
df["createdAt"] = pd.to_datetime(
    df["createdAt"],
    errors="coerce",
    utc=True
)

# 2. Mengubah waktu ke zona WIB
df["tanggal"] = df["createdAt"].dt.tz_convert(
    "Asia/Jakarta"
)

# 3. Melihat rentang tanggal
print("Tanggal paling awal:")
print(df["tanggal"].min())

print("\nTanggal paling akhir:")
print(df["tanggal"].max())

# 4. Melihat distribusi bahasa
print("\nJumlah data berdasarkan bahasa:")
display(df["lang"].value_counts(dropna=False))

# 5. Melihat 10 contoh postingan
display(
    df[["tanggal", "lang", "text"]].head(10)
)

Tanggal paling awal:
2026-10-13 07:30:00+07:00

Tanggal paling akhir:
2026-10-14 04:03:00+07:00

Jumlah data berdasarkan bahasa:

lang
in    234
Name: count, dtype: int64

,tanggal,lang,text
0,2026-10-13 23:47:24+07:00,in,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,2026-10-13 22:59:18+07:00,in,close yaa! timaacii yang sudah ikutan dan mera...
2,2026-10-13 22:58:00+07:00,in,btw kalo abis tanggal kembar emang gini yaa? s...
3,2026-10-13 21:11:29+07:00,in,Ya onlen kan banyak diskonannyaa terus byk bon...
4,2026-10-13 20:47:47+07:00,in,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."
5,2026-10-13 20:30:07+07:00,in,"Syongsok menikah di tanggal kembar, anaknya ke..."
6,2026-10-13 19:44:11+07:00,in,@nattwtij Masama sayangkuuu ð\nKalau beli e...
7,2026-10-13 18:23:10+07:00,in,Ges mau nanyað\nShopee kalian kalau lagi ga...
8,2026-10-13 18:22:48+07:00,in,"Tes kekencangan si Jisulife 10 ini oke sih, ad..."
9,2026-10-13 18:16:05+07:00,in,@riorkha Diskon tanggal kembar oren dong 9.9

In [ ]:
# Menentukan periode penelitian
tanggal_awal = pd.Timestamp(
    "2026-09-13 00:00:00",
    tz="Asia/Jakarta"
)

tanggal_akhir = pd.Timestamp(
    "2026-10-14 23:59:59",
    tz="Asia/Jakarta"
)

# Filter berdasarkan tanggal
df = df[
    (df["tanggal"] >= tanggal_awal) &
    (df["tanggal"] <= tanggal_akhir)
].copy()

print("Jumlah data setelah filter tanggal:", len(df))

print("Tanggal paling awal:", df["tanggal"].min())
print("Tanggal paling akhir:", df["tanggal"].max())

Jumlah data setelah filter tanggal: 234
Tanggal paling awal: 2026-10-13 07:30:00+07:00
Tanggal paling akhir: 2026-10-14 04:03:00+07:00

In [ ]:
kata_kunci = [
    "10.10",
    "10/10",
    "10 oktober",
    "tanggal kembar",
    "promo",
    "diskon",
    "voucher",
    "flash sale",
    "gratis ongkir",
    "shopee",
    "tokopedia",
    "lazada",
    "blibli"
]

for kata in kata_kunci:
    jumlah = df["text"].str.contains(
        kata,
        case=False,
        na=False,
        regex=False
    ).sum()

    print(f"{kata}: {jumlah} postingan")

10.10: 18 postingan
10/10: 0 postingan
10 oktober: 0 postingan
tanggal kembar: 25 postingan
promo: 97 postingan
diskon: 79 postingan
voucher: 71 postingan
flash sale: 38 postingan
gratis ongkir: 91 postingan
shopee: 102 postingan
tokopedia: 1 postingan
lazada: 5 postingan
blibli: 0 postingan

In [ ]:
# 1. Mengubah createdAt menjadi format tanggal
df["createdAt"] = pd.to_datetime(
    df["createdAt"],
    errors="coerce",
    utc=True
)

# 2. Mengubah waktu ke zona WIB
df["tanggal"] = df["createdAt"].dt.tz_convert(
    "Asia/Jakarta"
)

# 3. Melihat rentang tanggal
print("Tanggal paling awal:")
print(df["tanggal"].min())

print("\nTanggal paling akhir:")
print(df["tanggal"].max())

# 4. Melihat distribusi bahasa
print("\nJumlah data berdasarkan bahasa:")
display(df["lang"].value_counts(dropna=False))

# 5. Melihat 10 contoh postingan
display(
    df[["tanggal", "lang", "text"]].head(10)
)

Tanggal paling awal:
2026-10-13 07:30:00+07:00

Tanggal paling akhir:
2026-10-14 04:03:00+07:00

Jumlah data berdasarkan bahasa:

lang
in    234
Name: count, dtype: int64

,tanggal,lang,text
0,2026-10-13 23:47:24+07:00,in,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,2026-10-13 22:59:18+07:00,in,close yaa! timaacii yang sudah ikutan dan mera...
2,2026-10-13 22:58:00+07:00,in,btw kalo abis tanggal kembar emang gini yaa? s...
3,2026-10-13 21:11:29+07:00,in,Ya onlen kan banyak diskonannyaa terus byk bon...
4,2026-10-13 20:47:47+07:00,in,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."
5,2026-10-13 20:30:07+07:00,in,"Syongsok menikah di tanggal kembar, anaknya ke..."
6,2026-10-13 19:44:11+07:00,in,@nattwtij Masama sayangkuuu ð\nKalau beli e...
7,2026-10-13 18:23:10+07:00,in,Ges mau nanyað\nShopee kalian kalau lagi ga...
8,2026-10-13 18:22:48+07:00,in,"Tes kekencangan si Jisulife 10 ini oke sih, ad..."
9,2026-10-13 18:16:05+07:00,in,@riorkha Diskon tanggal kembar oren dong 9.9

In [ ]:
# Simpan salinan data sebelum proses cleaning
df_cleaning = df.copy()

# Pastikan kolom teks tidak kosong
df_cleaning["text"] = df_cleaning["text"].fillna("").astype(str)

print("Jumlah data sebelum cleaning:", len(df_cleaning))

Jumlah data sebelum cleaning: 234

In [ ]:
import re

pola_relevan = (
    r"10[.\-/ ]?10|"
    r"tanggal kembar|"
    r"promo|promosi|"
    r"diskon|discount|"
    r"voucher|kupon|"
    r"flash sale|"
    r"gratis ongkir|ongkir|"
    r"shopee|tokopedia|lazada|blibli|"
    r"marketplace|belanja online"
)

df_cleaning["relevansi_awal"] = df_cleaning["text"].str.contains(
    pola_relevan,
    case=False,
    regex=True,
    na=False
)

print("Postingan terindikasi relevan:")
print(df_cleaning["relevansi_awal"].value_counts())

display(
    df_cleaning[["text", "relevansi_awal"]].head(20)
)

Postingan terindikasi relevan:
relevansi_awal
True     217
False     17
Name: count, dtype: int64

                                                 text  relevansi_awal
0   @afrkml ak kemarin beli 3 hp di shopee aman am...            True
1   close yaa! timaacii yang sudah ikutan dan mera...            True
2   btw kalo abis tanggal kembar emang gini yaa? s...            True
3   Ya onlen kan banyak diskonannyaa terus byk bon...            True
4   @delvkd Iya Iannn, pas tanggal kembar wkwkwk J...            True
5   Syongsok menikah di tanggal kembar, anaknya ke...            True
6   @nattwtij Masama sayangkuuu ð\nKalau beli e...            True
7   Ges mau nanyað\nShopee kalian kalau lagi ga...            True
8   Tes kekencangan si Jisulife 10 ini oke sih, ad...            True
9        @riorkha Diskon tanggal kembar oren dong 9.9            True
10  @Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...            True
11  ini pelayanan sebesar xiaomi ngehadapin custom...            True
12  @usedtob3me Ga ada Kak\nBeli tanggal kembar aj...            True
13  siapapun yang menginisiasi tanggal kembar disk...            True
14  @LambeSahamjja emang melemah njir, buktinya ev...            True
15  @snowdropnikita KAN NGENES BARU KEMAREN AJA HA...            True
16  Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKe...            True
17  @usedtob3me Cetaphil bisa murah kalau beli di ...            True
18  Help RT or repost tweet di bawah ini guyss ð¥...            True
19  Hidup tuh jangan terlalu serius, nanti cepat t...            True

In [ ]:
#Text Cleaning
#Buat Fungsi Pembersihan Awal
import re
import unicodedata

def clean_text(text):
    text = str(text)

    # 1. Normalisasi karakter dan huruf kecil
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    # 2. Hapus URL dan email
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text)

    # 3. Hapus mention akun, tetapi pertahankan hashtag sebagai kata
    text = re.sub(r"(?<!\w)@\w+", " ", text)
    text = text.replace("#", "")

    # 4. Pertahankan angka, titik, dan persen untuk informasi promo
    # Bersihkan simbol lain
    text = re.sub(r"[^\w\s.%/-]", " ", text)

    # 5. Rapikan spasi
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_cleaning["clean_text"] = df_cleaning["text"].apply(clean_text)

display(
    df_cleaning[["text", "clean_text"]].head(15)
)

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi ga eve...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
10,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...,aku ð â ï tapi aku mau tanyaa deh toko kamu kl...
11,ini pelayanan sebesar xiaomi ngehadapin custom...,ini pelayanan sebesar xiaomi ngehadapin custom...
12,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...,ga ada kak beli tanggal kembar aja aku pake sa...
13,siapapun yang menginisiasi tanggal kembar disk...,siapapun yang menginisiasi tanggal kembar disk...
14,"@LambeSahamjja emang melemah njir, buktinya ev...",emang melemah njir buktinya event tanggal kemb...

In [ ]:
normalisasi = {
    "gak": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "enggak": "tidak",
    "gk": "tidak",
    "bgt": "banget",
    "bngt": "banget",
    "murce": "murah",
    "udh": "sudah",
    "udah": "sudah",
    "blm": "belum",
    "tdk": "tidak",
    "krn": "karena",
    "dgn": "dengan",
    "yg": "yang",
    "aja": "saja"
}

def normalize_slang(text):
    words = text.split()
    words = [normalisasi.get(word, word) for word in words]
    return " ".join(words)

df_cleaning["clean_text"] = df_cleaning["clean_text"].apply(normalize_slang)

display(
    df_cleaning[["text", "clean_text"]].head(15)
)

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi tidak ...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
10,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...,aku ð â ï tapi aku mau tanyaa deh toko kamu kl...
11,ini pelayanan sebesar xiaomi ngehadapin custom...,ini pelayanan sebesar xiaomi ngehadapin custom...
12,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...,tidak ada kak beli tanggal kembar saja aku pak...
13,siapapun yang menginisiasi tanggal kembar disk...,siapapun yang menginisiasi tanggal kembar disk...
14,"@LambeSahamjja emang melemah njir, buktinya ev...",emang melemah njir buktinya event tanggal kemb...

In [ ]:
df_cleaning.to_csv(
    "data_tanggal_kembar_cleaning_awal.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset cleaning awal berhasil disimpan.")

Dataset cleaning awal berhasil disimpan.

In [ ]:
from google.colab import files

files.download("data_tanggal_kembar_cleaning_awal.csv")

In [ ]:
print("Jumlah baris:", len(df))
print("Baris yang seluruh kolomnya kosong:", df.isna().all(axis=1).sum())

display(df[["text", "createdAt"]].head(10))

Jumlah baris: 234
Baris yang seluruh kolomnya kosong: 0

                                                text                 createdAt
0  @afrkml ak kemarin beli 3 hp di shopee aman am... 2026-10-13 16:47:24+00:00
1  close yaa! timaacii yang sudah ikutan dan mera... 2026-10-13 15:59:18+00:00
2  btw kalo abis tanggal kembar emang gini yaa? s... 2026-10-13 15:58:00+00:00
3  Ya onlen kan banyak diskonannyaa terus byk bon... 2026-10-13 14:11:29+00:00
4  @delvkd Iya Iannn, pas tanggal kembar wkwkwk J... 2026-10-13 13:47:47+00:00
5  Syongsok menikah di tanggal kembar, anaknya ke... 2026-10-13 13:30:07+00:00
6  @nattwtij Masama sayangkuuu ð\nKalau beli e... 2026-10-13 12:44:11+00:00
7  Ges mau nanyað\nShopee kalian kalau lagi ga... 2026-10-13 11:23:10+00:00
8  Tes kekencangan si Jisulife 10 ini oke sih, ad... 2026-10-13 11:22:48+00:00
9       @riorkha Diskon tanggal kembar oren dong 9.9 2026-10-13 11:16:05+00:00

In [ ]:
df_cleaning.to_csv(
    "data_tanggal_kembar_cleaning_awal.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Dataset cleaning awal berhasil disimpan.")

Dataset cleaning awal berhasil disimpan.

In [ ]:
from google.colab import files

files.download("data_tanggal_kembar_cleaning_awal.csv")

In [ ]:
# Membuat salinan data untuk proses cleaning
df_cleaning = df.copy()

# Memeriksa data kosong
print("Jumlah baris:", len(df_cleaning))
print("Teks kosong:", df_cleaning["text"].isna().sum())

# Melihat contoh teks
display(df_cleaning[["text", "createdAt"]].head(10))

Jumlah baris: 234
Teks kosong: 0

                                                text                 createdAt
0  @afrkml ak kemarin beli 3 hp di shopee aman am... 2026-10-13 16:47:24+00:00
1  close yaa! timaacii yang sudah ikutan dan mera... 2026-10-13 15:59:18+00:00
2  btw kalo abis tanggal kembar emang gini yaa? s... 2026-10-13 15:58:00+00:00
3  Ya onlen kan banyak diskonannyaa terus byk bon... 2026-10-13 14:11:29+00:00
4  @delvkd Iya Iannn, pas tanggal kembar wkwkwk J... 2026-10-13 13:47:47+00:00
5  Syongsok menikah di tanggal kembar, anaknya ke... 2026-10-13 13:30:07+00:00
6  @nattwtij Masama sayangkuuu ð\nKalau beli e... 2026-10-13 12:44:11+00:00
7  Ges mau nanyað\nShopee kalian kalau lagi ga... 2026-10-13 11:23:10+00:00
8  Tes kekencangan si Jisulife 10 ini oke sih, ad... 2026-10-13 11:22:48+00:00
9       @riorkha Diskon tanggal kembar oren dong 9.9 2026-10-13 11:16:05+00:00

In [ ]:
import re

df_cleaning = df.copy()
df_cleaning["text"] = df_cleaning["text"].fillna("").astype(str)

pola_relevan = (
    r"10[.\-/ ]?10|tanggal kembar|"
    r"promo|promosi|diskon|discount|"
    r"voucher|kupon|flash sale|gratis ongkir|ongkir|"
    r"shopee|tokopedia|lazada|blibli|"
    r"marketplace|belanja online"
)

df_cleaning["relevansi_awal"] = df_cleaning["text"].str.contains(
    pola_relevan, case=False, regex=True, na=False
)

print(df_cleaning["relevansi_awal"].value_counts())

relevansi_awal
True     217
False     17
Name: count, dtype: int64

In [ ]:
import re
import unicodedata

def clean_text(text):
    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    # Menghapus URL dan email
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(
        r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text
    )

    # Menghapus mention
    text = re.sub(r"(?<!\w)@\w+", " ", text)

    # Menghapus simbol hashtag, tetapi mempertahankan kata setelahnya
    text = text.replace("#", "")

    # Menghapus karakter khusus yang tidak diperlukan
    text = re.sub(r"[^\w\s.%/-]", " ", text)

    # Merapikan spasi
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_cleaning["clean_text"] = df_cleaning["text"].apply(clean_text)

display(df_cleaning[["text", "clean_text"]].head(10))

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi ga eve...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9

In [ ]:
import re
import unicodedata

def clean_text(text):
    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    # Menghapus URL dan email
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(
        r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text
    )

    # Menghapus mention
    text = re.sub(r"(?<!\w)@\w+", " ", text)

    # Menghapus simbol hashtag, tetapi mempertahankan kata setelahnya
    text = text.replace("#", "")

    # Menghapus karakter khusus yang tidak diperlukan
    text = re.sub(r"[^\w\s.%/-]", " ", text)

    # Merapikan spasi
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_cleaning["clean_text"] = df_cleaning["text"].apply(clean_text)

display(df_cleaning[["text", "clean_text"]].head(10))

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi ga eve...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9

In [ ]:
normalisasi = {
    "gak": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "enggak": "tidak",
    "gk": "tidak",
    "tdk": "tidak",
    "bgt": "banget",
    "bngt": "banget",
    "udh": "sudah",
    "udah": "sudah",
    "blm": "belum",
    "krn": "karena",
    "dgn": "dengan",
    "yg": "yang",
    "aja": "saja"
}

def normalize_slang(text):
    words = text.split()
    words = [normalisasi.get(word, word) for word in words]
    return " ".join(words)

df_cleaning["clean_text"] = df_cleaning["clean_text"].apply(normalize_slang)

display(df_cleaning[["text", "clean_text"]].head(10))

,text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi tidak ...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9

In [ ]:
# Menyimpan hasil agar bisa digunakan pada tahap analisis selanjutnya
df_cleaning.to_csv(
    "data_tanggal_kembar_cleaning.csv",
    index=False,
    encoding="utf-8-sig"
)

print("File berhasil disimpan: data_tanggal_kembar_cleaning.csv")

File berhasil disimpan: data_tanggal_kembar_cleaning.csv

In [33]:

# AUDIT HASIL TEXT CLEANING
import pandas as pd

# Pastikan variabel hasil cleaning tersedia
print("Jumlah baris:", len(df_cleaning))
print("Jumlah kolom:", len(df_cleaning.columns))

# Pastikan kolom teks tersedia
kolom_diperiksa = ["original_text", "clean_text"]
kolom_tersedia = [
    kolom for kolom in kolom_diperiksa
    if kolom in df_cleaning.columns
]
print("\nKolom teks yang tersedia:", kolom_tersedia)

# Periksa teks kosong
if "clean_text" in df_cleaning.columns:
    teks = df_cleaning["clean_text"].fillna("").astype(str).str.strip()

    print("\nTeks kosong setelah cleaning:", (teks == "").sum())
    print("Teks duplikat setelah cleaning:", teks[teks != ""].duplicated().sum())

    # Bandingkan teks asli dengan hasil cleaning
    if "original_text" in df_cleaning.columns:
        contoh = df_cleaning[
            ["original_text", "clean_text"]
        ].head(15)

        display(contoh)
    else:
        display(df_cleaning[["clean_text"]].head(15))
else:
    print(
        "\nKolom clean_text belum ditemukan. "
        "Jalankan dahulu sel text cleaning."
    )

Jumlah baris: 234
Jumlah kolom: 34

Kolom teks yang tersedia: ['original_text', 'clean_text']

Teks kosong setelah cleaning: 0
Teks duplikat setelah cleaning: 43

,original_text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi tidak ...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
10,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...,aku ð â ï tapi aku mau tanyaa deh toko kamu kl...
11,ini pelayanan sebesar xiaomi ngehadapin custom...,ini pelayanan sebesar xiaomi ngehadapin custom...
12,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...,tidak ada kak beli tanggal kembar saja aku pak...
13,siapapun yang menginisiasi tanggal kembar disk...,siapapun yang menginisiasi tanggal kembar disk...
14,"@LambeSahamjja emang melemah njir, buktinya ev...",emang melemah njir buktinya event tanggal kemb...

In [34]:

import re
import unicodedata

def clean_text(text):
    text = str(text)
    text = unicodedata.normalize("NFKC", text)
    text = text.lower()

    # Hapus URL dan email
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(
        r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b",
        " ", text
    )

    # Hapus mention
    text = re.sub(r"(?<!\w)@\w+", " ", text)

    # Hilangkan karakter pengganti dan karakter kontrol
    text = re.sub(r"[\ufffd]", " ", text)
    text = "".join(
        ch for ch in text
        if unicodedata.category(ch) not in ("Cc", "Cs")
    )

    # Hilangkan simbol emoji, tetapi pertahankan huruf,
    # angka, spasi, serta tanda yang berguna untuk promosi
    text = re.sub(r"[^\w\s.%/-]", " ", text)

    # Rapikan spasi
    text = re.sub(r"\s+", " ", text).strip()
    return text

df_cleaning["clean_text"] = (
    df_cleaning["original_text"]
    .fillna("")
    .apply(clean_text)
)

print("Teks kosong:", (df_cleaning["clean_text"].str.strip() == "").sum())
display(df_cleaning[["original_text", "clean_text"]].head(15))

Teks kosong: 0

,original_text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ðkalau beli elektronik begit...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyaðshopee kalian kalau lagi ga even...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
10,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...,aku ð âï tapi aku mau tanyaa deh toko kamu kl ...
11,ini pelayanan sebesar xiaomi ngehadapin custom...,ini pelayanan sebesar xiaomi ngehadapin custom...
12,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...,ga ada kakbeli tanggal kembar ajaaku pake samp...
13,siapapun yang menginisiasi tanggal kembar disk...,siapapun yang menginisiasi tanggal kembar disk...
14,"@LambeSahamjja emang melemah njir, buktinya ev...",emang melemah njir buktinya event tanggal kemb...

In [35]:
duplikat_teks = df_cleaning[
    df_cleaning["clean_text"].duplicated(keep=False)
].sort_values("clean_text")

print("Jumlah baris yang termasuk kelompok teks duplikat:",
      len(duplikat_teks))

display(
    duplikat_teks[
        ["id", "createdAt", "original_text", "clean_text"]
    ].head(20)
)

Jumlah baris yang termasuk kelompok teks duplikat: 49

,id,createdAt,original_text,clean_text
50,2110049116285960510,2026-10-13 16:44:46+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi infokode voucher diskon promo flas...
51,2110049099395596625,2026-10-13 16:44:42+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi infokode voucher diskon promo flas...
202,2109866783117283426,2026-10-13 04:40:15+00:00,Shopee Voucher Diskon 50% â¨\nâ° 12:00 | 20:...,shopee voucher diskon 50% â â 12 00 20 00 wib ...
203,2109866298822041639,2026-10-13 04:38:19+00:00,Shopee Voucher Diskon 50% â¨\nâ° 12:00 | 20:...,shopee voucher diskon 50% â â 12 00 20 00 wib ...
38,2109857413927158009,2026-10-13 04:03:01+00:00,@Lucibxz sini bisa fast,sini bisa fast
40,2109856440064324095,2026-10-13 03:59:09+00:00,@meihuaovv Sini bisa fast,sini bisa fast
211,2109841806611599454,2026-10-13 03:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
207,2109856660093079642,2026-10-13 04:00:01+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
157,2109978457061101751,2026-10-13 12:04:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
199,2109871758883074344,2026-10-13 05:00:01+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
196,2109887356694405487,2026-10-13 06:02:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
192,2109902707670565034,2026-10-13 07:03:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
184,2109917303999516786,2026-10-13 08:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
178,2109932404039438473,2026-10-13 09:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
173,2109947754944291051,2026-10-13 10:02:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
221,2109811355582607538,2026-10-13 01:00:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
218,2109826706970407344,2026-10-13 02:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
151,2109992801702465554,2026-10-13 13:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
164,2109962602877255751,2026-10-13 11:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
141,2110023504108404885,2026-10-13 15:03:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...

In [36]:

# Pemeriksaan duplikasi berdasarkan ID dan teks
print("Total baris:", len(df_cleaning))
print("ID tweet duplikat:",
      df_cleaning["id"].duplicated().sum())

print("Teks asli duplikat:",
      df_cleaning["original_text"].duplicated().sum())

print("Teks bersih duplikat:",
      df_cleaning["clean_text"].duplicated().sum())

# Tampilkan teks bersih yang berulang beserta ID dan waktu
mask_duplikat = df_cleaning["clean_text"].duplicated(keep=False)

kolom = [
    c for c in ["id", "createdAt", "original_text", "clean_text"]
    if c in df_cleaning.columns
]

display(
    df_cleaning.loc[mask_duplikat, kolom]
    .sort_values("clean_text")
    .head(30)
)

Total baris: 234
ID tweet duplikat: 0
Teks asli duplikat: 1
Teks bersih duplikat: 43

,id,createdAt,original_text,clean_text
50,2110049116285960510,2026-10-13 16:44:46+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi infokode voucher diskon promo flas...
51,2110049099395596625,2026-10-13 16:44:42+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi infokode voucher diskon promo flas...
202,2109866783117283426,2026-10-13 04:40:15+00:00,Shopee Voucher Diskon 50% â¨\nâ° 12:00 | 20:...,shopee voucher diskon 50% â â 12 00 20 00 wib ...
203,2109866298822041639,2026-10-13 04:38:19+00:00,Shopee Voucher Diskon 50% â¨\nâ° 12:00 | 20:...,shopee voucher diskon 50% â â 12 00 20 00 wib ...
38,2109857413927158009,2026-10-13 04:03:01+00:00,@Lucibxz sini bisa fast,sini bisa fast
40,2109856440064324095,2026-10-13 03:59:09+00:00,@meihuaovv Sini bisa fast,sini bisa fast
211,2109841806611599454,2026-10-13 03:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
207,2109856660093079642,2026-10-13 04:00:01+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
157,2109978457061101751,2026-10-13 12:04:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
199,2109871758883074344,2026-10-13 05:00:01+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
196,2109887356694405487,2026-10-13 06:02:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
192,2109902707670565034,2026-10-13 07:03:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
184,2109917303999516786,2026-10-13 08:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
178,2109932404039438473,2026-10-13 09:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
173,2109947754944291051,2026-10-13 10:02:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
221,2109811355582607538,2026-10-13 01:00:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
218,2109826706970407344,2026-10-13 02:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
151,2109992801702465554,2026-10-13 13:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
164,2109962602877255751,2026-10-13 11:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
141,2110023504108404885,2026-10-13 15:03:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
125,2110105796902273156,2026-10-13 20:30:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
138,2110038099980108117,2026-10-13 16:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
128,2110090696032239935,2026-10-13 19:30:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
130,2110075597301096696,2026-10-13 18:30:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
145,2110008153022615646,2026-10-13 14:02:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
133,2110060749083353459,2026-10-13 17:31:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
149,2110000102974906494,2026-10-13 13:30:01+00:00,ðï¸ 13 Oktober \nShopeefood Diskon 100% s/...,ðï 13 oktober shopeefood diskon 100% s/d 35rb ...
219,2109818906529448358,2026-10-13 01:30:00+00:00,ðï¸ 13 Oktober \nShopeefood Diskon 100% s/...,ðï 13 oktober shopeefood diskon 100% s/d 35rb ...
216,2109834004954243451,2026-10-13 02:30:00+00:00,ðï¸ 13 Oktober \nShopeefood Diskon 100% s/...,ðï 13 oktober shopeefood diskon 100% s/d 35rb ...
215,2109834006351200407,2026-10-13 02:30:00+00:00,ðï¸ 13 Oktober \nShopeefood Diskon 100% s/...,ðï 13 oktober shopeefood diskon 100% s/d 35rb ...

In [37]:
mask_kosong = (
    df_cleaning["clean_text"]
    .fillna("")
    .str.strip()
    .eq("")
)

print("Jumlah teks kosong:", mask_kosong.sum())

display(
    df_cleaning.loc[
        mask_kosong,
        ["id", "original_text", "clean_text"]
    ]
)

Jumlah teks kosong: 0

Empty DataFrame
Columns: [id, original_text, clean_text]
Index: []

In [38]:
print("Total baris:", len(df_cleaning))
print("ID tweet duplikat:",
      df_cleaning["id"].duplicated().sum())
print("Teks asli duplikat:",
      df_cleaning["original_text"].duplicated().sum())
print("Teks bersih duplikat:",
      df_cleaning["clean_text"].duplicated().sum())

Total baris: 234
ID tweet duplikat: 0
Teks asli duplikat: 1
Teks bersih duplikat: 43

In [39]:
duplikat_asli = df_cleaning[
    df_cleaning["original_text"].duplicated(keep=False)
].sort_values("original_text")

display(
    duplikat_asli[
        ["id", "createdAt", "original_text", "clean_text"]
    ]
)

,id,createdAt,original_text,clean_text
50,2110049116285960510,2026-10-13 16:44:46+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi infokode voucher diskon promo flas...
51,2110049099395596625,2026-10-13 16:44:42+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi infokode voucher diskon promo flas...

In [40]:
contoh_duplikat_bersih = (
    df_cleaning[
        df_cleaning["clean_text"].duplicated(keep=False)
    ]
    .sort_values("clean_text")
    [["id", "createdAt", "original_text", "clean_text"]]
    .head(20)
)

display(contoh_duplikat_bersih)

,id,createdAt,original_text,clean_text
50,2110049116285960510,2026-10-13 16:44:46+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi infokode voucher diskon promo flas...
51,2110049099395596625,2026-10-13 16:44:42+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi infokode voucher diskon promo flas...
202,2109866783117283426,2026-10-13 04:40:15+00:00,Shopee Voucher Diskon 50% â¨\nâ° 12:00 | 20:...,shopee voucher diskon 50% â â 12 00 20 00 wib ...
203,2109866298822041639,2026-10-13 04:38:19+00:00,Shopee Voucher Diskon 50% â¨\nâ° 12:00 | 20:...,shopee voucher diskon 50% â â 12 00 20 00 wib ...
38,2109857413927158009,2026-10-13 04:03:01+00:00,@Lucibxz sini bisa fast,sini bisa fast
40,2109856440064324095,2026-10-13 03:59:09+00:00,@meihuaovv Sini bisa fast,sini bisa fast
211,2109841806611599454,2026-10-13 03:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
207,2109856660093079642,2026-10-13 04:00:01+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
157,2109978457061101751,2026-10-13 12:04:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
199,2109871758883074344,2026-10-13 05:00:01+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
196,2109887356694405487,2026-10-13 06:02:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
192,2109902707670565034,2026-10-13 07:03:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
184,2109917303999516786,2026-10-13 08:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
178,2109932404039438473,2026-10-13 09:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
173,2109947754944291051,2026-10-13 10:02:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
221,2109811355582607538,2026-10-13 01:00:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
218,2109826706970407344,2026-10-13 02:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
151,2109992801702465554,2026-10-13 13:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
164,2109962602877255751,2026-10-13 11:01:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...
141,2110023504108404885,2026-10-13 15:03:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...

In [41]:

# Tampilkan teks lengkap, bukan hanya tampilan tabel yang terpotong
ids_diperiksa = [
    "2110049116285960510",
    "2110049099395596625",
    "2109857413927158009",
    "2109856440064324095",
    "2109866783117283426",
    "2109866298822041639",
]

hasil = df_cleaning[
    df_cleaning["id"].astype(str).isin(ids_diperiksa)
]

for _, row in hasil.iterrows():
    print("=" * 80)
    print("ID:", row["id"])
    print("Waktu:", row["createdAt"])
    print("TEKS ASLI:")
    print(row["original_text"])
    print("TEKS BERSIH:")
    print(row["clean_text"])
    print()

================================================================================
ID: 2109857413927158009
Waktu: 2026-10-13 04:03:01+00:00
TEKS ASLI:
@Lucibxz sini bisa fast
TEKS BERSIH:
sini bisa fast

================================================================================
ID: 2109856440064324095
Waktu: 2026-10-13 03:59:09+00:00
TEKS ASLI:
@meihuaovv Sini bisa fast
TEKS BERSIH:
sini bisa fast

================================================================================
ID: 2110049116285960510
Waktu: 2026-10-13 16:44:46+00:00
TEKS ASLI:
Rekomendasi Info
Kode Voucher Diskon Promo Flash Sale checkout belanja beli di Racun Shopee

14 Oktober 2026
Serbu Rabu
10.10 Big Sale

Klaim Voucher Diskonð
https://t.co/MwDA5ImEL6
https://t.co/5AbAhOfDuQ
https://t.co/eY75Lc3DM0

Flashsale pkl 00.00 ð
https://t.co/mYfJRb6buB
TEKS BERSIH:
rekomendasi infokode voucher diskon promo flash sale checkout belanja beli di racun shopee14 oktober 2026serbu rabu10.10 big saleklaim voucher diskonð flashsale pkl 00.00 ð

================================================================================
ID: 2110049099395596625
Waktu: 2026-10-13 16:44:42+00:00
TEKS ASLI:
Rekomendasi Info
Kode Voucher Diskon Promo Flash Sale checkout belanja beli di Racun Shopee

14 Oktober 2026
Serbu Rabu
10.10 Big Sale

Klaim Voucher Diskonð
https://t.co/MwDA5ImEL6
https://t.co/5AbAhOfDuQ
https://t.co/eY75Lc3DM0

Flashsale pkl 00.00 ð
https://t.co/mYfJRb6buB
TEKS BERSIH:
rekomendasi infokode voucher diskon promo flash sale checkout belanja beli di racun shopee14 oktober 2026serbu rabu10.10 big saleklaim voucher diskonð flashsale pkl 00.00 ð

================================================================================
ID: 2109866783117283426
Waktu: 2026-10-13 04:40:15+00:00
TEKS ASLI:
Shopee Voucher Diskon 50% â¨
â° 12:00 | 20:00 WIB

*Voucher Live Xtra*
â¢ Diskon 50% s/d 10RB minbel 20RB
â¢ khusus shopee live bertanda xtra

voucher sudah ada di akun masing-masing:
https://t.co/5XBGE2kKXr https://t.co/W10WUcFMa0
TEKS BERSIH:
shopee voucher diskon 50% â â 12 00 20 00 wib voucher live xtra â diskon 50% s/d 10rb minbel 20rbâ khusus shopee live bertanda xtravoucher sudah ada di akun masing-masing

================================================================================
ID: 2109866298822041639
Waktu: 2026-10-13 04:38:19+00:00
TEKS ASLI:
Shopee Voucher Diskon 50% â¨
â° 12:00 | 20:00 WIB

*Voucher Live Xtra*
â¢ Diskon 50% s/d 10RB minbel 20RB
â¢ khusus shopee live bertanda xtra

voucher sudah ada di akun masing-masing:
https://t.co/5XBGE2kKXr https://t.co/iO3mCwhjad
TEKS BERSIH:
shopee voucher diskon 50% â â 12 00 20 00 wib voucher live xtra â diskon 50% s/d 10rb minbel 20rbâ khusus shopee live bertanda xtravoucher sudah ada di akun masing-masing

In [42]:

import re
import unicodedata

def clean_text(text):
    text = str(text)
    text = unicodedata.normalize("NFKC", text).lower()

    # Ganti baris baru dan tab dengan spasi
    text = re.sub(r"[\r\n\t]+", " ", text)

    # Hapus URL sebelum membersihkan tanda baca
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    # Hapus email dan mention
    text = re.sub(
        r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b", " ", text
    )
    text = re.sub(r"(?<!\w)@\w+", " ", text)

    # Hapus karakter kontrol dan pengganti yang rusak
    text = "".join(
        ch for ch in text
        if unicodedata.category(ch) not in ("Cc", "Cs")
    )
    text = text.replace("\ufffd", " ")

    # Hapus simbol, tetapi pertahankan angka, persen,
    # titik, garis miring, dan tanda minus yang berguna
    text = re.sub(r"[^\w\s.%/-]", " ", text)

    # Rapikan spasi
    text = re.sub(r"\s+", " ", text).strip()
    return text

df_cleaning["clean_text"] = (
    df_cleaning["original_text"]
    .fillna("")
    .apply(clean_text)
)

display(df_cleaning[["original_text", "clean_text"]].head(15))

,original_text,clean_text
0,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...
1,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...
2,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...
3,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...
5,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...
6,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...
7,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi ga eve...
8,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
10,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...,aku ð âï tapi aku mau tanyaa deh toko kamu kl ...
11,ini pelayanan sebesar xiaomi ngehadapin custom...,ini pelayanan sebesar xiaomi ngehadapin custom...
12,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...,ga ada kak beli tanggal kembar aja aku pake sa...
13,siapapun yang menginisiasi tanggal kembar disk...,siapapun yang menginisiasi tanggal kembar disk...
14,"@LambeSahamjja emang melemah njir, buktinya ev...",emang melemah njir buktinya event tanggal kemb...

In [43]:
ids_diperiksa = [
    "2110049116285960510",
    "2110049099395596625",
    "2109866783117283426",
    "2109866298822041639",
]

display(
    df_cleaning[
        df_cleaning["id"].astype(str).isin(ids_diperiksa)
    ][["id", "original_text", "clean_text"]]
)

,id,original_text,clean_text
50,2110049116285960510,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi info kode voucher diskon promo fla...
51,2110049099395596625,Rekomendasi Info\nKode Voucher Diskon Promo Fl...,rekomendasi info kode voucher diskon promo fla...
202,2109866783117283426,Shopee Voucher Diskon 50% â¨\nâ° 12:00 | 20:...,shopee voucher diskon 50% â â 12 00 20 00 wib ...
203,2109866298822041639,Shopee Voucher Diskon 50% â¨\nâ° 12:00 | 20:...,shopee voucher diskon 50% â â 12 00 20 00 wib ...

In [44]:
#kode ini hanya memberikan tanda awal berdasarkan kata kunci.
import re
import pandas as pd

# Kata kunci untuk menyaring tweet yang berpotensi relevan
pola_relevan = (
    r"10\s*[./-]\s*10|10\.10|tanggal\s+kembar|"
    r"big\s*sale|double\s*date|"
    r"promo|promosi|diskon|discount|voucher|kupon|"
    r"flash\s*sale|flashsale|gratis\s*ongkir|"
    r"shopee|tokopedia|lazada|blibli|"
    r"marketplace|belanja\s+online"
)

df_cleaning["relevansi_awal"] = (
    df_cleaning["original_text"]
    .fillna("")
    .str.contains(pola_relevan, case=False, regex=True)
)

print("Jumlah tweet:", len(df_cleaning))
print("\nHasil penandaan awal:")
print(df_cleaning["relevansi_awal"].value_counts())

display(
    df_cleaning[
        ["id", "original_text", "clean_text", "relevansi_awal"]
    ].head(20)
)

Jumlah tweet: 234

Hasil penandaan awal:
relevansi_awal
True     217
False     17
Name: count, dtype: int64

,id,original_text,clean_text,relevansi_awal
0,2110049779162153142,@afrkml ak kemarin beli 3 hp di shopee aman am...,ak kemarin beli 3 hp di shopee aman aman aja. ...,True
1,2110037673167737100,close yaa! timaacii yang sudah ikutan dan mera...,close yaa timaacii yang sudah ikutan dan meram...,True
2,2110037344552186209,btw kalo abis tanggal kembar emang gini yaa? s...,btw kalo abis tanggal kembar emang gini yaa su...,True
3,2110010539950899311,Ya onlen kan banyak diskonannyaa terus byk bon...,ya onlen kan banyak diskonannyaa terus byk bon...,True
4,2110004575105388837,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",iya iannn pas tanggal kembar wkwkwk jisulife l...,True
5,2110000127884828879,"Syongsok menikah di tanggal kembar, anaknya ke...",syongsok menikah di tanggal kembar anaknya kem...,True
6,2109988569775591730,@nattwtij Masama sayangkuuu ð\nKalau beli e...,masama sayangkuuu ð kalau beli elektronik begi...,True
7,2109968183469957508,Ges mau nanyað\nShopee kalian kalau lagi ga...,ges mau nanyað shopee kalian kalau lagi ga eve...,True
8,2109968091128148197,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",tes kekencangan si jisulife 10 ini oke sih ada...,True
9,2109966398118408698,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9,True
10,2109950795177402757,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...,aku ð âï tapi aku mau tanyaa deh toko kamu kl ...,True
11,2109938277319069736,ini pelayanan sebesar xiaomi ngehadapin custom...,ini pelayanan sebesar xiaomi ngehadapin custom...,True
12,2109928760682414103,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...,ga ada kak beli tanggal kembar aja aku pake sa...,True
13,2109925742343839766,siapapun yang menginisiasi tanggal kembar disk...,siapapun yang menginisiasi tanggal kembar disk...,True
14,2109922315643580669,"@LambeSahamjja emang melemah njir, buktinya ev...",emang melemah njir buktinya event tanggal kemb...,True
15,2109905523567202516,@snowdropnikita KAN NGENES BARU KEMAREN AJA HA...,kan ngenes baru kemaren aja haaaaaaaaaa kata m...,True
16,2109903036479103119,Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKe...,jangan biarin saldo e-wallet kosong ð keranjan...,True
17,2109899261253222833,@usedtob3me Cetaphil bisa murah kalau beli di ...,cetaphil bisa murah kalau beli di lazada watso...,True
18,2109890173035335745,Help RT or repost tweet di bawah ini guyss ð¥...,help rt or repost tweet di bawah ini guyss ð o...,True
19,2109868003282341966,"Hidup tuh jangan terlalu serius, nanti cepat t...",hidup tuh jangan terlalu serius nanti cepat tu...,True

In [45]:
tweet_perlu_diperiksa = df_cleaning[
    ~df_cleaning["relevansi_awal"]
]

print("Tweet yang tidak cocok dengan kata kunci:",
      len(tweet_perlu_diperiksa))

display(
    tweet_perlu_diperiksa[
        ["id", "original_text", "clean_text"]
    ].head(30)
)

Tweet yang tidak cocok dengan kata kunci: 17

,id,original_text,clean_text
34,2109903590303396323,capcut naik haji maap yaa guyss kosongg,capcut naik haji maap yaa guyss kosongg
36,2109859125232550355,Capcut naik hajiið­ð­,capcut naik hajiið ð
38,2109857413927158009,@Lucibxz sini bisa fast,sini bisa fast
39,2109856715026153505,@elizpace sini kak\n\nCapcut 7D Rp.5.000\nCapc...,sini kak capcut 7d rp.5.000 capcut 30d shar rp...
40,2109856440064324095,@meihuaovv Sini bisa fast,sini bisa fast
41,2109856260535570577,@snoopyjw0 Capcut 7D Rp.5.000\nCapcut 30D shar...,capcut 7d rp.5.000 capcut 30d shar rp.15.000 c...
42,2109855973468942397,serem ujian audit ð¨ð¨,serem ujian audit ð ð
43,2109854938390307182,"Today ready ini saja yaa, full garansi dan ant...",today ready ini saja yaa full garansi dan anti...
44,2109849162284171421,"hai haiii aku openggg, after ujiannn gemeterannn",hai haiii aku openggg after ujiannn gemeterannn
56,2110015915177988109,à­¨à­§ Ëð·ð¹ð¶ð´ð¶ ð´ð°ðµð¼...,à à ëð ð1ð ð ð ð ð ðμð1 4ð ð ðμ ð ð ð ð ð1 4ð ...
86,2109935943146995788,DIMSUM MIE GACOAN ðµ\nð¦ Udang Keju udang ...,dimsum mie gacoan ðμ ð udang keju udang isian ...
114,2109842332921262451,@ayyalune RO dari awal VC sudah drekam seperti...,ro dari awal vc sudah drekam seperti sengaja d...
146,2110006397035573509,Bisa beli banyakk\nhttps://t.co/5PRqMQaVEC htt...,bisa beli banyakk
170,2109955396341489668,ð° Rp 10.000\nâ° 18:00 WIB\n\nSKIN1004 Mada...,ð rp 10.000 â 18 00 wib skin1004 madagascar ce...
200,2109867642215624949,ð° Rp 1.000\nâ° 12:00 WIB\n\nBASIKE Penyedo...,ð rp 1.000 â 12 00 wib basike penyedot debu ni...
201,2109867197791363366,ð° Rp10.000 â° 12:00 WIB\nSKIN1004 Madagasc...,ð rp10.000 â 12 00 wib skin1004 madagascar cen...
204,2109865866120896629,SIAP SIAP INPUT KODEâ¼ï¸\nâ° 11:00 WIB\nKod...,siap siap input kodeâ1 4ï â 11 00 wib kode nov...

In [46]:
print("Tanggal paling awal:", df_cleaning["createdAt"].min())
print("Tanggal paling akhir:", df_cleaning["createdAt"].max())

if "tanggal" in df_cleaning.columns:
    print("\nJumlah tweet per tanggal Jakarta:")
    print(
        df_cleaning["tanggal"]
        .dt.strftime("%Y-%m-%d")
        .value_counts()
        .sort_index()
    )

Tanggal paling awal: 2026-10-13 00:30:00+00:00
Tanggal paling akhir: 2026-10-13 21:03:00+00:00

Jumlah tweet per tanggal Jakarta:
tanggal
2026-10-13    219
2026-10-14     15
Name: count, dtype: int64

In [47]:
print("Hasil penandaan relevansi:")
print(
    df_cleaning["relevansi_awal"]
    .value_counts()
    .rename(index={True: "Berpotensi relevan", False: "Perlu diperiksa"})
)

# Lihat tweet yang tidak terdeteksi relevan
display(
    df_cleaning.loc[
        ~df_cleaning["relevansi_awal"],
        ["id", "createdAt", "original_text"]
    ].head(20)
)

Hasil penandaan relevansi:
relevansi_awal
Berpotensi relevan    217
Perlu diperiksa        17
Name: count, dtype: int64

,id,createdAt,original_text
34,2109903590303396323,2026-10-13 07:06:30+00:00,capcut naik haji maap yaa guyss kosongg
36,2109859125232550355,2026-10-13 04:09:49+00:00,Capcut naik hajiið­ð­
38,2109857413927158009,2026-10-13 04:03:01+00:00,@Lucibxz sini bisa fast
39,2109856715026153505,2026-10-13 04:00:14+00:00,@elizpace sini kak\n\nCapcut 7D Rp.5.000\nCapc...
40,2109856440064324095,2026-10-13 03:59:09+00:00,@meihuaovv Sini bisa fast
41,2109856260535570577,2026-10-13 03:58:26+00:00,@snoopyjw0 Capcut 7D Rp.5.000\nCapcut 30D shar...
42,2109855973468942397,2026-10-13 03:57:17+00:00,serem ujian audit ð¨ð¨
43,2109854938390307182,2026-10-13 03:53:11+00:00,"Today ready ini saja yaa, full garansi dan ant..."
44,2109849162284171421,2026-10-13 03:30:14+00:00,"hai haiii aku openggg, after ujiannn gemeterannn"
56,2110015915177988109,2026-10-13 14:32:51+00:00,à­¨à­§ Ëð·ð¹ð¶ð´ð¶ ð´ð°ðµð¼...
86,2109935943146995788,2026-10-13 09:15:04+00:00,DIMSUM MIE GACOAN ðµ\nð¦ Udang Keju udang ...
114,2109842332921262451,2026-10-13 03:03:05+00:00,@ayyalune RO dari awal VC sudah drekam seperti...
146,2110006397035573509,2026-10-13 13:55:01+00:00,Bisa beli banyakk\nhttps://t.co/5PRqMQaVEC htt...
170,2109955396341489668,2026-10-13 10:32:22+00:00,ð° Rp 10.000\nâ° 18:00 WIB\n\nSKIN1004 Mada...
200,2109867642215624949,2026-10-13 04:43:40+00:00,ð° Rp 1.000\nâ° 12:00 WIB\n\nBASIKE Penyedo...
201,2109867197791363366,2026-10-13 04:41:54+00:00,ð° Rp10.000 â° 12:00 WIB\nSKIN1004 Madagasc...
204,2109865866120896629,2026-10-13 04:36:36+00:00,SIAP SIAP INPUT KODEâ¼ï¸\nâ° 11:00 WIB\nKod...

dari 234 tweet, 217 terdeteksi berpotensi relevan dan 17 perlu diperiksa.

In [48]:
#Kolom keputusan Relevansi Manual
# Salin data agar keputusan relevansi tercatat terpisah
df_cleaning["relevansi_manual"] = "belum_diperiksa"

# Tandai ID tweet yang jelas tidak berkaitan berdasarkan
# teks yang telah kamu tampilkan.
id_tidak_relevan = [
    "2109903590303396323",  # CapCut naik haji
    "2109859125232550355",  # CapCut naik haji
    "2109855973468942397",  # Ujian audit
    "2109849162284171421",  # Percakapan setelah ujian
]

df_cleaning.loc[
    df_cleaning["id"].astype(str).isin(id_tidak_relevan),
    "relevansi_manual"
] = "tidak_relevan"

print(df_cleaning["relevansi_manual"].value_counts())

display(
    df_cleaning[
        df_cleaning["relevansi_manual"] != "belum_diperiksa"
    ][["id", "original_text", "relevansi_manual"]]
)

relevansi_manual
belum_diperiksa    230
tidak_relevan        4
Name: count, dtype: int64

,id,original_text,relevansi_manual
34,2109903590303396323,capcut naik haji maap yaa guyss kosongg,tidak_relevan
36,2109859125232550355,Capcut naik hajiið­ð­,tidak_relevan
42,2109855973468942397,serem ujian audit ð¨ð¨,tidak_relevan
44,2109849162284171421,"hai haiii aku openggg, after ujiannn gemeterannn",tidak_relevan

In [49]:
#tweet yg blum di putuskan
display(
    df_cleaning.loc[
        df_cleaning["relevansi_manual"] == "belum_diperiksa",
        ["id", "createdAt", "original_text", "relevansi_awal"]
    ].sort_values("createdAt")
)

,id,createdAt,original_text,relevansi_awal
223,2109803808322736167,2026-10-13 00:30:00+00:00,ðï¸ 13 Oktober \nShopeefood Diskon 100% s/...,True
222,2109807465277935816,2026-10-13 00:44:32+00:00,OPEN JASTIP SHOPEEð\n\nâTitip link jualan...,True
221,2109811355582607538,2026-10-13 01:00:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,True
24,2109812462103281734,2026-10-13 01:04:24+00:00,@ayrzz_ biasanya pas tanggal kembar aja kak,True
123,2109815179114696878,2026-10-13 01:15:11+00:00,"Halo kakak, bagi yg butuh carousell atau feed ...",True
...,...,...,...,...
25,2110093957330059731,2026-10-13 19:42:57+00:00,@broystv nggak sampe semenit kak 10.500 aja la...,True
127,2110098247138037949,2026-10-13 20:00:00+00:00,ðï¸ 14 Oktober \nShopeefood Diskon 100% s/...,True
126,2110102056979849529,2026-10-13 20:15:08+00:00,Open jastip trs sampe ga sadar voucher gratis ...,True
125,2110105796902273156,2026-10-13 20:30:00+00:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,True
124,2110114100755992969,2026-10-13 21:03:00+00:00,ðï¸ 14 Oktober \nShopeefood Diskon 100% s/...,True

In [50]:

# Tampilkan seluruh tweet untuk pemeriksaan relevansi manual
kolom_tinjau = [
    "id",
    "tanggal",
    "original_text",
    "clean_text",
    "relevansi_awal"
]

kolom_tersedia = [
    kolom for kolom in kolom_tinjau
    if kolom in df_cleaning.columns
]

display(
    df_cleaning[kolom_tersedia]
    .sort_values("tanggal")
    .reset_index(drop=True)
)

print("Total tweet:", len(df_cleaning))
print("\nHasil penyaringan otomatis:")
print(df_cleaning["relevansi_awal"].value_counts())

,id,tanggal,original_text,clean_text,relevansi_awal
0,2109803808322736167,2026-10-13 07:30:00+07:00,ðï¸ 13 Oktober \nShopeefood Diskon 100% s/...,ðï 13 oktober shopeefood diskon 100% s/d 35rb ...,True
1,2109807465277935816,2026-10-13 07:44:32+07:00,OPEN JASTIP SHOPEEð\n\nâTitip link jualan...,open jastip shopeeð âtitip link jualan 2 5k âj...,True
2,2109811355582607538,2026-10-13 08:00:00+07:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...,True
3,2109812462103281734,2026-10-13 08:04:24+07:00,@ayrzz_ biasanya pas tanggal kembar aja kak,biasanya pas tanggal kembar aja kak,True
4,2109815179114696878,2026-10-13 08:15:11+07:00,"Halo kakak, bagi yg butuh carousell atau feed ...",halo kakak bagi yg butuh carousell atau feed i...,True
...,...,...,...,...,...
229,2110093957330059731,2026-10-14 02:42:57+07:00,@broystv nggak sampe semenit kak 10.500 aja la...,nggak sampe semenit kak 10.500 aja lagi promo ...,True
230,2110098247138037949,2026-10-14 03:00:00+07:00,ðï¸ 14 Oktober \nShopeefood Diskon 100% s/...,ðï 14 oktober shopeefood diskon 100% s/d 35rb ...,True
231,2110102056979849529,2026-10-14 03:15:08+07:00,Open jastip trs sampe ga sadar voucher gratis ...,open jastip trs sampe ga sadar voucher gratis ...,True
232,2110105796902273156,2026-10-14 03:30:00+07:00,â¼ï¸Voucher shopeefood diskon 90% max 19rb +...,â1 4ï voucher shopeefood diskon 90% max 19rb g...,True
233,2110114100755992969,2026-10-14 04:03:00+07:00,ðï¸ 14 Oktober \nShopeefood Diskon 100% s/...,ðï 14 oktober shopeefood diskon 100% s/d 35rb ...,True

Total tweet: 234

Hasil penyaringan otomatis:
relevansi_awal
True     217
False     17
Name: count, dtype: int64

In [51]:
import re

# Kategori 1: indikasi langsung terkait tanggal kembar 10.10
pola_langsung = (
    r"10\s*[./-]\s*10|"
    r"tanggal\s+kembar|"
    r"10\.10|"
    r"10\s*10|"
    r"big\s*sale"
)

# Kategori 2: indikasi promosi marketplace
pola_kontekstual = (
    r"shopee|shopeefood|tokopedia|lazada|blibli|"
    r"voucher|kupon|diskon|discount|promo|promosi|"
    r"flash\s*sale|flashsale|gratis\s*ongkir|"
    r"kode\s*promo|kode\s*voucher|"
    r"belanja\s+online|marketplace"
)

teks = df_cleaning["original_text"].fillna("")

langsung = teks.str.contains(
    pola_langsung, case=False, regex=True
)

kontekstual = teks.str.contains(
    pola_kontekstual, case=False, regex=True
)

df_cleaning["kategori_relevansi_awal"] = "perlu ditinjau"

df_cleaning.loc[
    kontekstual & ~langsung,
    "kategori_relevansi_awal"
] = "indikasi kontekstual"

df_cleaning.loc[
    langsung,
    "kategori_relevansi_awal"
] = "indikasi langsung"

print(df_cleaning["kategori_relevansi_awal"].value_counts())

display(
    df_cleaning[
        [
            "id",
            "original_text",
            "kategori_relevansi_awal"
        ]
    ].head(30)
)

kategori_relevansi_awal
indikasi kontekstual    174
indikasi langsung        43
perlu ditinjau           17
Name: count, dtype: int64

,id,original_text,kategori_relevansi_awal
0,2110049779162153142,@afrkml ak kemarin beli 3 hp di shopee aman am...,indikasi langsung
1,2110037673167737100,close yaa! timaacii yang sudah ikutan dan mera...,indikasi langsung
2,2110037344552186209,btw kalo abis tanggal kembar emang gini yaa? s...,indikasi langsung
3,2110010539950899311,Ya onlen kan banyak diskonannyaa terus byk bon...,indikasi langsung
4,2110004575105388837,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J...",indikasi langsung
5,2110000127884828879,"Syongsok menikah di tanggal kembar, anaknya ke...",indikasi langsung
6,2109988569775591730,@nattwtij Masama sayangkuuu ð\nKalau beli e...,indikasi langsung
7,2109968183469957508,Ges mau nanyað\nShopee kalian kalau lagi ga...,indikasi langsung
8,2109968091128148197,"Tes kekencangan si Jisulife 10 ini oke sih, ad...",indikasi langsung
9,2109966398118408698,@riorkha Diskon tanggal kembar oren dong 9.9,indikasi langsung
10,2109950795177402757,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...,indikasi langsung
11,2109938277319069736,ini pelayanan sebesar xiaomi ngehadapin custom...,indikasi langsung
12,2109928760682414103,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...,indikasi langsung
13,2109925742343839766,siapapun yang menginisiasi tanggal kembar disk...,indikasi langsung
14,2109922315643580669,"@LambeSahamjja emang melemah njir, buktinya ev...",indikasi langsung
15,2109905523567202516,@snowdropnikita KAN NGENES BARU KEMAREN AJA HA...,indikasi langsung
16,2109903036479103119,Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKe...,indikasi langsung
17,2109899261253222833,@usedtob3me Cetaphil bisa murah kalau beli di ...,indikasi langsung
18,2109890173035335745,Help RT or repost tweet di bawah ini guyss ð¥...,indikasi langsung
19,2109868003282341966,"Hidup tuh jangan terlalu serius, nanti cepat t...",indikasi langsung
20,2109865827751370820,mending beli pb ugreen 20.000mAh sekarang 310r...,indikasi langsung
21,2109864834271678599,@Boyvulations Ga pas tanggal kembar biar tiap ...,indikasi langsung
22,2109853978360160326,@usedtob3me Cetaphil murah kak kalau belinya t...,indikasi langsung
23,2109825857250533387,@ilymoontae jamayyy pas tanggal kembar ðð...,indikasi langsung
24,2109812462103281734,@ayrzz_ biasanya pas tanggal kembar aja kak,indikasi langsung
25,2110093957330059731,@broystv nggak sampe semenit kak 10.500 aja la...,indikasi langsung
26,2110057610624078330,"@watermewlons_ 169 lagi, ga ada bonus promo 10...",indikasi langsung
27,2110051463494087062,@viescence @kalendyer maaf kak.. akuu lgi prom...,indikasi langsung
28,2110021556219126037,"@atmaYOUHA ketinggalan promo 10.10 :"")",indikasi langsung
29,2110001009879892195,@jjkthsweetiee aku beli di toko official tikto...,indikasi langsung

In [52]:
# Periksa 43 tweet dengan indikasi langsung
df_langsung = df_cleaning[
    df_cleaning["kategori_relevansi_awal"] == "indikasi langsung"
].copy()

display(
    df_langsung[
        ["id", "tanggal", "original_text"]
    ].to_string(index=False)
)

'                 id                   tanggal                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 original_text\n2110049779162153142 2026-10-13 23:47:24+07:00                                                                                                                                                                                                                                                                     @afrkml ak kemarin beli 3 hp di shopee aman aman aja. tapi lihat postingan kaya gini harus hati2 juga sih\\n\\nsebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik\n2110037673167737100 2026-10-13 22:59:18+07:00                                                                                                                                                                                                                                                                                                                                                                                    close yaa! timaacii yang sudah ikutan dan meramaikan :3 sampai bertemu di tanggal kembar selanjutnya iaa ð\x9f§\x8dð\x9f\x8f»â\x80\x8dâ\x99\x80ï¸\x8f\n2110037344552186209 2026-10-13 22:58:00+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                         btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss\n2110010539950899311 2026-10-13 21:11:29+07:00                                                                                                                                                                                                                       Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja\n2110004575105388837 2026-10-13 20:47:47+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                               @delvkd Iya Iannn, pas tanggal kembar wkwkwk Jisulife lagi ð\x9f\x98\xad\n2110000127884828879 2026-10-13 20:30:07+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                                  Syongsok menikah di tanggal kembar, anaknya kembar juga gak?\n2109988569775591730 2026-10-13 19:44:11+07:00                                                                                                                                                                                                                                                                                                                                                                     @nattwtij Masama sayangkuuu ð\x9f\x98\x98\\nKalau beli elektronik begitu saranku better beli di tanggal kembar ð\x9f\x98\x8d potongan nya sering gila-gilaan\n2109968183469957508 2026-10-13 18:23:10+07:00                                                                                                                                                                                                                                                                                                                                                  Ges mau nanyað\x9f\x98\x82\\nShopee kalian kalau lagi ga event tanggal kembar atau tanggal 25, tetep bisa freeong?\\n\\n((Nanya dulu, kali aja tiba2 aku mau sale lagi))\n2109968091128148197 2026-10-13 18:22:48+07:00                                                                                                                                                                                                                                                    Tes kekencangan si Jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. Tapi jisulife 5 cuma ada 3 tingkatan angin \\n\\nBeli pas tanggal kembar oke banget diskon nya ð\x9f¥° https://t.co/5E17pVy4YR\n2109966398118408698 2026-10-13 18:16:05+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                  @riorkha Diskon tanggal kembar oren dong 9.9\n2109950795177402757 2026-10-13 17:14:05+07:00                                                                                                                                                                                                                                                                                                                                                                                  @Weist9953 aku ð\x9f\x98\xadâ\x98\x9dï¸\x8f tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong gak sih?\n2109938277319069736 2026-10-13 16:24:20+07:00 ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?\n2109928760682414103 2026-10-13 15:46:31+07:00                                                                                                                                                                                                                                                                                                                                                                                                      @usedtob3me Ga ada Kak\\nBeli tanggal kembar aja\\nAku pake sampe ke bokong dan beneran bagus ð\x9f\x98\xadð\x9f\x98\xadð\x9f\x98\xad\n2109925742343839766 2026-10-13 15:34:32+07:00                                                                                                                                                                                                                                                                                                                                                                                                              siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampe 7 turunan\n2109922315643580669 2026-10-13 15:20:55+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                         @LambeSahamjja emang melemah njir, buktinya event tanggal kembar sepi\n2109905523567202516 2026-10-13 14:14:11+07:00                                                                                                                                                                                                                                                             @snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\\n\\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD\n2109903036479103119 2026-10-13 14:04:18+07:00                                                                                                                                                                                                Jangan Biarin Saldo E-Wallet Kosong!ð\x9f\x98\xad\\n\\nKeranjang belanjaan tanggal kembar besok udah penuh, tapi saldo e-wallet masih kosong melompong? Top up e-wallet favoritmu di Orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!ð\x9f\x9b\x8dï¸\x8fð\x9f\x91\x8c https://t.co/VYdb3cw5Zn\n2109899261253222833 2026-10-13 13:49:18+07:00                                                                                                                                                                                                                                                                                           @usedtob3me Cetaphil bisa murah kalau beli di Lazada (watsons)\\nKalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar)\\nLebih murah lagi ada hadalabo gokujyun (agak berbusa dikit)\n2109890173035335745 2026-10-13 13:13:11+07:00                                                                                                                                                                                                                                                                           Help RT or repost tweet di bawah ini guyss ð\x9f¥º #zonauang\\n\\nAku ada optip open titip layout dalam rangka tanggal kembar 10.10 dengan harga spesial special price promo diskon 6k aja!!\\n\\nBisa sampai tanggal 17 Oktober yaaa ð\x9f\x98\x8d\n2109868003282341966 2026-10-13 11:45:06+07:00                                                                                                                                                                                                                      Hidup tuh jangan terlalu serius, nanti cepat tua. Tapi kalau terlalu santai, takut miskin. Mau kerja capek, nggak kerja nggak punya duit. Mau hemat, banyak godaan. Mau kaya, rebahan mulu. Ya Allah, sebenarnya aku ini maunya hidup atau cuma mau menikmati promo tanggal kembar? ð\x9f\x98\xad\n2109865827751370820 2026-10-13 11:36:27+07:00                                                                                                                                                                                                                                                                                                                            mending beli pb ugreen 20.000mAh sekarang 310rb,atau nanti 11.11? waktu bayarnya sampe jam 1 ini, bayar aja apa nunggu 11.11 ya? tapi kadang tanggal kembar jg promonya yaudah aja\n2109864834271678599 2026-10-13 11:32:30+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                     @Boyvulations Ga pas tanggal kembar biar tiap anniv bisa CO dapet diskon?\n2109853978360160326 2026-10-13 10:49:22+07:00                                                                                                                                                                                                                                                                                                                                                                                 @usedtob3me Cetaphil murah kak kalau belinya tanggal kembar pake koin di lazada + voucher beauty\\nJangan di oren karena mahal\n2109825857250533387 2026-10-13 08:57:37+07:00                                                                                                                                                                                                                                                                                                                                @ilymoontae jamayyy pas tanggal kembar ð\x9f\x91\x90ð\x9f\x91\x90 baterai 71% ak pakai seharian di mobil masi 54% malah udah jatuh dari kasur ke lantai tp masi bernyawa https://t.co/hRlYydkfbV\n2109812462103281734 2026-10-13 08:04:24+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                   @ayrzz_ biasanya pas tanggal kembar aja kak\n2110093957330059731 2026-10-14 02:42:57+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                            @broystv nggak sampe semenit kak 10.500 aja lagi promo 10.10 kakak\n2110057610624078330 2026-10-14 00:18:32+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                                         @watermewlons_ 169 lagi, ga ada bonus promo 10.10 kah\n2110051463494087062 2026-10-13 23:54:06+07:00                                                                                                                                                                                                                                                                                                                                                                                                               @viescence @kalendyer maaf kak.. akuu lgi promo 10.10 sampai tanggal 15 aja sih kakð\x9f\x98\x94ð\x9f\x99\x8fð\x9f\x8f¼\n2110021556219126037 2026-10-13 21:55:15+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @atmaYOUHA ketinggalan promo 10.10 :")\n2110001009879892195 2026-10-13 20:33:37+07:00                                                                                                                                                                                                                                                                                                                                                                                                                    @jjkthsweetiee aku beli di toko official tiktoknya jisulife kak, waktu promo 10.10 kemarin\n2109973839958647251 2026-10-13 18:45:39+07:00                                                                                                                                                                                                     Siapa nih yang kalau buka marketplace cuma niat lihat-lihat, tapi malah jadi belanja?\\n\\nApalagi Promo 10.10 Zarfix masih berlangsung dengan diskon sampai 15%!\\n\\nYuk, cek produk incaranmu sekarang di Zarfix!\\n\\n#Zarfix #Promo1010 #BelanjaOnline #DiskonZarfix #RacunBelanja https://t.co/G3vNWfSe7H\n2109958029974413786 2026-10-13 17:42:50+07:00                                                                                                                                                                                                                 WTSS GAIS!! \\n \\ndijual sepatu skechers MASIH BARU BGT BARU DATENG. dijual karna salah size kekecilan ternyata, beli di harga 1.000k kena promo 10.10. aku jual 950k aja boleh nego tipis dm aja ya harga yg masuk akal soalnya baru bgt\\n\\nsize 37.5 insole 24.5 (complete) \\n\\ndom. bandung\n2109920827214905602 2026-10-13 15:15:00+07:00                                                                                                                                                                                                                                                                                                                                ð\x9f\x93\x8cNambang koin Lazada\\n\\nTambahan potongan harga\\nhttps://t.co/ch4ncAmAaf\\n(buku, Skincare, produk lain juga banyak)\\n\\nâ\x9c\x85Mumpung masih promo 10.10 https://t.co/IJhGkcQOqk\n2109913124266742170 2026-10-13 14:44:23+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                                   @lkiciw ciwi rs carmen promo 10.10\\nhttps://t.co/Asmzn4ne2x\n2109887237064409233 2026-10-13 13:01:31+07:00                                                                                                                                                                                                                                                                                                                                                                                                                                                           @eyesonhyeon harga promo 10.10 kak.. 10.500 aja kak\n2109857693217562880 2026-10-13 11:04:07+07:00                                                                                                                                                                                                                           

In [53]:
# Tampilkan 15 tweet per bagian
bagian = 0  # ubah menjadi 1, 2, dan seterusnya
ukuran_bagian = 15

mulai = bagian * ukuran_bagian
selesai = mulai + ukuran_bagian

display(
    df_langsung[
        ["id", "tanggal", "original_text"]
    ].iloc[mulai:selesai]
)

,id,tanggal,original_text
0,2110049779162153142,2026-10-13 23:47:24+07:00,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,2110037673167737100,2026-10-13 22:59:18+07:00,close yaa! timaacii yang sudah ikutan dan mera...
2,2110037344552186209,2026-10-13 22:58:00+07:00,btw kalo abis tanggal kembar emang gini yaa? s...
3,2110010539950899311,2026-10-13 21:11:29+07:00,Ya onlen kan banyak diskonannyaa terus byk bon...
4,2110004575105388837,2026-10-13 20:47:47+07:00,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."
5,2110000127884828879,2026-10-13 20:30:07+07:00,"Syongsok menikah di tanggal kembar, anaknya ke..."
6,2109988569775591730,2026-10-13 19:44:11+07:00,@nattwtij Masama sayangkuuu ð\nKalau beli e...
7,2109968183469957508,2026-10-13 18:23:10+07:00,Ges mau nanyað\nShopee kalian kalau lagi ga...
8,2109968091128148197,2026-10-13 18:22:48+07:00,"Tes kekencangan si Jisulife 10 ini oke sih, ad..."
9,2109966398118408698,2026-10-13 18:16:05+07:00,@riorkha Diskon tanggal kembar oren dong 9.9
10,2109950795177402757,2026-10-13 17:14:05+07:00,@Weist9953 aku ð­âï¸ tapi aku mau tanyaa ...
11,2109938277319069736,2026-10-13 16:24:20+07:00,ini pelayanan sebesar xiaomi ngehadapin custom...
12,2109928760682414103,2026-10-13 15:46:31+07:00,@usedtob3me Ga ada Kak\nBeli tanggal kembar aj...
13,2109925742343839766,2026-10-13 15:34:32+07:00,siapapun yang menginisiasi tanggal kembar disk...
14,2109922315643580669,2026-10-13 15:20:55+07:00,"@LambeSahamjja emang melemah njir, buktinya ev..."

In [54]:
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", 50)

display(
    df_langsung[
        ["id", "original_text"]
    ].iloc[0:15]
)

,id,original_text
0,2110049779162153142,"@afrkml ak kemarin beli 3 hp di shopee aman aman aja. tapi lihat postingan kaya gini harus hati2 juga sih\n\nsebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik"
1,2110037673167737100,close yaa! timaacii yang sudah ikutan dan meramaikan :3 sampai bertemu di tanggal kembar selanjutnya iaa ð§ð»ââï¸
2,2110037344552186209,btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss
3,2110010539950899311,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja"
4,2110004575105388837,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk Jisulife lagi ð­"
5,2110000127884828879,"Syongsok menikah di tanggal kembar, anaknya kembar juga gak?"
6,2109988569775591730,@nattwtij Masama sayangkuuu ð\nKalau beli elektronik begitu saranku better beli di tanggal kembar ð potongan nya sering gila-gilaan
7,2109968183469957508,"Ges mau nanyað\nShopee kalian kalau lagi ga event tanggal kembar atau tanggal 25, tetep bisa freeong?\n\n((Nanya dulu, kali aja tiba2 aku mau sale lagi))"
8,2109968091128148197,"Tes kekencangan si Jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. Tapi jisulife 5 cuma ada 3 tingkatan angin \n\nBeli pas tanggal kembar oke banget diskon nya ð¥° https://t.co/5E17pVy4YR"
9,2109966398118408698,@riorkha Diskon tanggal kembar oren dong 9.9
10,2109950795177402757,"@Weist9953 aku ð­âï¸ tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong gak sih?"
11,2109938277319069736,"ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?"
12,2109928760682414103,@usedtob3me Ga ada Kak\nBeli tanggal kembar aja\nAku pake sampe ke bokong dan beneran bagus ð­ð­ð­
13,2109925742343839766,"siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampe 7 turunan"
14,2109922315643580669,"@LambeSahamjja emang melemah njir, buktinya event tanggal kembar sepi"

In [55]:
# Label manual untuk 15 tweet pertama yang telah ditinjau
label_manual = {
    "2110049779162153142": "relevan_kontekstual",
    "2110037673167737100": "relevan_kontekstual",
    "2110037344552186209": "tidak_relevan",
    "2110010539950899311": "relevan_kontekstual",
    "2110004575105388837": "relevan_kontekstual",
    "2110000127884828879": "tidak_relevan",
    "2109988569775591730": "relevan_kontekstual",
    "2109968183469957508": "relevan_kontekstual",
    "2109968091128148197": "relevan_kontekstual",
    "2109966398118408698": "relevan_kontekstual",
    "2109950795177402757": "relevan_kontekstual",
    "2109938277319069736": "relevan_kontekstual",
    "2109928760682414103": "relevan_kontekstual",
    "2109925742343839766": "relevan_kontekstual",
    "2109922315643580669": "relevan_kontekstual"
}

# Buat kolom jika belum ada, tanpa menghapus label sebelumnya
if "relevansi_manual" not in df_cleaning.columns:
    df_cleaning["relevansi_manual"] = "belum_diperiksa"

df_cleaning["id"] = df_cleaning["id"].astype(str)

for tweet_id, label in label_manual.items():
    df_cleaning.loc[
        df_cleaning["id"] == tweet_id,
        "relevansi_manual"
    ] = label

print(df_cleaning["relevansi_manual"].value_counts())

display(
    df_cleaning[
        df_cleaning["id"].isin(label_manual.keys())
    ][["id", "original_text", "relevansi_manual"]]
)

relevansi_manual
belum_diperiksa        215
relevan_kontekstual     13
tidak_relevan            6
Name: count, dtype: int64

,id,original_text,relevansi_manual
0,2110049779162153142,"@afrkml ak kemarin beli 3 hp di shopee aman aman aja. tapi lihat postingan kaya gini harus hati2 juga sih\n\nsebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik",relevan_kontekstual
1,2110037673167737100,close yaa! timaacii yang sudah ikutan dan meramaikan :3 sampai bertemu di tanggal kembar selanjutnya iaa ð§ð»ââï¸,relevan_kontekstual
2,2110037344552186209,btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss,tidak_relevan
3,2110010539950899311,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja",relevan_kontekstual
4,2110004575105388837,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk Jisulife lagi ð­",relevan_kontekstual
5,2110000127884828879,"Syongsok menikah di tanggal kembar, anaknya kembar juga gak?",tidak_relevan
6,2109988569775591730,@nattwtij Masama sayangkuuu ð\nKalau beli elektronik begitu saranku better beli di tanggal kembar ð potongan nya sering gila-gilaan,relevan_kontekstual
7,2109968183469957508,"Ges mau nanyað\nShopee kalian kalau lagi ga event tanggal kembar atau tanggal 25, tetep bisa freeong?\n\n((Nanya dulu, kali aja tiba2 aku mau sale lagi))",relevan_kontekstual
8,2109968091128148197,"Tes kekencangan si Jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. Tapi jisulife 5 cuma ada 3 tingkatan angin \n\nBeli pas tanggal kembar oke banget diskon nya ð¥° https://t.co/5E17pVy4YR",relevan_kontekstual
9,2109966398118408698,@riorkha Diskon tanggal kembar oren dong 9.9,relevan_kontekstual
10,2109950795177402757,"@Weist9953 aku ð­âï¸ tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong gak sih?",relevan_kontekstual
11,2109938277319069736,"ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?",relevan_kontekstual
12,2109928760682414103,@usedtob3me Ga ada Kak\nBeli tanggal kembar aja\nAku pake sampe ke bokong dan beneran bagus ð­ð­ð­,relevan_kontekstual
13,2109925742343839766,"siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampe 7 turunan",relevan_kontekstual
14,2109922315643580669,"@LambeSahamjja emang melemah njir, buktinya event tanggal kembar sepi",relevan_kontekstual

In [56]:
# Tampilkan tweet nomor 15–29 dari kategori indikasi langsung
pd.set_option("display.max_colwidth", None)

display(
    df_langsung[
        ["id", "original_text"]
    ].iloc[15:30]
)

,id,original_text
15,2109905523567202516,@snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\n\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD
16,2109903036479103119,"Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKeranjang belanjaan tanggal kembar besok udah penuh, tapi saldo e-wallet masih kosong melompong? Top up e-wallet favoritmu di Orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!ðï¸ð https://t.co/VYdb3cw5Zn"
17,2109899261253222833,@usedtob3me Cetaphil bisa murah kalau beli di Lazada (watsons)\nKalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar)\nLebih murah lagi ada hadalabo gokujyun (agak berbusa dikit)
18,2109890173035335745,Help RT or repost tweet di bawah ini guyss ð¥º #zonauang\n\nAku ada optip open titip layout dalam rangka tanggal kembar 10.10 dengan harga spesial special price promo diskon 6k aja!!\n\nBisa sampai tanggal 17 Oktober yaaa ð
19,2109868003282341966,"Hidup tuh jangan terlalu serius, nanti cepat tua. Tapi kalau terlalu santai, takut miskin. Mau kerja capek, nggak kerja nggak punya duit. Mau hemat, banyak godaan. Mau kaya, rebahan mulu. Ya Allah, sebenarnya aku ini maunya hidup atau cuma mau menikmati promo tanggal kembar? ð­"
20,2109865827751370820,"mending beli pb ugreen 20.000mAh sekarang 310rb,atau nanti 11.11? waktu bayarnya sampe jam 1 ini, bayar aja apa nunggu 11.11 ya? tapi kadang tanggal kembar jg promonya yaudah aja"
21,2109864834271678599,@Boyvulations Ga pas tanggal kembar biar tiap anniv bisa CO dapet diskon?
22,2109853978360160326,@usedtob3me Cetaphil murah kak kalau belinya tanggal kembar pake koin di lazada + voucher beauty\nJangan di oren karena mahal
23,2109825857250533387,@ilymoontae jamayyy pas tanggal kembar ðð baterai 71% ak pakai seharian di mobil masi 54% malah udah jatuh dari kasur ke lantai tp masi bernyawa https://t.co/hRlYydkfbV
24,2109812462103281734,@ayrzz_ biasanya pas tanggal kembar aja kak
25,2110093957330059731,@broystv nggak sampe semenit kak 10.500 aja lagi promo 10.10 kakak
26,2110057610624078330,"@watermewlons_ 169 lagi, ga ada bonus promo 10.10 kah"
27,2110051463494087062,@viescence @kalendyer maaf kak.. akuu lgi promo 10.10 sampai tanggal 15 aja sih kakððð¼
28,2110021556219126037,"@atmaYOUHA ketinggalan promo 10.10 :"")"
29,2110001009879892195,"@jjkthsweetiee aku beli di toko official tiktoknya jisulife kak, waktu promo 10.10 kemarin"

In [58]:
label_manual_lanjutan = {
    "2109905523567202516": "relevan_kontekstual",
    "2109903036479103119": "relevan_kontekstual",
    "2109899261253222833": "relevan_kontekstual",
    "2109890173035335745": "relevan_langsung",
    "2109868003282341966": "relevan_kontekstual",
    "2109865827751370820": "relevan_kontekstual",
    "2109864834271678599": "relevan_kontekstual",
    "2109853978360160326": "relevan_kontekstual",
    "2109825857250533387": "perlu_konteks",
    "2109812462103281734": "perlu_konteks",
    "2110093957330059731": "relevan_langsung",
    "2110057610624078330": "relevan_langsung",
    "2110051463494087062": "relevan_langsung",
    "2110021556219126037": "relevan_langsung",
    "2110001009879892195": "relevan_langsung"
}

for tweet_id, label in label_manual_lanjutan.items():
    df_cleaning.loc[
        df_cleaning["id"].astype(str) == tweet_id,
        "relevansi_manual"
    ] = label

print(df_cleaning["relevansi_manual"].value_counts())

relevansi_manual
belum_diperiksa        200
relevan_kontekstual     20
tidak_relevan            6
relevan_langsung         6
perlu_konteks            2
Name: count, dtype: int64

In [59]:
display(
    df_langsung[["id", "original_text"]].iloc[30:43]
)

,id,original_text
30,2109973839958647251,"Siapa nih yang kalau buka marketplace cuma niat lihat-lihat, tapi malah jadi belanja?\n\nApalagi Promo 10.10 Zarfix masih berlangsung dengan diskon sampai 15%!\n\nYuk, cek produk incaranmu sekarang di Zarfix!\n\n#Zarfix #Promo1010 #BelanjaOnline #DiskonZarfix #RacunBelanja https://t.co/G3vNWfSe7H"
31,2109958029974413786,"WTSS GAIS!! \n \ndijual sepatu skechers MASIH BARU BGT BARU DATENG. dijual karna salah size kekecilan ternyata, beli di harga 1.000k kena promo 10.10. aku jual 950k aja boleh nego tipis dm aja ya harga yg masuk akal soalnya baru bgt\n\nsize 37.5 insole 24.5 (complete) \n\ndom. bandung"
32,2109920827214905602,"ðNambang koin Lazada\n\nTambahan potongan harga\nhttps://t.co/ch4ncAmAaf\n(buku, Skincare, produk lain juga banyak)\n\nâ Mumpung masih promo 10.10 https://t.co/IJhGkcQOqk"
33,2109913124266742170,@lkiciw ciwi rs carmen promo 10.10\nhttps://t.co/Asmzn4ne2x
35,2109887237064409233,@eyesonhyeon harga promo 10.10 kak.. 10.500 aja kak
37,2109857693217562880,"promo 10.10 hari terakhir, yang mau jajan by request atau ready stock layout yuk masih bisa #zonauang #bealanja"
45,2109846085397315587,@iymuf imut ini mau? rs carmen promo 10.10\nhttps://t.co/Asmzn4ne2x
46,2109845779678712309,@gaunry baru. rs carmen promo 10.10\nhttps://t.co/Asmzn4ne2x
47,2109845760850182428,"Aku juga udah mempertimbangkan selama Â±2 bulan, beneran butuh atau nggak. Akhirnya, karena ada budget dan masih kepikiran terus selama 2 bulan itu, aku checkout pas promo 10.10 kemarin HAHAHA ð­\n\nUntuk shade, aku pilih Notty karena lagi suka lip product yang punya hint cokelat."
50,2110049116285960510,Rekomendasi Info\nKode Voucher Diskon Promo Flash Sale checkout belanja beli di Racun Shopee\n\n14 Oktober 2026\nSerbu Rabu\n10.10 Big Sale\n\nKlaim Voucher Diskonð\nhttps://t.co/MwDA5ImEL6\nhttps://t.co/5AbAhOfDuQ\nhttps://t.co/eY75Lc3DM0\n\nFlashsale pkl 00.00 ð\nhttps://t.co/mYfJRb6buB
51,2110049099395596625,Rekomendasi Info\nKode Voucher Diskon Promo Flash Sale checkout belanja beli di Racun Shopee\n\n14 Oktober 2026\nSerbu Rabu\n10.10 Big Sale\n\nKlaim Voucher Diskonð\nhttps://t.co/MwDA5ImEL6\nhttps://t.co/5AbAhOfDuQ\nhttps://t.co/eY75Lc3DM0\n\nFlashsale pkl 00.00 ð\nhttps://t.co/mYfJRb6buB
66,2110004483220713708,@BudiBaikk riilll budd. siapa tau aja dapat iphone 15 seharga flash sale 10.10 kan wqwqw.
100,2109871052390273111,SHOPEE FITCHECK BIG SALE. Semua Fashion Diskon 25% s/d 100.000. KLAIM Vouchernya di sini\nhttps://t.co/yePZ589ar9\n========

In [60]:
label_manual_kelompok3 = {
    "2109973839958647251": "relevan_langsung",
    "2109958029974413786": "relevan_langsung",
    "2109920827214905602": "relevan_langsung",
    "2109913124266742170": "relevan_langsung",
    "2109887237064409233": "relevan_langsung",
    "2109857693217562880": "relevan_langsung",
    "2109846085397315587": "relevan_langsung",
    "2109845779678712309": "relevan_langsung",
    "2109845760850182428": "relevan_langsung",
    "2110049116285960510": "relevan_langsung",
    "2110049099395596625": "relevan_langsung",
    "2110004483220713708": "relevan_langsung",
    "2109871052390273111": "relevan_langsung"
}

for tweet_id, label in label_manual_kelompok3.items():
    df_cleaning.loc[
        df_cleaning["id"].astype(str) == tweet_id,
        "relevansi_manual"
    ] = label

print(df_cleaning["relevansi_manual"].value_counts(dropna=False))

relevansi_manual
belum_diperiksa        187
relevan_kontekstual     20
relevan_langsung        19
tidak_relevan            6
perlu_konteks            2
Name: count, dtype: int64

In [61]:
id_duplikat_teks = [
    "2110049116285960510",
    "2110049099395596625"
]

display(
    df_cleaning[
        df_cleaning["id"].astype(str).isin(id_duplikat_teks)
    ][["id", "createdAt", "original_text", "clean_text"]]
)

,id,createdAt,original_text,clean_text
50,2110049116285960510,2026-10-13 16:44:46+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Flash Sale checkout belanja beli di Racun Shopee\n\n14 Oktober 2026\nSerbu Rabu\n10.10 Big Sale\n\nKlaim Voucher Diskonð\nhttps://t.co/MwDA5ImEL6\nhttps://t.co/5AbAhOfDuQ\nhttps://t.co/eY75Lc3DM0\n\nFlashsale pkl 00.00 ð\nhttps://t.co/mYfJRb6buB,rekomendasi info kode voucher diskon promo flash sale checkout belanja beli di racun shopee 14 oktober 2026 serbu rabu 10.10 big sale klaim voucher diskonð flashsale pkl 00.00 ð
51,2110049099395596625,2026-10-13 16:44:42+00:00,Rekomendasi Info\nKode Voucher Diskon Promo Flash Sale checkout belanja beli di Racun Shopee\n\n14 Oktober 2026\nSerbu Rabu\n10.10 Big Sale\n\nKlaim Voucher Diskonð\nhttps://t.co/MwDA5ImEL6\nhttps://t.co/5AbAhOfDuQ\nhttps://t.co/eY75Lc3DM0\n\nFlashsale pkl 00.00 ð\nhttps://t.co/mYfJRb6buB,rekomendasi info kode voucher diskon promo flash sale checkout belanja beli di racun shopee 14 oktober 2026 serbu rabu 10.10 big sale klaim voucher diskonð flashsale pkl 00.00 ð

In [62]:
df_kontekstual = df_cleaning[
    df_cleaning["kategori_relevansi_awal"] == "indikasi kontekstual"
].copy()

display(
    df_kontekstual[["id", "original_text"]].head(20)
)

,id,original_text
48,2110063100783464899,"Lazada Flash Sale Digital Rp0\nð 15 Okt\nâ°ï¸ 12:00, 16:00, 18:00, 20:00\n\nMember Center (klik banner seperti di gambar)\nhttps://t.co/qta8X8w11c https://t.co/hX7G5q3S0W"
49,2110049971055771980,"Flash Sale CHERL & KOLRS Rp49.000\nð 14 Okt\nâ° 00:00\n\nCHERL & KOLRS Tas Selempang Wanita Women Bag Putih #01 \nhttps://t.co/yxNnLJgshn\nStok: 10\n\nCHERL & KOLRS Tas Wanita Model Simple Tas Bahu Wanita Stylish #07 \nhttps://t.co/xh0nDROaqO\nVar: Cream, Hitam\nStok: 12\n\nCHERL & KOLRS Tas Selempang Wanita Women Bag Hitam #01 \nhttps://t.co/3KQsCsD0df\nStok: 10"
52,2110045203222626337,Flash Sale Pulsa &amp; Paket Data Mulai Rp1\nâ° 00:00 WIB\n\nCek selengkapnya disini\nSelengkapnya\nhttps://t.co/swvIQ1EeGa https://t.co/7za7XplNKW
53,2110039792805372383,@depelemon di shopee flash sale banyank tuhh yg under 50rb
54,2110021140492267982,@saturnusay Hai Sahabat BTN @saturnusay dengan senang hati kami informasikan mengenai Program Flash Sale PayDay yang berakhir pukul 23:59 WIB setiap harinya. Setiap nasabah hanya memiliki kesempatan 1 kali penukaran di masing- masing merchant selama periode program flash sale. (1/3)
55,2110019724046414018,"+ gabung sama app prem, harganya jadi lebih mahal... Pdhal klo mumpung flash sale yang dibutuhin ya cuma kuotanya ð"
57,2110010515779162334,"SHOPEE FOOD Promo DISKON McDonald's ððð¦ [ BUKA 24 JAM ] Pesan di ShopeeFood Sekarang, langsung diantar â¨\nhttps://t.co/iRlFzRtqEc\n----------"
58,2110010082826358847,"guysss... yg suka da hong pao momoyo aku kasih tau caranya biar bisa dpt harga murah di shopeefood, bahkan lebih murah dr voc tiktok nihh...\npertama pilih yg flash sale double da hong pao di sini https://t.co/4SfGRY3J6u https://t.co/NQ82pe0Ctj"
59,2110009648938139996,"SHOPEE FOOD Promo AYAM GORENG MAK DURA by Hangry ð Pesan sekarang di ShopeeFood, langsung diantar\nhttps://t.co/X5aGIMSG7Q\n------------"
60,2110008785939169453,"ISHOPEE FOOD KOPI FOREVER by Hangry âð¥¤ sekarang ada di ShopeeFood Pesan Sekarang, langsung diantar â¨\nhttps://t.co/EnFdmikd1W\n===="
61,2110007022964154647,"RICHEESE FACTORY Paket Combo Mabar Fire Chicken sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar https://t.co/c97149Lcju\n======="
62,2110006811336364332,"SHOPEE FOOD SEC BOWL â¨ sekarang ada di ShopeeFood Pesan Sekarang, langsung diantar â¨\nhttps://t.co/RcCMnIqrBr\n======="
63,2110006136267317581,"SHOPEE FOOD Promo DIMSUM MIE GACOAN ð sekarang ada di ShopeeFood Pesan Sekarang, langsung diantar\nhttps://t.co/DL4OCXmX8g\n----------"
64,2110005923209224302,"SHOPEE FOOD McDonald [ BUKA 24 JAM ] Paket Keluarga Seru - McFlurry Feat. OREO,Â TanpaÂ Mainan sekarang ada di ShopeeFood Pesan Sekarang, langsung diantar â¨ðµ\nhttps://t.co/w9QyJjIPff\n-----------"
65,2110005237851496817,"PAKET MARTABAK MANIS &amp; TELUR\nSHOPEE FOOD Martabak Pecenongan 78 - Menteng sekarang ada di ShopeeFood Pesan Sekarang, langsung diantar\nhttps://t.co/XVah9QPcTB\n-----------"
67,2109999925001883666,"@JustDan1990 @SeekHustle Aman juga kok, udah biasa beli hp online sejak 2014 jaman flash sale Lazada https://t.co/kTFRdphFEJ"
68,2109996411974824305,@minzclips Kak udh kayak flash sale iphone shopi ð¤£ gaib
69,2109994857867743677,"â½ SUPER SERU FLASH SALE! Kuota 50GB/28 hari cuma Rp100 ribu, udah termasuk langganan Vidio Gold, Prime Video, VISION+, dan WeTV!\n\nð 13-19 Oktober 2026\nð² MyTelkomsel, *363*35#, Outlet terdekat, atau klik https://t.co/wJ1baYFIHO\n\n#SIMPATITerbaikUntukmu #PastiSIMPATI https://t.co/Sn5eSKtriT"
70,2109989780612424124,buset ini kayaknya kamu minum kah nderr?? ini aku dpt flash sale dari tahun 2025 baru habis sebotol loh https://t.co/qDWFqPEs1u
71,2109970808470999197,"aku kan lagi pengen jukut (bayem krispi(?)) terus belilah ayam yang ada jukutnya juga mumpung flash sale, TAPI JUKUTNYA SEDIKIT AYAMNYA DADA ð­ð­ð­ jadi seharusnya aku makan 1 porsi malah jadi 2 karena dapet dada. PADAHAL UDH SHARING SAMA MAMI tapi masih aja kekenyangan ð"

In [63]:
label_kontekstual_1 = {
    "2110063100783464899": "tidak_relevan",
    "2110049971055771980": "tidak_relevan",
    "2110045203222626337": "tidak_relevan",
    "2110039792805372383": "perlu_konteks",
    "2110021140492267982": "tidak_relevan",
    "2110019724046414018": "perlu_konteks",
    "2110010515779162334": "tidak_relevan",
    "2110010082826358847": "perlu_konteks",
    "2110009648938139996": "tidak_relevan",
    "2110008785939169453": "tidak_relevan",
    "2110007022964154647": "tidak_relevan",
    "2110006811336364332": "tidak_relevan",
    "2110006136267317581": "tidak_relevan",
    "2110005923209224302": "tidak_relevan",
    "2110005237851496817": "tidak_relevan",
    "2109999925001883666": "perlu_konteks",
    "2109996411974824305": "perlu_konteks",
    "2109994857867743677": "tidak_relevan",
    "2109989780612424124": "perlu_konteks",
    "2109970808470999197": "perlu_konteks"
}

for tweet_id, label in label_kontekstual_1.items():
    df_cleaning.loc[
        df_cleaning["id"].astype(str) == tweet_id,
        "relevansi_manual"
    ] = label

print(df_cleaning["relevansi_manual"].value_counts(dropna=False))

relevansi_manual
belum_diperiksa        167
relevan_kontekstual     20
tidak_relevan           19
relevan_langsung        19
perlu_konteks            9
Name: count, dtype: int64

In [64]:
display(
    df_kontekstual[["id", "original_text"]].iloc[20:40]
)

,id,original_text
72,2109969887099867251,"@jeonjkmybae Kemaren aku jg ngrasain gitu\nFlash sale under 10jt ujungânya 9,9ð¤§ðª\nPaan diskon cuman 100rebuð¤"
73,2109964097307435259,satu-satunya buku yang aku beli di sembuk dan itupun jastip... ð bener-bener ga ada tenaga buat war-war diskonan kaya gitu soalnya venue yang di malang panas bgt jujur ð­ tahun depan deh kita bantai flash sale 90% sembuk itu #manifesting ðââï¸
74,2109961312382201930,Flash Sale\nâ° 18:00 WIB\n\nRp1.000\nPIOMA Tina Dompet Kartu Wanita 1 Resleting Pouch Mini Waterproof\nCOPPER BROWN\nStok: 1 Pcs\nhttps://t.co/c1AzrHa2Kp\n\nRp1.000\nOPIOBAGS TAS HANDBAG WANITA - TAS TENTENG WANITA - TAS JINJJING FASHION\nMAROON\nStok: 1 Pcs\nhttps://t.co/l3TGTwoGdw https://t.co/23Wh0vwxfi
75,2109960911545102838,@AkulahPara Flash Sale Akhirnya Menemukan Anda Rp10.000
76,2109960673786789955,"Flash Sale\nâ° 18:00 WIB\n\nRp10.000\nFLASH SALE [N 1/27] JILL SKINCARE Bakuchiol Calendula Night Gel 10gr |\nStok: 5 Pcs\nhttps://t.co/1dFVmYMNjS\n\nRp10.000\nFLASH SALE [N 12/26] JILL SKINCARE Arbutin Glow Night Gel | Pelembap\nStok: 5 Pcs\nhttps://t.co/Zi2So8Kwo9\n\nRp10.000\nSKIN1004 Madagascar Centella Soothing Cream 75ml\nStok: 5 Pcs\nhttps://t.co/iPQuBEhXOW\n\nRp10.000\nSKIN1004 Madagascar Centella Ampoule Foam 125ml\nStok: 5 Pcs\nhttps://t.co/md9WmwWUG9\n\nRp10.000\nHONYAN Tas Wanita Minor Defect Sale\nDompet panjang, dompet panjang3\nStok: 30 Pcs\nhttps://t.co/43FF5V7c6u\n\nRp10.000\nSevenDays Body Mist Special Edition Cinnamoroll, Hello Kitty, Kuromi, My Melody |\n7DBM CN PROMO\nStok: 24 Pcs\nhttps://t.co/kn18nv6ivd\n\nRp10.000\nFinally Found You! BLACK RICE+ AI High-Concentrated Brightening Body Soap | Sabun\n2 Pack Soap, 3 Pack Soap, Single Soap\nStok: 15 Pcs\nhttps://t.co/2C63UslJYH"
77,2109960125234758109,Flash Sale Pulsa &amp; Paket Data Mulai Rp1\nâ° 18:00 WIB\n\nCek selengkapnya disini\nSelengkapnya\nhttps://t.co/swvIQ1EeGa https://t.co/Feht5Ke24m
78,2109959560073236805,"SHOPEE FOOD Promo STARBUCKS â sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar â¨\nhttps://t.co/IsgcmMu040\n=============="
79,2109958775339950375,"RICHEESE FACTORY Paket Combo Mabar Whole Flying Chicken sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar \nhttps://t.co/uTuNgcU4CE\n========"
80,2109957656295391677,"SHOPEE FOOD Promo DOMINO'S PIZZA ð sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar â¨\nhttps://t.co/RawP9ocpg4\n====="
81,2109957061169844732,"SHOPEE FOOD Promo BURGER KING ðð MENU BURGER &amp; AYAM. Pesan sekarang di ShopeeFood, langsung diantar \nhttps://t.co/rNwICa3EQA\n---------------"
82,2109955969572884550,"SHOPEE FOOD PIZZA HUT Delivery ð Pesan sekarang di ShopeeFood, langsung diantar â¨\nhttps://t.co/MWGsdWuqEP\n====="
83,2109955293387919767,SHOPEE SPESIAL PROMO DISKON APPLE IPHONE SERES ð Apple Iphone Premium Reseller Indonesia IBOX Official Shop Shopee. Garansi Resmi. Cek di sini \nhttps://t.co/OUyPgYRWyq\n==========
84,2109948842674475038,"Aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa + gipiti 1d 8u onlii 8k . Cuma satu doang. Deem untuk claim \n\n#zonauang #zonajajan"
85,2109943701669814699,"@_Hrst amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk"
87,2109934928934920583,"SHOPEE FOOD Promo Diskon KFC K Duo Deals sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar\nhttps://t.co/HDLvLZpH1N\n========"
88,2109934123645304937,"SHOPEE FOOD McDonalds PaNas 2 Krispy, Large sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar. https://t.co/irJKDJwUVQ\n--------"
89,2109918129967227000,"SHOPEE FOOD ICHIBAN SUSHI ð±ð£ð¤ Pesan sekarang di ShopeeFood, langsung diantar â¨\nhttps://t.co/T3RQ7OZtTR\n======="
90,2109911289082626551,"SHOPEE FOOD Promo SOLARIA ð Pesan sekarang di ShopeeFood , langsung diantar\nhttps://t.co/YdLpWNHdqu\n-------------"
91,2109893383951130994,"SHOPEE FOOD Promo AYAM GEPUK PAK GEMBUS ð sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar â¨\nhttps://t.co/yJVMFGOS0N\n========="
92,2109891116611035510,"SHOPEE FOOD Promo UENA Nasi Ayam dan Mie Ayam ð Pesan sekarang di ShopeeFood, langsung diantar\nhttps://t.co/rEv1gc1gMn\n====="

In [65]:
label_kontekstual_2 = {
    "2109969887099867251": "perlu_konteks",
    "2109964097307435259": "perlu_konteks",
    "2109961312382201930": "tidak_relevan",
    "2109960911545102838": "perlu_konteks",
    "2109960673786789955": "tidak_relevan",
    "2109960125234758109": "tidak_relevan",
    "2109959560073236805": "tidak_relevan",
    "2109958775339950375": "tidak_relevan",
    "2109957656295391677": "tidak_relevan",
    "2109957061169844732": "tidak_relevan",
    "2109955969572884550": "tidak_relevan",
    "2109955293387919767": "perlu_konteks",
    "2109948842674475038": "tidak_relevan",
    "2109943701669814699": "perlu_konteks",
    "2109934928934920583": "tidak_relevan",
    "2109934123645304937": "tidak_relevan",
    "2109918129967227000": "tidak_relevan",
    "2109911289082626551": "tidak_relevan",
    "2109893383951130994": "tidak_relevan",
    "2109891116611035510": "tidak_relevan"
}

for tweet_id, label in label_kontekstual_2.items():
    df_cleaning.loc[
        df_cleaning["id"].astype(str) == tweet_id,
        "relevansi_manual"
    ] = label

print(df_cleaning["relevansi_manual"].value_counts(dropna=False))

relevansi_manual
belum_diperiksa        147
tidak_relevan           34
relevan_kontekstual     20
relevan_langsung        19
perlu_konteks           14
Name: count, dtype: int64

In [66]:
display(
    df_kontekstual[["id", "original_text"]].iloc[40:60]
)

,id,original_text
93,2109886014864974217,"SHOPEE FOOD Promo HOKBEN ð± Lokasari sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar! \nhttps://t.co/GKaxrqOZlc\n====="
94,2109885627802030441,"SHOPEE FOOD Promo MANG KATSU, Nasi Katsu Ayam ð± sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar â¨\nhttps://t.co/WxoXkKfZqM\n==========="
95,2109882272426205430,"SHOPEE FOOD Promo Dbesto [ CHICKEN &amp; BURGER ] ðð sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar \nhttps://t.co/WRfP9mMPc9\n========"
96,2109882074153058367,"SHOPEE FOOD Promo A&amp;W [ AYAM. &amp; BURGER ] ð sekarang ada di ShopeeFood Pesan Sekarang, langsung diantar â¨\nhttps://t.co/HlOl9sakqI\n======={"
97,2109879805944738017,"SHOPEE FOOD MOON CHICKEN (Hangry Fried Chicken) AYAM GORENG KOREA [ BUKA 24 JAM] ð¥ Pesan sekarang di ShopeeFood, langsung diantar\nhttps://t.co/s1d8vTAYbA\n======="
98,2109873902197616885,"SHOPEE FOOD Promo McDonald's ððð¦ [ BUKA 24 JAM ] Pesan di ShopeeFood Sekarang, langsung diantar â¨\nhttps://t.co/iRlFzRtqEc\n-------------"
99,2109872156817633606,"SHOPEE FOOD Promo KFC ðð Pesan di ShopeeFood sekarang, langsung diantar \nhttps://t.co/LmGuupRKzp\n======="
101,2109870814451663355,SHOPEE LIVE LEBIH CANTIK &amp; HEMAT DI LIVE XTRA. Pasti DISKON 20% s/d 50 RB Untuk Semua Produk Fashion Beauty. KLAIM Vouchernya di sini ð\nhttps://t.co/l2BoZ9N3Ee\n----------
102,2109870326415052962,Flash Sale Sopi\nð 13 Okt\nâ° 12:00\n\nRp999 (bs byk)\nJoyko Permanent Marker Spidol Permanen Round Tip Free Refill \nhttps://t.co/stl9LQcYNv\nVar: Blue\nStok: 200\n\nRp11.999\nPanlandwoo - Cincin Set Rhodium Peach Adjustable \nhttps://t.co/G82wvSvw2w\nVar: All\nStok: 36\n\nRp4.000\nDry Hand Foam Sanitizer 85ml - NORVUS \nhttps://t.co/NsnDSDgdGe\nStok: 50
103,2109869108963766361,"Harga Paling Worth It Saat ini ð¥\nEksklusif! POCO F9 Pro Diskon 2,5JT\nCuma di Shopee! Serbu POCO F9 Pro terbaru pakai Potongan 2,5JT. Cek\nhttps://t.co/lSAIYbMGqH\n-----------"
104,2109868784714674528,"SHOPEE FOOD Promo MIE GACOAN ð sekarang ada di ShopeeFood Pesan Sekarang, langsung diantar â¨\nhttps://t.co/DL4OCXmX8g\n-----------"
105,2109868461791007226,Flash Sale Pulsa &amp; Produk Digital SERBA Rp 1â¡\nâ°ï¸ 12:00 WIB\n\nhttps://t.co/JCIEX0kwcO https://t.co/xhZJBwlpvW
106,2109866107226235253,Flash Sale Pulsa &amp; Paket Data Mulai Rp1\nâ° 12:00 WIB\n\nCek selengkapnya disini\nSelengkapnya\nhttps://t.co/swvIQ1EeGa https://t.co/4BhEtPTbpT
107,2109865416453763182,Flash Sale Skin1004 Rp10.000\nâ°12.00 WIB\n\nSKIN1004 Madagascar Centella Tone Brightening Capsule Cream 75ml\nhttps://t.co/24FnstBFM4\n\nSKIN1004 Madagascar Centella Hyalu-Cica Water-Fit Sun Serum SPF50 PA++++\nhttps://t.co/fclpUUiNl3 https://t.co/uf2MeFIT1C
108,2109865374045122887,"Flash Sale\nâ° 12:00 WIB\n\nRp10.000\nFLASH SALE [N 1/27] JILL SKINCARE Bakuchiol Calendula Night Gel 10gr |\nStok: 5 Pcs\nhttps://t.co/vFRDUFeQQC\n\nRp10.000\nFLASH SALE [N 12/26] JILL SKINCARE Arbutin Glow Night Gel | Pelembap\nStok: 5 Pcs\nhttps://t.co/MhTqWINPGZ\n\nRp10.000\nSKIN1004 Madagascar Centella Tone Brightening Capsule Cream 75ml\nStok: 5 Pcs\nhttps://t.co/MVkrAekVb1\n\nRp10.000\nSKIN1004 Madagascar Centella Hyalu-Cica Water-Fit Sun Serum SPF50 PA++++\n50ml\nStok: 5 Pcs\nhttps://t.co/DxZqEVK7QU\n\nRp10.000\nHONYAN Tas Wanita Minor Defect Sale\nDompet panjang, dompet panjang3\nStok: 30 Pcs\nhttps://t.co/VqwV96xpqy\n\nRp10.000\nSevenDays Body Mist Special Edition Cinnamoroll, Hello Kitty, Kuromi, My Melody |\n7DBM CN PROMO, 7DBM KT PROMO, 7DBM KU PROMO\nStok: 72 Pcs\nhttps://t.co/EyR9b3NXpb\n\nRp10.000\nKartu Perdana XL PRIORITAS 60K 25GB/bln\n1 Bulan\nStok: 5 Pcs\nhttps://t.co/DXtuu8bP72\n\nRp10.000\neSIM XL PRIORITAS 60K 25GB/bln\n1 Bulan\nStok: 5 Pcs\nhttps://t.co/BKUivCxQIs\n\nRp10.000\nFinally Found You! Ocean Blue Pea Dual-Phase Essence Mist 100ml\n1PCS Face Mist 100mL, Travel Size 50mL\nStok: 10 Pcs\nhttps://t.co/XoVkt0DXqC\n\nRp10.000\nFinally Found You! ProtecTEA+ AI Smart Odor Control Antiperspirant Deodorant | Deodoran\n2pack Deodorant, 3pack Deodorant, Single Deodorant\nStok: 15 Pcs\nhttps://t.co/Z5D54PaDlZ"
109,2109864367093371112,"Flash Sale\nâ° 12:00 WIB\n\nRp1.000\nBASIKE Penyedot Debu Nirkabel Vacuum Cleaner Tanpa Kabel 30000PA 120W Daya Hisap\nStok: 1 Pcs\nhttps://t.co/vSsLdIalsK\n\nRp1.000\nOPIOBAGS - Tas umroh besar Totebag Wanita Handbag Wanita Tas Kanvas Tote\nNO 32\nStok: 1 Pcs\nhttps://t.co/ZgHPZyHUtD\n\nRp1.000\nOPIOBAGS DOMPET HP SELEMPANG WANITA / DOMPET HP WANITA / DOMPET NYLON\nBLACK,BESAR\nStok: 1 Pcs\nhttps://t.co/vSsLdIalsK\n\nRp1.100\nBETA TOOLS Alas Standar Motor Jagrak Karpet Motor Polos Kualitas Baik Tebal\nStok: 10 Pcs\nhttps://t.co/aT5oOKF8ff"
110,2109863403284242798,EMAS UBS 2 GRAM LOGAM MULIA 24K - BUNGA TANJUNG GOLD dengan harga Rp5.262.000. Dapatkan di Shopee sekarang! ð\nhttps://t.co/bcXAe4J8UD\n====
111,2109843503346028999,"SHOPEE FOOD Promo POINT COFFEE âð¥¤ðµ Pesan sekarang di ShopeeFood, langsung diantar\nhttps://t.co/RuXXEm3rg3\n---------------"
112,2109843262827872381,"SHOPEE FOOD SeIndonesia (Sei Sapi Dan Ayam) ð¥© Pesan sekarang di ShopeeFood, langsung diantar â¨\nhttps://t.co/Lo4lSU3a3f\n========"
113,2109843241873158296,aku nak bikin flash sale buat joki archon quest oke g yhh ð¤ð¤

In [67]:

label_kontekstual_3 = {
    "2109886014864974217": "tidak_relevan",
    "2109885627802030441": "tidak_relevan",
    "2109882272426205430": "tidak_relevan",
    "2109882074153058367": "tidak_relevan",
    "2109879805944738017": "tidak_relevan",
    "2109873902197616885": "tidak_relevan",
    "2109872156817633606": "tidak_relevan",
    "2109870814451663355": "perlu_konteks",
    "2109870326415052962": "tidak_relevan",
    "2109869108963766361": "perlu_konteks",
    "2109868784714674528": "tidak_relevan",
    "2109868461791007226": "tidak_relevan",
    "2109866107226235253": "tidak_relevan",
    "2109865416453763182": "tidak_relevan",
    "2109865374045122887": "tidak_relevan",
    "2109864367093371112": "tidak_relevan",
    "2109863403284242798": "perlu_konteks",
    "2109843503346028999": "tidak_relevan",
    "2109843262827872381": "tidak_relevan",
    "2109843241873158296": "tidak_relevan"
}

for tweet_id, label in label_kontekstual_3.items():
    df_cleaning.loc[
        df_cleaning["id"].astype(str) == tweet_id,
        "relevansi_manual"
    ] = label

print(df_cleaning["relevansi_manual"].value_counts(dropna=False))

relevansi_manual
belum_diperiksa        127
tidak_relevan           51
relevan_kontekstual     20
relevan_langsung        19
perlu_konteks           17
Name: count, dtype: int64

In [68]:
display(
    df_kontekstual[["id", "original_text"]].iloc[60:80]
)

,id,original_text
115,2109837772186059166,"SHOPEE FOOD Promo AYAM GEPREK by Hangry ð sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar ðµ\nhttps://t.co/B30tXV16jg\n----------"
116,2109830219834294764,Promo XTRA Diperpanjang. Promo Flash Sale Segera Berakhir Miniso x Harry Potter Preppy Style Crossbody Bag Tas Selempang Kasual Tas Bahu Tahan Air 23x7x17 - Ravenclaw Rp159.900. https://t.co/rlz9twXml2
117,2109828983424729288,Promo XTRA Diperpanjang. Promo Flash Sale Segera Berakhir [Cek Deskripsi] Cuci Gudang MINISO x Sanrio Cinnamoroll Strawberry Cosmetic Bag Make up Pouch Tas Kosmetik Besar Dompet Bernoda* Rp24.900.\nhttps://t.co/Sfi1jhupeY
118,2109828615118680223,Promo XTRA Diperpanjang. Promo Flash Sale Segera Berakhir MINISO x Hello Kitty Stitch Bound Book Set Buku Tulis Set (28pages) (2pcs) Rp49.900. https://t.co/3Bc0N3qyrv
119,2109828459941994561,Promo XTRA Diperpanjang \nPromo Flash Sale Segera Berakhir \nMiniso X Crayon Shinchan Lunch Box Bento Box Kotak Bekal Makan Siang Shinchan 650mL Cek Deskripsi* Rp59.900\nhttps://t.co/ShUPH6BTik
120,2109828343814303898,Promo XTRA Diperpanjang\nPromo Flash Sale Segera Berakhir Miniso x Zanmang Loopy Massaging Hair Brush Sisir Cek Deskripsi* Rp52.900\nhttps://t.co/OYtagknmWz
121,2109827461886464095,"@wohyuI aih masih lama ya yul ini, belum resmi ya, tapi doain biar gua bisa kunci gelar secepatnya. ð nah itu anjir yang gak gua jago, jempol gua kalah cepet sama mba dan mas yang udah biasa war flash sale. ;("
122,2109819362555404455,Promo flash sale tutup 2 jam lagi\n\nhttps://t.co/5eoSjMIqRL
123,2109815179114696878,"Halo kakak, bagi yg butuh carousell atau feed instagram yang lagi trendy, kita lgi ada flash sale bundling 25 design feed hanya 10kâ¨ï¸ #zonauang #jasaedit #carousel #trend #beautifulpicture https://t.co/M8gESYcqHW"
124,2110114100755992969,"ðï¸ 14 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior https://t.co/fB5UjuTid2"
125,2110105796902273156,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/5VIwzJOXoR
126,2110102056979849529,Open jastip trs sampe ga sadar voucher gratis ongkir habis ð­
127,2110098247138037949,"ðï¸ 14 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwwHm8\nhttps://t.co/B7nYSwwHm8\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior https://t.co/cMWO1jER2x"
128,2110090696032239935,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/wbghl0D2BA
129,2110083901683282265,"ðï¸ 14 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior https://t.co/BcRFZbEnQE"
130,2110075597301096696,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/Mj9qZbbTqp
131,2110068048749281440,"ðï¸ 14 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior https://t.co/fKRvAMOVF0"
132,2110066650599108998,keuntungan lainnya yang kamu dapetin:\n1.Voucher Gratis Ongkir 100X\n2.Diskon 50% 15RB setiap tanggal 15 \n3.Diskon 20% s/d 10RB\n4.Diskon 20% s/d 4RB\n5.Indomaret Point Rp1\n6.Roti'O Rp1
133,2110060749083353459,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/RXpLJHU2fP
134,2110056389074903246,"promo NEMU keluar, maskotnya langsung joget duluan ðºð\n\ngratis ongkir s/d Rp20rb + diskon produk s/d 67%. download NEMU, link di bio\n\n#nemu #belanja #online https://t.co/HMY2SfoEOn"

In [70]:
label_kontekstual_4 = {
    "2109837772186059166": "tidak_relevan",
    "2109830219834294764": "tidak_relevan",
    "2109828983424729288": "tidak_relevan",
    "2109828615118680223": "tidak_relevan",
    "2109828459941994561": "tidak_relevan",
    "2109828343814303898": "tidak_relevan",
    "2109827461886464095": "perlu_konteks",
    "2109819362555404455": "perlu_konteks",
    "2109815179114696878": "tidak_relevan",
    "2110114100755992969": "tidak_relevan",
    "2110105796902273156": "tidak_relevan",
    "2110102056979849529": "perlu_konteks",
    "2110098247138037949": "tidak_relevan",
    "2110090696032239935": "tidak_relevan",
    "2110083901683282265": "tidak_relevan",
    "2110075597301096696": "tidak_relevan",
    "2110068048749281440": "tidak_relevan",
    "2110066650599108998": "perlu_konteks",
    "2110060749083353459": "tidak_relevan",
    "2110056389074903246": "tidak_relevan"
}

for tweet_id, label in label_kontekstual_4.items():
    df_cleaning.loc[
        df_cleaning["id"].astype(str) == tweet_id,
        "relevansi_manual"
    ] = label

print(df_cleaning["relevansi_manual"].value_counts(dropna=False))

relevansi_manual
belum_diperiksa        107
tidak_relevan           67
perlu_konteks           21
relevan_kontekstual     20
relevan_langsung        19
Name: count, dtype: int64

In [71]:
display(
    df_kontekstual[["id", "original_text"]].iloc[80:100]
)

,id,original_text
135,2110052954514551221,"ðï¸ 14 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior https://t.co/A3J2uXvzkz"
136,2110047287988965485,Misi Balik Nonton â¨\nâ° 00:00 WIB\n\ncukup nonton shopee video atau shopee live selama 3 menit dan dapetin Diskon Voucher 50% s/d 100RB ðð¼\n\ncek selengkapnya di sini:\nhttps://t.co/vVkBaYTupK https://t.co/VKQbU0B7Pj
137,2110045397628370994,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwwHm8\nhttps://t.co/B7nYSwwHm8\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/vVmLG41SyB"
138,2110038099980108117,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/h0i5ij3bxt
139,2110030434059092112,@tachimchuu Ibarat pake voucher gratis ongkir ya bu
140,2110030299589718172,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/36bmBUBHdM"
141,2110023504108404885,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/qKxvRNAawv
142,2110015450574897592,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/FJmNTZ1wwg"
143,2110011479525151036,DAU!\nEdisi Teman Malam UTS by Kopi Ukut.\n\nSpecial Offers!!\nOnly 18k\n\nOpen: 17.00 - 02.00\n\n(+) GRATIS ONGKIR ALL AROUND NANGOR ya gengs. https://t.co/aEPcOcycLn
144,2110010360694726775,@pwark_justin Nah itu balik aja dah yok manualð« ð­ kalo gini mending ku kasih gratis ongkir manual udah sama asuransi jabodetabek mah dri pada kayak giniii
145,2110008153022615646,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU0HZR\nhttps://t.co/KpFtHU0HZR\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/wj7N8ho57h
147,2110005908847923612,KODE BESOK SPESIAL RABU â¼ï¸\nâ° 00:00 WIB\n\nâ¢ *Diskon 50% MAX 10RB Minbel 20RB*\nKode: *SERBURABU14OCT*\n\nInput kodenya disini:\nhttps://t.co/NE8Sxk3WAk https://t.co/mNVLSrcoZw
148,2110004109470527552,"@mbanenoy Ternyata biaya gratis ongkir xtra lumayan ya kena 8%. Platform 8.15%, 3% po, 0,5% pajak"
149,2110000102974906494,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/Q8AP2vXdCR"
150,2109996756159312092,@mbanenoy eh biaya gratis ongkir xtra penjual yg bayar? biaya platformnya gede banget helpð­ð­ð­
151,2109992801702465554,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/ErGbzE9Zzu
152,2109989202352042421,"@ciloqciliq diskon + gratis ongkir emg menggoda bgt sih ð­ tp penasaran, diskonnya berlaku buat semua menu atau ada ketentuan minimumnya yaa?"
153,2109985003656388802,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwwHm8\nhttps://t.co/B7nYSwwHm8\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/oS986gbv2R"
154,2109984482702836063,@rightnaows Sayangnya gopud ku busyuk ð­ð­ð­ gak ada promo disc apalagi gratis ongkir ð­ https://t.co/WxNBSdY2TI
155,2109980081888063866,"Mau makan GRATIS s.d. 15RB + gratis ongkir semua resto? Nah, promo ini cocok untuk kamu ð§¡\n\nKhusus untuk pengguna baru, order ShopeeFood di aplikasi ShopeePay! #ShopeePay #AplikasiShopeePay #DompetSerbaBisa https://t.co/WLJwqYBVbY"

In [72]:
label_kontekstual_5 = {
    "2110015450574897592": "tidak_relevan",
    "2110011479525151036": "tidak_relevan",
    "2110010360694726775": "perlu_konteks",
    "2110008153022615646": "tidak_relevan",
    "2110005908847923612": "tidak_relevan",
    "2110004109470527552": "perlu_konteks",
    "2110000102974906494": "tidak_relevan",
    "2109996756159312092": "perlu_konteks",
    "2109992801702465554": "tidak_relevan",
    "2109989202352042421": "perlu_konteks",
    "2109985003656388802": "tidak_relevan",
    "2109984482702836063": "perlu_konteks",
    "2109980081888063866": "tidak_relevan"
}

for tweet_id, label in label_kontekstual_5.items():
    df_cleaning.loc[
        df_cleaning["id"].astype(str) == tweet_id,
        "relevansi_manual"
    ] = label

print(df_cleaning["relevansi_manual"].value_counts(dropna=False))

relevansi_manual
belum_diperiksa        94
tidak_relevan          75
perlu_konteks          26
relevan_kontekstual    20
relevan_langsung       19
Name: count, dtype: int64

In [73]:
display(
    df_kontekstual[["id", "original_text"]].iloc[100:120]
)

,id,original_text
156,2109978623935402404,AKU JUAL RUGI BAJU RENANG OPELON YA WARGAâ\n\nHARGA BELI 400AN\nAKU JUAL 150RB AJA YAPP SOALNYA JARANG DIPAKE\n\nbisa oyen + gratis ongkir yaa â\nhttps://t.co/O8irSID2UZ\n\n#notiputipu #preloved #bajurenang #opelon #thrifting https://t.co/e1Dz6IvlOX
157,2109978457061101751,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/2u1tCrU1uD
158,2109974646489776636,@intanorii ngopi udh jdkebutuhan pokok ya bund ð­ untung klo ada diskon sm gratis ongkir jadi ga terlalu mikir pas mau checkout wkwk
159,2109974536754221553,"SIAPAPUN WARGA BANTU LARISIN PRELOVED AKU DONGG, AKU JUAL RUGI BNGETT. HARGA ASLI KISARAN 500RB, AKU JUAL UNDER 200RB AJA ð¥º\n\nbisa oyen yaa plus gratis ongkirâ https://t.co/LwsVGe1NKQ"
160,2109973280891535515,"@__altheist no no, aku ga ok :'( terima kasih kawan karena telah bertanya â£ï¸ semoga selalu gratis ongkir shopee mu nak ð«"
161,2109970643542241398,"Nakes homecare cek lab langsung ke rumah sat set, konsul rutin di Halodoc.\n\nBaju sempit jd longgar! Checkout pake voucher ONGKIRGLP dpt benefit gratis ongkir homecare ya!"
162,2109969905697099887,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwwHm8\nhttps://t.co/B7nYSwwHm8\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/MWRPW4ytyC"
163,2109966568788783137,"Badan jauh lbh enteng &amp; berenergi pas ngantor.\n\nBuat warga Tangerang, daftar pake kupon ONGKIRGLP dpt gratis ongkir kunjungan homecare ya!"
164,2109962602877255751,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/HIRNWc5ewE
165,2109960949872652777,"tutor gratis ongkir shopi plis, AP MKSD BARANGNYA 1000 GA NYAMPE, ONGKIRNYA 25"
166,2109957261716328633,Cek Kabel Data Samsung C to C Super Fast Charging 25W Original Cable USB Type C to Type C 3A. Dapatkan di Shopee sekarang!\n\nð Shopee COD &amp; Gratis Ongkir \nhttps://t.co/qwgkVgkpBt
167,2109957178010612140,Cek Charger SAMSUNG Type C Fast Charging 45 Watt Kabel C to C Original Samsung 100%. Dapatkan di Shopee sekarang!\n\nð Shopee COD &amp; Gratis Ongkir \nhttps://t.co/39jfvyjxd3
168,2109957064407867467,Cek Kabel Data Xiaomi Type C Turbo Charge 6 Ampere Original 100% Fast Charging 67W berkualitas cepat dan awet. Dapatkan di Shopee sekarang!\n\nð Shopee COD &amp; Gratis Ongkir \nhttps://t.co/Gqvr6UFaJP
169,2109956951472054610,Cek Kabel Data Xiaomi Type C Turbo Charge 6 Ampere Original 100% Fast Charging 67W berkualitas cepat dan awet. Dapatkan di Shopee sekarang!\n\nð Shopee COD & Gratis Ongkir \nhttps://t.co/cOByxGjQdc\n\nð Produk Terlaris Shopee\nhttps://t.co/MFJmOLHkFD\n\nð Ikuti Saluran WhatsAap\nhttps://t.co/lmA3VrXUEJ
171,2109954801274655067,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/bdEwoy9K8Y"
172,2109949599058403568,"@cigarettexecs OKAYY, kayanya aku cobaa dulu deh 100p ntar kalo gabisa set 500, terus kamu daftar yang gratis ongkir extra dari duluu kah by, ntar masuk ke email atau gmn deh huhu soalnya lum ada tanda"" uda bisa gratong(?)"
173,2109947754944291051,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU0HZR\nhttps://t.co/KpFtHU0HZR\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/x6z5NsXRXU
174,2109943865709142382,"@hdupsdiih @miawgumo sebenernya gratong ttep dari shopee kakk cmiiw, tapi seller ada biaya adm krn daftar gratis ongkir gituuu (bbrp persen tergantung kategori produk) \n\njadi walaupun ongkir pembeli misal cuman 20k, tapi krn persenan adm tadi dikali harga barang jadi yaa WKWKWKWK"
175,2109939825180922083,"wts want to sell novel bahasa indonesia\nðbogor, ðsplitpay via sopi yaaa, bisa gratis ongkir\n\nâ new sealed\nsihir perempuan - intan paramaditha 50k\nthe devotion of suspect x (kesetiaan mr x) - keigo higashino 65k https://t.co/vehKwd3RWn"
176,2109939703214665760,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/6a4cSNAJZ0"

In [74]:

label_kontekstual_6 = {
    "2109978623935402404": "tidak_relevan",
    "2109978457061101751": "tidak_relevan",
    "2109974646489776636": "perlu_konteks",
    "2109974536754221553": "tidak_relevan",
    "2109973280891535515": "perlu_konteks",
    "2109970643542241398": "tidak_relevan",
    "2109969905697099887": "tidak_relevan",
    "2109966568788783137": "tidak_relevan",
    "2109962602877255751": "tidak_relevan",
    "2109960949872652777": "perlu_konteks",
    "2109957261716328633": "tidak_relevan",
    "2109957178010612140": "tidak_relevan",
    "2109957064407867467": "tidak_relevan",
    "2109956951472054610": "tidak_relevan",
    "2109954801274655067": "tidak_relevan",
    "2109949599058403568": "perlu_konteks",
    "2109947754944291051": "tidak_relevan",
    "2109943865709142382": "perlu_konteks",
    "2109939825180922083": "tidak_relevan",
    "2109939703214665760": "tidak_relevan"
}

for tweet_id, label in label_kontekstual_6.items():
    df_cleaning.loc[
        df_cleaning["id"].astype(str) == tweet_id,
        "relevansi_manual"
    ] = label

print(df_cleaning["relevansi_manual"].value_counts(dropna=False))

relevansi_manual
tidak_relevan          90
belum_diperiksa        74
perlu_konteks          31
relevan_kontekstual    20
relevan_langsung       19
Name: count, dtype: int64

In [75]:
print("Total data:", len(df_cleaning))

print("\nStatus label relevansi manual:")
print(df_cleaning["relevansi_manual"].value_counts(dropna=False))

print("\nTweet yang belum diberi label:")
display(
    df_cleaning.loc[
        df_cleaning["relevansi_manual"].isna(),
        ["id", "original_text", "kategori_relevansi_awal"]
    ].head(10)
)

Total data: 234

Status label relevansi manual:
relevansi_manual
tidak_relevan          90
belum_diperiksa        74
perlu_konteks          31
relevan_kontekstual    20
relevan_langsung       19
Name: count, dtype: int64

Tweet yang belum diberi label:

Empty DataFrame
Columns: [id, original_text, kategori_relevansi_awal]
Index: []

In [76]:
import re

mask = df_cleaning["relevansi_manual"].eq("belum_diperiksa")
teks = df_cleaning["original_text"].fillna("")

# Indikasi kuat: secara eksplisit menyebut 10.10 atau tanggal kembar
pola_langsung = (
    r"10\s*[./-]\s*10|10\.10|"
    r"tanggal\s+kembar|double\s*date|"
    r"big\s*sale\s*10"
)

# Konteks promo e-commerce
pola_promo = (
    r"shopee|tokopedia|lazada|blibli|"
    r"voucher|kupon|diskon|discount|promo|promosi|"
    r"flash\s*sale|flashsale|gratis\s+ongkir|"
    r"kode\s*promo|marketplace|belanja\s+online"
)

langsung = teks.str.contains(
    pola_langsung, case=False, regex=True
)
promo = teks.str.contains(
    pola_promo, case=False, regex=True
)

# Hanya memproses baris yang belum diperiksa
df_cleaning.loc[mask & langsung, "relevansi_manual"] = "perlu_konteks"
df_cleaning.loc[mask & ~langsung & promo, "relevansi_manual"] = "perlu_konteks"
df_cleaning.loc[mask & ~langsung & ~promo, "relevansi_manual"] = "tidak_relevan"

print(df_cleaning["relevansi_manual"].value_counts())

relevansi_manual
tidak_relevan          103
perlu_konteks           92
relevan_kontekstual     20
relevan_langsung        19
Name: count, dtype: int64

In [77]:
display(
    df_cleaning[
        df_cleaning["relevansi_manual"] == "perlu_konteks"
    ][["id", "original_text", "relevansi_manual"]]
)

,id,original_text,relevansi_manual
23,2109825857250533387,@ilymoontae jamayyy pas tanggal kembar ðð baterai 71% ak pakai seharian di mobil masi 54% malah udah jatuh dari kasur ke lantai tp masi bernyawa https://t.co/hRlYydkfbV,perlu_konteks
24,2109812462103281734,@ayrzz_ biasanya pas tanggal kembar aja kak,perlu_konteks
53,2110039792805372383,@depelemon di shopee flash sale banyank tuhh yg under 50rb,perlu_konteks
55,2110019724046414018,"+ gabung sama app prem, harganya jadi lebih mahal... Pdhal klo mumpung flash sale yang dibutuhin ya cuma kuotanya ð",perlu_konteks
58,2110010082826358847,"guysss... yg suka da hong pao momoyo aku kasih tau caranya biar bisa dpt harga murah di shopeefood, bahkan lebih murah dr voc tiktok nihh...\npertama pilih yg flash sale double da hong pao di sini https://t.co/4SfGRY3J6u https://t.co/NQ82pe0Ctj",perlu_konteks
...,...,...,...
229,2109946434489614617,Jangan lupa buat klaim voucher belanja dari shopee ini guyss!\n\nhttps://t.co/eHByNblkee,perlu_konteks
230,2109913429389754847,https://t.co/oODc5uugwW\n\naku lgi ada voucher belanja nih gaes..,perlu_konteks
231,2109904469421084905,"Time to start the mission: KWANG STAR MISSION. Get ready to bring home your dream wishlist with K Natural White!â£\nâ£\nBelanja K Natural White semua varian minimal Rp30.000 aja, dapatkan 1 STAR. Kumpulin STAR sebanyak mungkin dan tukarkan dengan hadiah impian.â£\nâ£\nAda hadiah 18pcs Marhen J Sabrina Bag, 15pcs logam mulia 0,5 gram, 15pcs FUJIFILM Instax Mini, 500pcs voucher belanja Rp 100.000 & 500pcs voucher belanja Rp 50.000â£\nâ£\nPeriode: 16 Juli - 15 Oktober 2026â£",perlu_konteks
232,2109865460594585635,"Mestinya emiten2 ini daripada habisin duit buat merch RUPS buat para shareholder oportunit, mending terapin cara yg sama kayak di jepang. Hold sahamnya >1 tahun bisa dapet gift.\n\nMisal cpin dapet 1 parcel nugget, bca dapet flazz edisi khusus, map dapet voucher belanja, ptba dapet batu bara 15 kg dikirim k rumah.\n\nkan enak.",perlu_konteks
233,2109841666651594958,Dapatkan voucher belanja hingga 40% dari nilai frame di Optik Melawai. Diskon hingga 20% utk pembelian kaca mata hitam. Hingga 14 Okt. https://t.co/BN2tqmOBCH,perlu_konteks

In [78]:
# Kandidat tweet yang menyebut tanggal kembar atau 10.10 secara eksplisit
pola_event = (
    r"10\s*[./-]\s*10|"
    r"10\.10|"
    r"tanggal\s+kembar|"
    r"double\s*date|"
    r"big\s*sale"
)

df_cleaning["teks_untuk_filter"] = (
    df_cleaning["original_text"].fillna("")
)

df_cleaning["kandidat_event_10_10"] = (
    df_cleaning["teks_untuk_filter"]
    .str.contains(pola_event, case=False, regex=True)
)

df_kandidat = df_cleaning[
    df_cleaning["kandidat_event_10_10"]
].copy()

print("Total data awal:", len(df_cleaning))
print("Kandidat yang menyebut event:", len(df_kandidat))

display(
    df_kandidat[
        ["id", "original_text", "relevansi_manual"]
    ].head(20)
)

Total data awal: 234
Kandidat yang menyebut event: 43

,id,original_text,relevansi_manual
0,2110049779162153142,"@afrkml ak kemarin beli 3 hp di shopee aman aman aja. tapi lihat postingan kaya gini harus hati2 juga sih\n\nsebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik",relevan_kontekstual
1,2110037673167737100,close yaa! timaacii yang sudah ikutan dan meramaikan :3 sampai bertemu di tanggal kembar selanjutnya iaa ð§ð»ââï¸,relevan_kontekstual
2,2110037344552186209,btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss,tidak_relevan
3,2110010539950899311,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja",relevan_kontekstual
4,2110004575105388837,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk Jisulife lagi ð­",relevan_kontekstual
5,2110000127884828879,"Syongsok menikah di tanggal kembar, anaknya kembar juga gak?",tidak_relevan
6,2109988569775591730,@nattwtij Masama sayangkuuu ð\nKalau beli elektronik begitu saranku better beli di tanggal kembar ð potongan nya sering gila-gilaan,relevan_kontekstual
7,2109968183469957508,"Ges mau nanyað\nShopee kalian kalau lagi ga event tanggal kembar atau tanggal 25, tetep bisa freeong?\n\n((Nanya dulu, kali aja tiba2 aku mau sale lagi))",relevan_kontekstual
8,2109968091128148197,"Tes kekencangan si Jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. Tapi jisulife 5 cuma ada 3 tingkatan angin \n\nBeli pas tanggal kembar oke banget diskon nya ð¥° https://t.co/5E17pVy4YR",relevan_kontekstual
9,2109966398118408698,@riorkha Diskon tanggal kembar oren dong 9.9,relevan_kontekstual
10,2109950795177402757,"@Weist9953 aku ð­âï¸ tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong gak sih?",relevan_kontekstual
11,2109938277319069736,"ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?",relevan_kontekstual
12,2109928760682414103,@usedtob3me Ga ada Kak\nBeli tanggal kembar aja\nAku pake sampe ke bokong dan beneran bagus ð­ð­ð­,relevan_kontekstual
13,2109925742343839766,"siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampe 7 turunan",relevan_kontekstual
14,2109922315643580669,"@LambeSahamjja emang melemah njir, buktinya event tanggal kembar sepi",relevan_kontekstual
15,2109905523567202516,@snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\n\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD,relevan_kontekstual
16,2109903036479103119,"Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKeranjang belanjaan tanggal kembar besok udah penuh, tapi saldo e-wallet masih kosong melompong? Top up e-wallet favoritmu di Orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!ðï¸ð https://t.co/VYdb3cw5Zn",relevan_kontekstual
17,2109899261253222833,@usedtob3me Cetaphil bisa murah kalau beli di Lazada (watsons)\nKalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar)\nLebih murah lagi ada hadalabo gokujyun (agak berbusa dikit),relevan_kontekstual
18,2109890173035335745,Help RT or repost tweet di bawah ini guyss ð¥º #zonauang\n\nAku ada optip open titip layout dalam rangka tanggal kembar 10.10 dengan harga spesial special price promo diskon 6k aja!!\n\nBisa sampai tanggal 17 Oktober yaaa ð,relevan_langsung
19,2109868003282341966,"Hidup tuh jangan terlalu serius, nanti cepat tua. Tapi kalau terlalu santai, takut miskin. Mau kerja capek, nggak kerja nggak punya duit. Mau hemat, banyak godaan. Mau kaya, rebahan mulu. Ya Allah, sebenarnya aku ini maunya hidup atau cuma mau menikmati promo tanggal kembar? ð­",relevan_kontekstual

In [79]:
# Bandingkan teks asli dan hasil text cleaning
display(
    df_cleaning[
        ["original_text", "clean_text"]
    ].sample(
        min(10, len(df_cleaning)),
        random_state=42
    )
)

,original_text,clean_text
69,"â½ SUPER SERU FLASH SALE! Kuota 50GB/28 hari cuma Rp100 ribu, udah termasuk langganan Vidio Gold, Prime Video, VISION+, dan WeTV!\n\nð 13-19 Oktober 2026\nð² MyTelkomsel, *363*35#, Outlet terdekat, atau klik https://t.co/wJ1baYFIHO\n\n#SIMPATITerbaikUntukmu #PastiSIMPATI https://t.co/Sn5eSKtriT",â1 2 super seru flash sale kuota 50gb/28 hari cuma rp100 ribu udah termasuk langganan vidio gold prime video vision dan wetv ð 13-19 oktober 2026 ð2 mytelkomsel 363 35 outlet terdekat atau klik simpatiterbaikuntukmu pastisimpati
206,"PromoâTomoro Coffee, ada diskon menu 40% + voucher diskon 30%! Cek iniðð»\nhttps://t.co/H9lyo48Zqf\n\nPromoâPilona Coffee, ada voucher diskon 22k + voucher gratis ongkir! Cek iniðð»\nhttps://t.co/ssN7WiZvLS\n\n#ShopeeFoodX #PromoMakanan #selasa #pagii",promoâtomoro coffee ada diskon menu 40% voucher diskon 30% cek iniðð promoâpilona coffee ada voucher diskon 22k voucher gratis ongkir cek iniðð shopeefoodx promomakanan selasa pagii
180,@savirgoelf KK MAKASIH BANYAK UDAH SELALU WOOMENð¥ºð¥ºð¥º smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di orenð¥ºð¥ºð¥ºâ¤ï¸ð«°ð»,kk makasih banyak udah selalu woomenð oð oð o smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di orenð oð oð oâ ï ð ð
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
127,"ðï¸ 14 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwwHm8\nhttps://t.co/B7nYSwwHm8\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior https://t.co/cMWO1jER2x",ðï 14 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto akun tertentu â1 4ï â1 4ï cek dan klaim di resto ini ð gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior
109,"Flash Sale\nâ° 12:00 WIB\n\nRp1.000\nBASIKE Penyedot Debu Nirkabel Vacuum Cleaner Tanpa Kabel 30000PA 120W Daya Hisap\nStok: 1 Pcs\nhttps://t.co/vSsLdIalsK\n\nRp1.000\nOPIOBAGS - Tas umroh besar Totebag Wanita Handbag Wanita Tas Kanvas Tote\nNO 32\nStok: 1 Pcs\nhttps://t.co/ZgHPZyHUtD\n\nRp1.000\nOPIOBAGS DOMPET HP SELEMPANG WANITA / DOMPET HP WANITA / DOMPET NYLON\nBLACK,BESAR\nStok: 1 Pcs\nhttps://t.co/vSsLdIalsK\n\nRp1.100\nBETA TOOLS Alas Standar Motor Jagrak Karpet Motor Polos Kualitas Baik Tebal\nStok: 10 Pcs\nhttps://t.co/aT5oOKF8ff",flash sale â 12 00 wib rp1.000 basike penyedot debu nirkabel vacuum cleaner tanpa kabel 30000pa 120w daya hisap stok 1 pcs rp1.000 opiobags - tas umroh besar totebag wanita handbag wanita tas kanvas tote no 32 stok 1 pcs rp1.000 opiobags dompet hp selempang wanita / dompet hp wanita / dompet nylon black besar stok 1 pcs rp1.100 beta tools alas standar motor jagrak karpet motor polos kualitas baik tebal stok 10 pcs
196,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/oydxCEVVUm,â1 4ï voucher shopeefood diskon 90% max 19rb gratis ongkir 9rb â klaim di resto sebelum habis ððð t. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir
93,"SHOPEE FOOD Promo HOKBEN ð± Lokasari sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar! \nhttps://t.co/GKaxrqOZlc\n=====",shopee food promo hokben ð lokasari sekarang ada di shopeefood pesan sekarang langsung diantar
213,halo gais~\nRu ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir &gt;&lt;\nyang mau bareng bisa dm atau chat ke WA Ru yaa â¨\n\n#warunganime #warunggame,halo gais ru ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir gt lt yang mau bareng bisa dm atau chat ke wa ru yaa â warunganime warunggame
15,@snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\n\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD,kan ngenes baru kemaren aja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo ini di superindo tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xddd

In [80]:
import re
import unicodedata
import pandas as pd

def clean_text_v2(text):
    if pd.isna(text):
        return ""

    text = unicodedata.normalize("NFKC", str(text)).lower()

    # Hapus URL dan email
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(
        r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b",
        " ",
        text
    )

    # Hapus mention, tetapi pertahankan hashtag sebagai kata
    text = re.sub(r"(?<!\w)@\w+", " ", text)
    text = re.sub(r"#(\w+)", r"\1", text)

    # Hapus karakter kontrol dan simbol emoji yang tersisa.
    # Huruf, angka, tanda baca, dan spasi tetap dipertahankan.
    hasil = []
    for ch in text:
        kategori = unicodedata.category(ch)
        if kategori[0] in ("L", "N", "P", "Z") or ch in "%":
            hasil.append(ch)
        else:
            hasil.append(" ")

    text = "".join(hasil)

    # Rapikan spasi
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_cleaning["clean_text_v2"] = (
    df_cleaning["original_text"].apply(clean_text_v2)
)

display(
    df_cleaning[
        ["original_text", "clean_text", "clean_text_v2"]
    ].sample(min(10, len(df_cleaning)), random_state=42)
)

,original_text,clean_text,clean_text_v2
69,"â½ SUPER SERU FLASH SALE! Kuota 50GB/28 hari cuma Rp100 ribu, udah termasuk langganan Vidio Gold, Prime Video, VISION+, dan WeTV!\n\nð 13-19 Oktober 2026\nð² MyTelkomsel, *363*35#, Outlet terdekat, atau klik https://t.co/wJ1baYFIHO\n\n#SIMPATITerbaikUntukmu #PastiSIMPATI https://t.co/Sn5eSKtriT",â1 2 super seru flash sale kuota 50gb/28 hari cuma rp100 ribu udah termasuk langganan vidio gold prime video vision dan wetv ð 13-19 oktober 2026 ð2 mytelkomsel 363 35 outlet terdekat atau klik simpatiterbaikuntukmu pastisimpati,"â 1 2 super seru flash sale! kuota 50gb/28 hari cuma rp100 ribu, udah termasuk langganan vidio gold, prime video, vision , dan wetv! ð 13-19 oktober 2026 ð 2 mytelkomsel, *363*35#, outlet terdekat, atau klik simpatiterbaikuntukmu pastisimpati"
206,"PromoâTomoro Coffee, ada diskon menu 40% + voucher diskon 30%! Cek iniðð»\nhttps://t.co/H9lyo48Zqf\n\nPromoâPilona Coffee, ada voucher diskon 22k + voucher gratis ongkir! Cek iniðð»\nhttps://t.co/ssN7WiZvLS\n\n#ShopeeFoodX #PromoMakanan #selasa #pagii",promoâtomoro coffee ada diskon menu 40% voucher diskon 30% cek iniðð promoâpilona coffee ada voucher diskon 22k voucher gratis ongkir cek iniðð shopeefoodx promomakanan selasa pagii,"promoâ tomoro coffee, ada diskon menu 40% voucher diskon 30%! cek inið ð » promoâ pilona coffee, ada voucher diskon 22k voucher gratis ongkir! cek inið ð » shopeefoodx promomakanan selasa pagii"
180,@savirgoelf KK MAKASIH BANYAK UDAH SELALU WOOMENð¥ºð¥ºð¥º smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di orenð¥ºð¥ºð¥ºâ¤ï¸ð«°ð»,kk makasih banyak udah selalu woomenð oð oð o smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di orenð oð oð oâ ï ð ð,kk makasih banyak udah selalu woomenð oð oð o smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di orenð oð oð oâ ï ð « ð »
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
127,"ðï¸ 14 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwwHm8\nhttps://t.co/B7nYSwwHm8\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior https://t.co/cMWO1jER2x",ðï 14 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto akun tertentu â1 4ï â1 4ï cek dan klaim di resto ini ð gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior,"ð ï 14 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu â 1 4ï â 1 4ï cek dan klaim di resto ini ð gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior"
109,"Flash Sale\nâ° 12:00 WIB\n\nRp1.000\nBASIKE Penyedot Debu Nirkabel Vacuum Cleaner Tanpa Kabel 30000PA 120W Daya Hisap\nStok: 1 Pcs\nhttps://t.co/vSsLdIalsK\n\nRp1.000\nOPIOBAGS - Tas umroh besar Totebag Wanita Handbag Wanita Tas Kanvas Tote\nNO 32\nStok: 1 Pcs\nhttps://t.co/ZgHPZyHUtD\n\nRp1.000\nOPIOBAGS DOMPET HP SELEMPANG WANITA / DOMPET HP WANITA / DOMPET NYLON\nBLACK,BESAR\nStok: 1 Pcs\nhttps://t.co/vSsLdIalsK\n\nRp1.100\nBETA TOOLS Alas Standar Motor Jagrak Karpet Motor Polos Kualitas Baik Tebal\nStok: 10 Pcs\nhttps://t.co/aT5oOKF8ff",flash sale â 12 00 wib rp1.000 basike penyedot debu nirkabel vacuum cleaner tanpa kabel 30000pa 120w daya hisap stok 1 pcs rp1.000 opiobags - tas umroh besar totebag wanita handbag wanita tas kanvas tote no 32 stok 1 pcs rp1.000 opiobags dompet hp selempang wanita / dompet hp wanita / dompet nylon black besar stok 1 pcs rp1.100 beta tools alas standar motor jagrak karpet motor polos kualitas baik tebal stok 10 pcs,"flash sale â 12:00 wib rp1.000 basike penyedot debu nirkabel vacuum cleaner tanpa kabel 30000pa 120w daya hisap stok: 1 pcs rp1.000 opiobags - tas umroh besar totebag wanita handbag wanita tas kanvas tote no 32 stok: 1 pcs rp1.000 opiobags dompet hp selempang wanita / dompet hp wanita / dompet nylon black,besar stok: 1 pcs rp1.100 beta tools alas standar motor jagrak karpet motor polos kualitas baik tebal stok: 10 pcs"
196,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/oydxCEVVUm,â1 4ï voucher shopeefood diskon 90% max 19rb gratis ongkir 9rb â klaim di resto sebelum habis ððð t. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir,â 1 4ï voucher shopeefood diskon 90% max 19rb gratis ongkir 9rb â klaim di resto sebelum habis ð ð ð t. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir
93,"SHOPEE FOOD Promo HOKBEN ð± Lokasari sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar! \nhttps://t.co/GKaxrqOZlc\n=====",shopee food promo hokben ð lokasari sekarang ada di shopeefood pesan sekarang langsung diantar,"shopee food promo hokben ð lokasari sekarang ada di shopeefood! pesan sekarang, langsung diantar!"
213,halo gais~\nRu ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir &gt;&lt;\nyang mau bareng bisa dm atau chat ke WA Ru yaa â¨\n\n#warunganime #warunggame,halo gais ru ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir gt lt yang mau bareng bisa dm atau chat ke wa ru yaa â warunganime warunggame,halo gais ru ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir &gt;&lt; yang mau bareng bisa dm atau chat ke wa ru yaa â warunganime warunggame
15,@snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\n\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD,kan ngenes baru kemaren aja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo ini di superindo tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xddd,kan ngenes baru kemaren aja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xddd

In [81]:
import re
import unicodedata
import pandas as pd
import html

def clean_text_v3(text):
    if pd.isna(text):
        return ""

    text = html.unescape(str(text))
    text = unicodedata.normalize("NFKC", text).lower()

    # Hapus URL dan email
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)
    text = re.sub(
        r"\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b",
        " ",
        text
    )

    # Hapus mention, pertahankan kata dari hashtag
    text = re.sub(r"(?<!\w)@\w+", " ", text)
    text = re.sub(r"#(\w+)", r"\1", text)

    # Hapus artefak encoding yang sering muncul pada emoji rusak.
    # Jangan menghapus huruf atau angka secara umum.
    text = re.sub(r"[âðï�]+", " ", text)

    # Pertahankan huruf, angka, spasi, dan tanda baca
    # yang berguna untuk teks promosi.
    hasil = []
    for ch in text:
        kategori = unicodedata.category(ch)
        if kategori[0] in ("L", "N", "P", "Z") or ch in "%":
            hasil.append(ch)
        else:
            hasil.append(" ")

    text = "".join(hasil)
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_cleaning["clean_text_v3"] = (
    df_cleaning["original_text"].apply(clean_text_v3)
)

display(
    df_cleaning[
        ["original_text", "clean_text_v2", "clean_text_v3"]
    ].sample(min(10, len(df_cleaning)), random_state=42)
)

,original_text,clean_text_v2,clean_text_v3
69,"â½ SUPER SERU FLASH SALE! Kuota 50GB/28 hari cuma Rp100 ribu, udah termasuk langganan Vidio Gold, Prime Video, VISION+, dan WeTV!\n\nð 13-19 Oktober 2026\nð² MyTelkomsel, *363*35#, Outlet terdekat, atau klik https://t.co/wJ1baYFIHO\n\n#SIMPATITerbaikUntukmu #PastiSIMPATI https://t.co/Sn5eSKtriT","â 1 2 super seru flash sale! kuota 50gb/28 hari cuma rp100 ribu, udah termasuk langganan vidio gold, prime video, vision , dan wetv! ð 13-19 oktober 2026 ð 2 mytelkomsel, *363*35#, outlet terdekat, atau klik simpatiterbaikuntukmu pastisimpati","1 2 super seru flash sale! kuota 50gb/28 hari cuma rp100 ribu, udah termasuk langganan vidio gold, prime video, vision , dan wetv! 13-19 oktober 2026 2 mytelkomsel, *363*35#, outlet terdekat, atau klik simpatiterbaikuntukmu pastisimpati"
206,"PromoâTomoro Coffee, ada diskon menu 40% + voucher diskon 30%! Cek iniðð»\nhttps://t.co/H9lyo48Zqf\n\nPromoâPilona Coffee, ada voucher diskon 22k + voucher gratis ongkir! Cek iniðð»\nhttps://t.co/ssN7WiZvLS\n\n#ShopeeFoodX #PromoMakanan #selasa #pagii","promoâ tomoro coffee, ada diskon menu 40% voucher diskon 30%! cek inið ð » promoâ pilona coffee, ada voucher diskon 22k voucher gratis ongkir! cek inið ð » shopeefoodx promomakanan selasa pagii","promo tomoro coffee, ada diskon menu 40% voucher diskon 30%! cek ini » promo pilona coffee, ada voucher diskon 22k voucher gratis ongkir! cek ini » shopeefoodx promomakanan selasa pagii"
180,@savirgoelf KK MAKASIH BANYAK UDAH SELALU WOOMENð¥ºð¥ºð¥º smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di orenð¥ºð¥ºð¥ºâ¤ï¸ð«°ð»,kk makasih banyak udah selalu woomenð oð oð o smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di orenð oð oð oâ ï ð « ð »,kk makasih banyak udah selalu woomen o o o smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di oren o o o « »
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
127,"ðï¸ 14 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwwHm8\nhttps://t.co/B7nYSwwHm8\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior https://t.co/cMWO1jER2x","ð ï 14 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu â 1 4ï â 1 4ï cek dan klaim di resto ini ð gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior","14 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior"
109,"Flash Sale\nâ° 12:00 WIB\n\nRp1.000\nBASIKE Penyedot Debu Nirkabel Vacuum Cleaner Tanpa Kabel 30000PA 120W Daya Hisap\nStok: 1 Pcs\nhttps://t.co/vSsLdIalsK\n\nRp1.000\nOPIOBAGS - Tas umroh besar Totebag Wanita Handbag Wanita Tas Kanvas Tote\nNO 32\nStok: 1 Pcs\nhttps://t.co/ZgHPZyHUtD\n\nRp1.000\nOPIOBAGS DOMPET HP SELEMPANG WANITA / DOMPET HP WANITA / DOMPET NYLON\nBLACK,BESAR\nStok: 1 Pcs\nhttps://t.co/vSsLdIalsK\n\nRp1.100\nBETA TOOLS Alas Standar Motor Jagrak Karpet Motor Polos Kualitas Baik Tebal\nStok: 10 Pcs\nhttps://t.co/aT5oOKF8ff","flash sale â 12:00 wib rp1.000 basike penyedot debu nirkabel vacuum cleaner tanpa kabel 30000pa 120w daya hisap stok: 1 pcs rp1.000 opiobags - tas umroh besar totebag wanita handbag wanita tas kanvas tote no 32 stok: 1 pcs rp1.000 opiobags dompet hp selempang wanita / dompet hp wanita / dompet nylon black,besar stok: 1 pcs rp1.100 beta tools alas standar motor jagrak karpet motor polos kualitas baik tebal stok: 10 pcs","flash sale 12:00 wib rp1.000 basike penyedot debu nirkabel vacuum cleaner tanpa kabel 30000pa 120w daya hisap stok: 1 pcs rp1.000 opiobags - tas umroh besar totebag wanita handbag wanita tas kanvas tote no 32 stok: 1 pcs rp1.000 opiobags dompet hp selempang wanita / dompet hp wanita / dompet nylon black,besar stok: 1 pcs rp1.100 beta tools alas standar motor jagrak karpet motor polos kualitas baik tebal stok: 10 pcs"
196,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/oydxCEVVUm,â 1 4ï voucher shopeefood diskon 90% max 19rb gratis ongkir 9rb â klaim di resto sebelum habis ð ð ð t. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir,1 4 voucher shopeefood diskon 90% max 19rb gratis ongkir 9rb klaim di resto sebelum habis t. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir
93,"SHOPEE FOOD Promo HOKBEN ð± Lokasari sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar! \nhttps://t.co/GKaxrqOZlc\n=====","shopee food promo hokben ð lokasari sekarang ada di shopeefood! pesan sekarang, langsung diantar!","shopee food promo hokben lokasari sekarang ada di shopeefood! pesan sekarang, langsung diantar!"
213,halo gais~\nRu ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir &gt;&lt;\nyang mau bareng bisa dm atau chat ke WA Ru yaa â¨\n\n#warunganime #warunggame,halo gais ru ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir &gt;&lt; yang mau bareng bisa dm atau chat ke wa ru yaa â warunganime warunggame,halo gais ru ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir yang mau bareng bisa dm atau chat ke wa ru yaa warunganime warunggame
15,@snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\n\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD,kan ngenes baru kemaren aja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xddd,kan ngenes baru kemaren aja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xddd

In [82]:
print("Jumlah data:", len(df_cleaning))
print("Teks kosong:", df_cleaning["clean_text_v3"].eq("").sum())
print("Nilai kosong:", df_cleaning["clean_text_v3"].isna().sum())

# Periksa apakah URL masih tersisa
url_tersisa = df_cleaning["clean_text_v3"].str.contains(
    r"https?://|www\.",
    case=False,
    regex=True
).sum()

print("Teks yang masih mengandung URL:", url_tersisa)

# Periksa apakah artefak encoding masih tersisa
artefak = df_cleaning["clean_text_v3"].str.contains(
    r"[âðï�]",
    regex=True
).sum()

print("Teks yang masih mengandung karakter artefak:", artefak)

Jumlah data: 234
Teks kosong: 0
Nilai kosong: 0
Teks yang masih mengandung URL: 0
Teks yang masih mengandung karakter artefak: 0

In [83]:
from collections import Counter
import re

# Ambil kata dari hasil text cleaning
semua_kata = []

for teks in df_cleaning["clean_text_v3"].fillna(""):
    kata = re.findall(r"\b[\w.%-]+\b", teks.lower())
    semua_kata.extend(kata)

frekuensi_kata = Counter(semua_kata)

tabel_kata = pd.DataFrame(
    frekuensi_kata.most_common(50),
    columns=["kata", "frekuensi"]
)

display(tabel_kata)

          kata  frekuensi
0           di        134
1       ongkir        116
2       gratis        114
3       shopee        110
4        promo        106
5            1        102
6      voucher        102
7       diskon         84
8   shopeefood         75
9            4         74
10        food         71
11       resto         67
12    sekarang         56
13        kode         53
14       klaim         53
15        sale         51
16         ada         50
17         dan         47
18         ini         44
19       flash         43
20      gofood         43
21    grabfood         43
22          go         43
23        grab         43
24       sfood         43
25       daget         43
26       gojek         43
27         cek         41
28           s         36
29    langsung         35
30        stok         34
31           d         33
32          00         32
33     tanggal         31
34       pesan         30
35     diantar         30
36         aku         29
37     oktober         29
38       semua         28
39         100         28
40      kembar         27
41        bisa         27
42        akun         27
43      minbel         26
44        beli         25
45          ya         25
46         20k         25
47         aja         24
48        yang         23
49      gacoan         23

In [84]:
import re
import pandas as pd

kamus_normalisasi = {
    "udah": "sudah",
    "aja": "saja",
    "gak": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "enggak": "tidak",
    "bgt": "banget",
    "ntar": "nanti",
    "yg": "yang",
    "dgn": "dengan",
    "gratong": "gratis ongkir",
}

def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    for kata_asli, kata_baru in kamus_normalisasi.items():
        pola = r"(?<!\w)" + re.escape(kata_asli) + r"(?!\w)"
        text = re.sub(pola, kata_baru, text)

    # Rapikan spasi setelah normalisasi
    text = re.sub(r"\s+", " ", text).strip()

    return text

df_cleaning["normalized_text"] = (
    df_cleaning["clean_text_v3"].apply(normalize_text)
)

display(
    df_cleaning[
        ["clean_text_v3", "normalized_text"]
    ].sample(min(10, len(df_cleaning)), random_state=42)
)

,clean_text_v3,normalized_text
69,"1 2 super seru flash sale! kuota 50gb/28 hari cuma rp100 ribu, udah termasuk langganan vidio gold, prime video, vision , dan wetv! 13-19 oktober 2026 2 mytelkomsel, *363*35#, outlet terdekat, atau klik simpatiterbaikuntukmu pastisimpati","1 2 super seru flash sale! kuota 50gb/28 hari cuma rp100 ribu, sudah termasuk langganan vidio gold, prime video, vision , dan wetv! 13-19 oktober 2026 2 mytelkomsel, *363*35#, outlet terdekat, atau klik simpatiterbaikuntukmu pastisimpati"
206,"promo tomoro coffee, ada diskon menu 40% voucher diskon 30%! cek ini » promo pilona coffee, ada voucher diskon 22k voucher gratis ongkir! cek ini » shopeefoodx promomakanan selasa pagii","promo tomoro coffee, ada diskon menu 40% voucher diskon 30%! cek ini » promo pilona coffee, ada voucher diskon 22k voucher gratis ongkir! cek ini » shopeefoodx promomakanan selasa pagii"
180,kk makasih banyak udah selalu woomen o o o smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di oren o o o « »,kk makasih banyak sudah selalu woomen o o o smoga kamu bahagia terus dan bantal kamu selalu dingin dan selalu dapet voucher gratis ongkir di oren o o o « »
9,diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9
127,"14 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior","14 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir super junior"
109,"flash sale 12:00 wib rp1.000 basike penyedot debu nirkabel vacuum cleaner tanpa kabel 30000pa 120w daya hisap stok: 1 pcs rp1.000 opiobags - tas umroh besar totebag wanita handbag wanita tas kanvas tote no 32 stok: 1 pcs rp1.000 opiobags dompet hp selempang wanita / dompet hp wanita / dompet nylon black,besar stok: 1 pcs rp1.100 beta tools alas standar motor jagrak karpet motor polos kualitas baik tebal stok: 10 pcs","flash sale 12:00 wib rp1.000 basike penyedot debu nirkabel vacuum cleaner tanpa kabel 30000pa 120w daya hisap stok: 1 pcs rp1.000 opiobags - tas umroh besar totebag wanita handbag wanita tas kanvas tote no 32 stok: 1 pcs rp1.000 opiobags dompet hp selempang wanita / dompet hp wanita / dompet nylon black,besar stok: 1 pcs rp1.100 beta tools alas standar motor jagrak karpet motor polos kualitas baik tebal stok: 10 pcs"
196,1 4 voucher shopeefood diskon 90% max 19rb gratis ongkir 9rb klaim di resto sebelum habis t. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir,1 4 voucher shopeefood diskon 90% max 19rb gratis ongkir 9rb klaim di resto sebelum habis t. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir
93,"shopee food promo hokben lokasari sekarang ada di shopeefood! pesan sekarang, langsung diantar!","shopee food promo hokben lokasari sekarang ada di shopeefood! pesan sekarang, langsung diantar!"
213,halo gais ru ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir yang mau bareng bisa dm atau chat ke wa ru yaa warunganime warunggame,halo gais ru ada req kloter surugaya yaah masih kurang 3600 yen lagi supaya gratis ongkir yang mau bareng bisa dm atau chat ke wa ru yaa warunganime warunggame
15,kan ngenes baru kemaren aja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xddd,kan ngenes baru kemaren saja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya sudah kebeli satu set dicoba dulu nanti kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xddd

In [85]:
from collections import Counter

semua_kata_normal = []

for teks in df_cleaning["normalized_text"].fillna(""):
    semua_kata_normal.extend(re.findall(r"\b[\w.%-]+\b", teks.lower()))

tabel_normalisasi = pd.DataFrame(
    Counter(semua_kata_normal).most_common(30),
    columns=["kata", "frekuensi"]
)

display(tabel_normalisasi)

          kata  frekuensi
0           di        134
1       ongkir        118
2       gratis        116
3       shopee        110
4        promo        106
5            1        102
6      voucher        102
7       diskon         84
8   shopeefood         75
9            4         74
10        food         71
11       resto         67
12    sekarang         56
13        kode         53
14       klaim         53
15        sale         51
16         ada         50
17         dan         47
18         ini         44
19       flash         43
20      gofood         43
21    grabfood         43
22          go         43
23        grab         43
24       sfood         43
25       daget         43
26       gojek         43
27         cek         41
28           s         36
29        yang         35

In [86]:
display(
    df_cleaning[
        ["original_text", "clean_text_v3", "normalized_text"]
    ].sample(min(15, len(df_cleaning)), random_state=7)
)

,original_text,clean_text_v3,normalized_text
140,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/36bmBUBHdM","13 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii","13 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii"
80,"SHOPEE FOOD Promo DOMINO'S PIZZA ð sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar â¨\nhttps://t.co/RawP9ocpg4\n=====","shopee food promo domino's pizza sekarang ada di shopeefood! pesan sekarang, langsung diantar","shopee food promo domino's pizza sekarang ada di shopeefood! pesan sekarang, langsung diantar"
84,"Aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa + gipiti 1d 8u onlii 8k . Cuma satu doang. Deem untuk claim \n\n#zonauang #zonajajan","aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa gipiti 1d 8u onlii 8k . cuma satu doang. deem untuk claim zonauang zonajajan","aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa gipiti 1d 8u onlii 8k . cuma satu doang. deem untuk claim zonauang zonajajan"
197,"Semenjak langganan grabunlimited jadi berasa banget value nya. Tiap checkout ada aja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. Pantesan orang-orang bilang ini life hack biar makin iritðð» https://t.co/8XsurSI8re","semenjak langganan grabunlimited jadi berasa banget value nya. tiap checkout ada aja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. pantesan orang-orang bilang ini life hack biar makin irit »","semenjak langganan grabunlimited jadi berasa banget value nya. tiap checkout ada saja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. pantesan orang-orang bilang ini life hack biar makin irit »"
3,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja","ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. di toko fisik jarang dpt benefit sebanyk itu. lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja","ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yang dr toko onlinenya, dpt cicilan 0% nya jg. di toko fisik jarang dpt benefit sebanyk itu. lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman saja"
85,"@_Hrst amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk","amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk","amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk"
101,SHOPEE LIVE LEBIH CANTIK &amp; HEMAT DI LIVE XTRA. Pasti DISKON 20% s/d 50 RB Untuk Semua Produk Fashion Beauty. KLAIM Vouchernya di sini ð\nhttps://t.co/l2BoZ9N3Ee\n----------,shopee live lebih cantik & hemat di live xtra. pasti diskon 20% s/d 50 rb untuk semua produk fashion beauty. klaim vouchernya di sini ----------,shopee live lebih cantik & hemat di live xtra. pasti diskon 20% s/d 50 rb untuk semua produk fashion beauty. klaim vouchernya di sini ----------
11,"ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?","ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?","ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua tidak gerak dari pagi ? gua chat di ig juga sama saja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing saja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yang sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?"
143,DAU!\nEdisi Teman Malam UTS by Kopi Ukut.\n\nSpecial Offers!!\nOnly 18k\n\nOpen: 17.00 - 02.00\n\n(+) GRATIS ONGKIR ALL AROUND NANGOR ya gengs. https://t.co/aEPcOcycLn,dau! edisi teman malam uts by kopi ukut. special offers!! only 18k open: 17.00 - 02.00 ( ) gratis ongkir all around nangor ya gengs.,dau! edisi teman malam uts by kopi ukut. special offers!! only 18k open: 17.00 - 02.00 ( ) gratis ongkir all around nangor ya gengs.
82,"SHOPEE FOOD PIZZA HUT Delivery ð Pesan sekarang di ShopeeFood, langsung diantar â¨\nhttps://t.co/MWGsdWuqEP\n=====","shopee food pizza hut delivery pesan sekarang di shopeefood, langsung diantar","shopee food pizza hut delivery pesan sekarang di shopeefood, langsung diantar"
2,btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss,btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss,btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss
164,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/HIRNWc5ewE,1 4 voucher shopeefood diskon 90% max 19rb gratis ongkir 9rb klaim di resto sebelum habis t. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir,1 4 voucher shopeefood diskon 90% max 19rb gratis ongkir 9rb klaim di resto sebelum habis t. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir
174,"@hdupsdiih @miawgumo sebenernya gratong ttep dari shopee kakk cmiiw, tapi seller ada biaya adm krn daftar gratis ongkir gituuu (bbrp persen tergantung kategori produk) \n\njadi walaupun ongkir pembeli misal cuman 20k, tapi krn persenan adm tadi dikali harga barang jadi yaa WKWKWKWK","sebenernya gratong ttep dari shopee kakk cmiiw, tapi seller ada biaya adm krn daftar gratis ongkir gituuu (bbrp persen tergantung kategori produk) jadi walaupun ongkir pembeli misal cuman 20k, tapi krn persenan adm tadi dikali harga barang jadi yaa wkwkwkwk","sebenernya gratis ongkir ttep dari shopee kakk cmiiw, tapi seller ada biaya adm krn daftar gratis ongkir gituuu (bbrp persen tergantung kategori produk) jadi walaupun ongkir pembeli misal cuman 20k, tapi krn persenan adm tadi dikali harga barang jadi yaa wkwkwkwk"
57,"SHOPEE FOOD Promo DISKON McDonald's ððð¦ [ BUKA 24 JAM ] Pesan di ShopeeFood Sekarang, langsung diantar â¨\nhttps://t.co/iRlFzRtqEc\n----------","shopee food promo diskon mcdonald's [ buka 24 jam ] pesan di shopeefood sekarang, langsung diantar ----------","shopee food promo diskon mcdonald's [ buka 24 jam ] pesan di shopeefood sekarang, langsung diantar ----------"
24,@ayrzz_ biasanya pas tanggal kembar aja kak,biasanya pas tanggal kembar aja kak,biasanya pas tanggal kembar saja kak

In [87]:
import re
import pandas as pd

kamus_normalisasi = {
    "udah": "sudah",
    "aja": "saja",
    "gak": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "enggak": "tidak",
    "bgt": "banget",
    "ntar": "nanti",
    "yg": "yang",
    "dgn": "dengan",
    "gratong": "gratis ongkir",
    "sampe": "sampai",
    "ampe": "sampai",
    "kalo": "kalau",
    "gitu": "begitu",
    "gini": "begini",
    "aja": "saja",
}

def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    for kata_asli, kata_baru in kamus_normalisasi.items():
        pola = r"(?<!\w)" + re.escape(kata_asli) + r"(?!\w)"
        text = re.sub(pola, kata_baru, text)

    text = re.sub(r"\s+", " ", text).strip()
    return text

df_cleaning["normalized_text"] = (
    df_cleaning["clean_text_v3"].apply(normalize_text)
)

display(
    df_cleaning[
        ["original_text", "clean_text_v3", "normalized_text"]
    ].sample(min(10, len(df_cleaning)), random_state=7)
)

,original_text,clean_text_v3,normalized_text
140,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/36bmBUBHdM","13 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii","13 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii"
80,"SHOPEE FOOD Promo DOMINO'S PIZZA ð sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar â¨\nhttps://t.co/RawP9ocpg4\n=====","shopee food promo domino's pizza sekarang ada di shopeefood! pesan sekarang, langsung diantar","shopee food promo domino's pizza sekarang ada di shopeefood! pesan sekarang, langsung diantar"
84,"Aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa + gipiti 1d 8u onlii 8k . Cuma satu doang. Deem untuk claim \n\n#zonauang #zonajajan","aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa gipiti 1d 8u onlii 8k . cuma satu doang. deem untuk claim zonauang zonajajan","aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa gipiti 1d 8u onlii 8k . cuma satu doang. deem untuk claim zonauang zonajajan"
197,"Semenjak langganan grabunlimited jadi berasa banget value nya. Tiap checkout ada aja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. Pantesan orang-orang bilang ini life hack biar makin iritðð» https://t.co/8XsurSI8re","semenjak langganan grabunlimited jadi berasa banget value nya. tiap checkout ada aja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. pantesan orang-orang bilang ini life hack biar makin irit »","semenjak langganan grabunlimited jadi berasa banget value nya. tiap checkout ada saja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. pantesan orang-orang bilang ini life hack biar makin irit »"
3,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja","ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. di toko fisik jarang dpt benefit sebanyk itu. lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja","ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalau punya paylater yang dr toko onlinenya, dpt cicilan 0% nya jg. di toko fisik jarang dpt benefit sebanyk itu. lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman saja"
85,"@_Hrst amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk","amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk","amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk"
101,SHOPEE LIVE LEBIH CANTIK &amp; HEMAT DI LIVE XTRA. Pasti DISKON 20% s/d 50 RB Untuk Semua Produk Fashion Beauty. KLAIM Vouchernya di sini ð\nhttps://t.co/l2BoZ9N3Ee\n----------,shopee live lebih cantik & hemat di live xtra. pasti diskon 20% s/d 50 rb untuk semua produk fashion beauty. klaim vouchernya di sini ----------,shopee live lebih cantik & hemat di live xtra. pasti diskon 20% s/d 50 rb untuk semua produk fashion beauty. klaim vouchernya di sini ----------
11,"ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?","ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?","ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua tidak gerak dari pagi ? gua chat di ig juga sama saja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampai packing saja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yang sama sudah berangkat dari pagi, ini xiaomi kenapa begini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampai pake bot ?"
143,DAU!\nEdisi Teman Malam UTS by Kopi Ukut.\n\nSpecial Offers!!\nOnly 18k\n\nOpen: 17.00 - 02.00\n\n(+) GRATIS ONGKIR ALL AROUND NANGOR ya gengs. https://t.co/aEPcOcycLn,dau! edisi teman malam uts by kopi ukut. special offers!! only 18k open: 17.00 - 02.00 ( ) gratis ongkir all around nangor ya gengs.,dau! edisi teman malam uts by kopi ukut. special offers!! only 18k open: 17.00 - 02.00 ( ) gratis ongkir all around nangor ya gengs.
82,"SHOPEE FOOD PIZZA HUT Delivery ð Pesan sekarang di ShopeeFood, langsung diantar â¨\nhttps://t.co/MWGsdWuqEP\n=====","shopee food pizza hut delivery pesan sekarang di shopeefood, langsung diantar","shopee food pizza hut delivery pesan sekarang di shopeefood, langsung diantar"

In [88]:
import re
import pandas as pd

kamus_normalisasi = {
    "udah": "sudah",
    "aja": "saja",
    "gak": "tidak",
    "ga": "tidak",
    "nggak": "tidak",
    "enggak": "tidak",
    "bgt": "banget",
    "ntar": "nanti",
    "yg": "yang",
    "byk": "banyak",
    "dgn": "dengan",
    "gratong": "gratis ongkir",
    "sampe": "sampai",
    "ampe": "sampai",
    "kalo": "kalau",
    "gitu": "begitu",
    "gini": "begini",
    "onlen": "online",
    "aplgi": "apalagi",
    "dpt": "dapat",
    "jg": "juga",
    "cm": "cuma",
    "tpi": "tapi",
    "gbsa": "tidak bisa",
}

def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Hilangkan dekorasi berupa deretan tanda hubung
    text = re.sub(r"[-]{3,}", " ", text)

    for kata_asli, kata_baru in kamus_normalisasi.items():
        pola = r"(?<!\w)" + re.escape(kata_asli) + r"(?!\w)"
        text = re.sub(pola, kata_baru, text)

    return re.sub(r"\s+", " ", text).strip()

df_cleaning["normalized_text"] = (
    df_cleaning["clean_text_v3"].apply(normalize_text)
)

display(
    df_cleaning[
        ["original_text", "clean_text_v3", "normalized_text"]
    ].sample(min(10, len(df_cleaning)), random_state=7)
)

,original_text,clean_text_v3,normalized_text
140,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/36bmBUBHdM","13 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii","13 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii"
80,"SHOPEE FOOD Promo DOMINO'S PIZZA ð sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar â¨\nhttps://t.co/RawP9ocpg4\n=====","shopee food promo domino's pizza sekarang ada di shopeefood! pesan sekarang, langsung diantar","shopee food promo domino's pizza sekarang ada di shopeefood! pesan sekarang, langsung diantar"
84,"Aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa + gipiti 1d 8u onlii 8k . Cuma satu doang. Deem untuk claim \n\n#zonauang #zonajajan","aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa gipiti 1d 8u onlii 8k . cuma satu doang. deem untuk claim zonauang zonajajan","aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa gipiti 1d 8u onlii 8k . cuma satu doang. deem untuk claim zonauang zonajajan"
197,"Semenjak langganan grabunlimited jadi berasa banget value nya. Tiap checkout ada aja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. Pantesan orang-orang bilang ini life hack biar makin iritðð» https://t.co/8XsurSI8re","semenjak langganan grabunlimited jadi berasa banget value nya. tiap checkout ada aja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. pantesan orang-orang bilang ini life hack biar makin irit »","semenjak langganan grabunlimited jadi berasa banget value nya. tiap checkout ada saja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. pantesan orang-orang bilang ini life hack biar makin irit »"
3,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja","ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. di toko fisik jarang dpt benefit sebanyk itu. lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja","ya online kan banyak diskonannyaa terus banyak bonusnya juga, apalagi tanggal kembar, aplg kalau punya paylater yang dr toko onlinenya, dapat cicilan 0% nya juga. di toko fisik jarang dapat benefit sebanyk itu. lg pula itu kejadian juga cuma 0 koma sekian persen lah, w slalu beli online dan aman saja"
85,"@_Hrst amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk","amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk","amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk"
101,SHOPEE LIVE LEBIH CANTIK &amp; HEMAT DI LIVE XTRA. Pasti DISKON 20% s/d 50 RB Untuk Semua Produk Fashion Beauty. KLAIM Vouchernya di sini ð\nhttps://t.co/l2BoZ9N3Ee\n----------,shopee live lebih cantik & hemat di live xtra. pasti diskon 20% s/d 50 rb untuk semua produk fashion beauty. klaim vouchernya di sini ----------,shopee live lebih cantik & hemat di live xtra. pasti diskon 20% s/d 50 rb untuk semua produk fashion beauty. klaim vouchernya di sini
11,"ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?","ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?","ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua tidak gerak dari pagi ? gua chat di ig juga sama saja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampai packing saja keteteran ? prasaan bukan tanggal kembar tapi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yang sama sudah berangkat dari pagi, ini xiaomi kenapa begini ya pelaynannya ? tidak bisa ngegaji karyawan sebagai admin apa gimana sampai pake bot ?"
143,DAU!\nEdisi Teman Malam UTS by Kopi Ukut.\n\nSpecial Offers!!\nOnly 18k\n\nOpen: 17.00 - 02.00\n\n(+) GRATIS ONGKIR ALL AROUND NANGOR ya gengs. https://t.co/aEPcOcycLn,dau! edisi teman malam uts by kopi ukut. special offers!! only 18k open: 17.00 - 02.00 ( ) gratis ongkir all around nangor ya gengs.,dau! edisi teman malam uts by kopi ukut. special offers!! only 18k open: 17.00 - 02.00 ( ) gratis ongkir all around nangor ya gengs.
82,"SHOPEE FOOD PIZZA HUT Delivery ð Pesan sekarang di ShopeeFood, langsung diantar â¨\nhttps://t.co/MWGsdWuqEP\n=====","shopee food pizza hut delivery pesan sekarang di shopeefood, langsung diantar","shopee food pizza hut delivery pesan sekarang di shopeefood, langsung diantar"

In [90]:
# Tambahkan aturan yang maknanya cukup jelas
kamus_normalisasi.update({
    "lg": "lagi",
    "sebanyk": "sebanyak",
    "prasaan": "perasaan",
    "pelaynannya": "pelayanannya",
    "tpi": "tapi",
    "dr": "dari",
    "w": "aku",
})

df_cleaning["normalized_text"] = (
    df_cleaning["clean_text_v3"].apply(normalize_text)
)

# Periksa sampel terbaru
display(
    df_cleaning[
        ["original_text", "clean_text_v3", "normalized_text"]
    ].sample(min(10, len(df_cleaning)), random_state=7)
)

,original_text,clean_text_v3,normalized_text
140,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/36bmBUBHdM","13 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii","13 oktober shopeefood diskon 100% s/d 35rb minbel 20k. semua resto, akun tertentu 1 4 1 4 cek dan klaim di resto ini gofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii"
80,"SHOPEE FOOD Promo DOMINO'S PIZZA ð sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar â¨\nhttps://t.co/RawP9ocpg4\n=====","shopee food promo domino's pizza sekarang ada di shopeefood! pesan sekarang, langsung diantar","shopee food promo domino's pizza sekarang ada di shopeefood! pesan sekarang, langsung diantar"
84,"Aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa + gipiti 1d 8u onlii 8k . Cuma satu doang. Deem untuk claim \n\n#zonauang #zonajajan","aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa gipiti 1d 8u onlii 8k . cuma satu doang. deem untuk claim zonauang zonajajan","aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa gipiti 1d 8u onlii 8k . cuma satu doang. deem untuk claim zonauang zonajajan"
197,"Semenjak langganan grabunlimited jadi berasa banget value nya. Tiap checkout ada aja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. Pantesan orang-orang bilang ini life hack biar makin iritðð» https://t.co/8XsurSI8re","semenjak langganan grabunlimited jadi berasa banget value nya. tiap checkout ada aja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. pantesan orang-orang bilang ini life hack biar makin irit »","semenjak langganan grabunlimited jadi berasa banget value nya. tiap checkout ada saja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. pantesan orang-orang bilang ini life hack biar makin irit »"
3,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja","ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. di toko fisik jarang dpt benefit sebanyk itu. lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja","ya online kan banyak diskonannyaa terus banyak bonusnya juga, apalagi tanggal kembar, aplg kalau punya paylater yang dari toko onlinenya, dapat cicilan 0% nya juga. di toko fisik jarang dapat benefit sebanyak itu. lagi pula itu kejadian juga cuma 0 koma sekian persen lah, aku slalu beli online dan aman saja"
85,"@_Hrst amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk","amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk","amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk"
101,SHOPEE LIVE LEBIH CANTIK &amp; HEMAT DI LIVE XTRA. Pasti DISKON 20% s/d 50 RB Untuk Semua Produk Fashion Beauty. KLAIM Vouchernya di sini ð\nhttps://t.co/l2BoZ9N3Ee\n----------,shopee live lebih cantik & hemat di live xtra. pasti diskon 20% s/d 50 rb untuk semua produk fashion beauty. klaim vouchernya di sini ----------,shopee live lebih cantik & hemat di live xtra. pasti diskon 20% s/d 50 rb untuk semua produk fashion beauty. klaim vouchernya di sini
11,"ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?","ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?","ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua tidak gerak dari pagi ? gua chat di ig juga sama saja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampai packing saja keteteran ? perasaan bukan tanggal kembar tapi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yang sama sudah berangkat dari pagi, ini xiaomi kenapa begini ya pelayanannya ? tidak bisa ngegaji karyawan sebagai admin apa gimana sampai pake bot ?"
143,DAU!\nEdisi Teman Malam UTS by Kopi Ukut.\n\nSpecial Offers!!\nOnly 18k\n\nOpen: 17.00 - 02.00\n\n(+) GRATIS ONGKIR ALL AROUND NANGOR ya gengs. https://t.co/aEPcOcycLn,dau! edisi teman malam uts by kopi ukut. special offers!! only 18k open: 17.00 - 02.00 ( ) gratis ongkir all around nangor ya gengs.,dau! edisi teman malam uts by kopi ukut. special offers!! only 18k open: 17.00 - 02.00 ( ) gratis ongkir all around nangor ya gengs.
82,"SHOPEE FOOD PIZZA HUT Delivery ð Pesan sekarang di ShopeeFood, langsung diantar â¨\nhttps://t.co/MWGsdWuqEP\n=====","shopee food pizza hut delivery pesan sekarang di shopeefood, langsung diantar","shopee food pizza hut delivery pesan sekarang di shopeefood, langsung diantar"

In [91]:
df_cleaning["relevansi_manual"] = ""

# Contoh label berdasarkan peninjauan sementara:
# Ganti nilai ID sesuai tipe kolom ID pada dataset kamu.
df_cleaning.loc[
    df_cleaning["id"].astype(str) == "11",
    "relevansi_manual"
] = "tidak_relevan"

df_cleaning.loc[
    df_cleaning["id"].astype(str).isin(["143", "82"]),
    "relevansi_manual"
] = "perlu_konteks"

display(
    df_cleaning[
        ["id", "original_text", "relevansi_manual"]
    ].head()
)

,id,original_text,relevansi_manual
0,2110049779162153142,"@afrkml ak kemarin beli 3 hp di shopee aman aman aja. tapi lihat postingan kaya gini harus hati2 juga sih\n\nsebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik",
1,2110037673167737100,close yaa! timaacii yang sudah ikutan dan meramaikan :3 sampai bertemu di tanggal kembar selanjutnya iaa ð§ð»ââï¸,
2,2110037344552186209,btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss,
3,2110010539950899311,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja",
4,2110004575105388837,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk Jisulife lagi ð­",

In [92]:
label_relevansi = {
    0: "relevan_kontekstual",
    1: "perlu_konteks",
    2: "perlu_konteks",
    3: "relevan_kontekstual",
    4: "perlu_konteks",
}

for indeks, label in label_relevansi.items():
    df_cleaning.at[indeks, "relevansi_manual"] = label

display(
    df_cleaning[
        ["original_text", "relevansi_manual"]
    ].head(5)
)

,original_text,relevansi_manual
0,"@afrkml ak kemarin beli 3 hp di shopee aman aman aja. tapi lihat postingan kaya gini harus hati2 juga sih\n\nsebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik",relevan_kontekstual
1,close yaa! timaacii yang sudah ikutan dan meramaikan :3 sampai bertemu di tanggal kembar selanjutnya iaa ð§ð»ââï¸,perlu_konteks
2,btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss,perlu_konteks
3,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja",relevan_kontekstual
4,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk Jisulife lagi ð­",perlu_konteks

In [93]:
# Tampilkan tweet yang belum diberi label relevansi
belum_dilabeli = df_cleaning[
    df_cleaning["relevansi_manual"].isna()
    | (df_cleaning["relevansi_manual"].astype(str).str.strip() == "")
]

print("Jumlah tweet yang belum dilabeli:", len(belum_dilabeli))

display(
    belum_dilabeli[
        ["original_text", "relevansi_manual"]
    ].head(20)
)

Jumlah tweet yang belum dilabeli: 229

,original_text,relevansi_manual
5,"Syongsok menikah di tanggal kembar, anaknya kembar juga gak?",
6,@nattwtij Masama sayangkuuu ð\nKalau beli elektronik begitu saranku better beli di tanggal kembar ð potongan nya sering gila-gilaan,
7,"Ges mau nanyað\nShopee kalian kalau lagi ga event tanggal kembar atau tanggal 25, tetep bisa freeong?\n\n((Nanya dulu, kali aja tiba2 aku mau sale lagi))",
8,"Tes kekencangan si Jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. Tapi jisulife 5 cuma ada 3 tingkatan angin \n\nBeli pas tanggal kembar oke banget diskon nya ð¥° https://t.co/5E17pVy4YR",
9,@riorkha Diskon tanggal kembar oren dong 9.9,
10,"@Weist9953 aku ð­âï¸ tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong gak sih?",
11,"ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?",
12,@usedtob3me Ga ada Kak\nBeli tanggal kembar aja\nAku pake sampe ke bokong dan beneran bagus ð­ð­ð­,
13,"siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampe 7 turunan",
14,"@LambeSahamjja emang melemah njir, buktinya event tanggal kembar sepi",
15,@snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\n\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD,
16,"Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKeranjang belanjaan tanggal kembar besok udah penuh, tapi saldo e-wallet masih kosong melompong? Top up e-wallet favoritmu di Orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!ðï¸ð https://t.co/VYdb3cw5Zn",
17,@usedtob3me Cetaphil bisa murah kalau beli di Lazada (watsons)\nKalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar)\nLebih murah lagi ada hadalabo gokujyun (agak berbusa dikit),
18,Help RT or repost tweet di bawah ini guyss ð¥º #zonauang\n\nAku ada optip open titip layout dalam rangka tanggal kembar 10.10 dengan harga spesial special price promo diskon 6k aja!!\n\nBisa sampai tanggal 17 Oktober yaaa ð,
19,"Hidup tuh jangan terlalu serius, nanti cepat tua. Tapi kalau terlalu santai, takut miskin. Mau kerja capek, nggak kerja nggak punya duit. Mau hemat, banyak godaan. Mau kaya, rebahan mulu. Ya Allah, sebenarnya aku ini maunya hidup atau cuma mau menikmati promo tanggal kembar? ð­",
20,"mending beli pb ugreen 20.000mAh sekarang 310rb,atau nanti 11.11? waktu bayarnya sampe jam 1 ini, bayar aja apa nunggu 11.11 ya? tapi kadang tanggal kembar jg promonya yaudah aja",
21,@Boyvulations Ga pas tanggal kembar biar tiap anniv bisa CO dapet diskon?,
22,@usedtob3me Cetaphil murah kak kalau belinya tanggal kembar pake koin di lazada + voucher beauty\nJangan di oren karena mahal,
23,@ilymoontae jamayyy pas tanggal kembar ðð baterai 71% ak pakai seharian di mobil masi 54% malah udah jatuh dari kasur ke lantai tp masi bernyawa https://t.co/hRlYydkfbV,
24,@ayrzz_ biasanya pas tanggal kembar aja kak,

In [94]:

import re
import pandas as pd

def label_relevansi_otomatis(teks):
    teks = str(teks).lower()

    # Deteksi penyebutan tanggal kembar / 10.10
    langsung = bool(re.search(
        r"10\s*[./-]\s*10|10\.10|tanggal\s+kembar|"
        r"\b10\s*10\b|double\s*date",
        teks
    ))

    # Indikasi percakapan tentang promosi belanja
    promo = bool(re.search(
        r"promo|promosi|diskon|discount|voucher|kupon|"
        r"flash\s*sale|flashsale|gratis\s*ongkir|freeong|"
        r"belanja|checkout|marketplace|shopee|tokopedia|"
        r"lazada|blibli|paylater|potongan\s+harga",
        teks
    ))

    # Kemungkinan penyebutan tanggal kembar yang tidak berkaitan
    konteks_tidak_relevan = bool(re.search(
        r"anaknya kembar|menikah di tanggal kembar|"
        r"ulang tahun|anniversary",
        teks
    ))

    if konteks_tidak_relevan and not promo:
        return "tidak_relevan"
    elif langsung and promo:
        return "relevan_langsung"
    elif langsung:
        return "perlu_konteks"
    elif promo:
        return "relevan_kontekstual"
    else:
        return "perlu_konteks"


# Isi hanya label yang masih kosong
mask_kosong = (
    df_cleaning["relevansi_manual"].isna()
    | df_cleaning["relevansi_manual"].astype(str).str.strip().eq("")
)

df_cleaning.loc[mask_kosong, "relevansi_manual"] = (
    df_cleaning.loc[mask_kosong, "original_text"]
    .apply(label_relevansi_otomatis)
)

print("Total tweet:", len(df_cleaning))
print("\nJumlah label:")
display(df_cleaning["relevansi_manual"].value_counts().to_frame("jumlah"))

print("\nContoh hasil label:")
display(
    df_cleaning[
        ["original_text", "relevansi_manual"]
    ].sample(min(15, len(df_cleaning)), random_state=7)
)

Total tweet: 234

Jumlah label:

                     jumlah
relevansi_manual
relevan_kontekstual     177
relevan_langsung         30
perlu_konteks            26
tidak_relevan             1

Contoh hasil label:

,original_text,relevansi_manual
140,"ðï¸ 13 Oktober \nShopeefood Diskon 100% s/d 35rb minbel 20K. Semua resto, akun tertentu â¼ï¸â¼ï¸\n\nCek dan klaim di resto ini ð\nhttps://t.co/B7nYSwxfbG\nhttps://t.co/B7nYSwxfbG\n\ngofood grabfood kode promo go grab shopee food sfood voucher daget gojek gratis ongkir sanggup kakang pagii https://t.co/36bmBUBHdM",relevan_kontekstual
80,"SHOPEE FOOD Promo DOMINO'S PIZZA ð sekarang ada di ShopeeFood! Pesan Sekarang, langsung diantar â¨\nhttps://t.co/RawP9ocpg4\n=====",relevan_kontekstual
84,"Aku ridi flash sale lah, yt fampl 1b ( acc pribadi) only 7k sajaa + gipiti 1d 8u onlii 8k . Cuma satu doang. Deem untuk claim \n\n#zonauang #zonajajan",relevan_kontekstual
197,"Semenjak langganan grabunlimited jadi berasa banget value nya. Tiap checkout ada aja diskonnya, gratis ongkir, ada voucher tambahan juga. yang tadinya ongkir 15rb jadi kepotong 10rb, ditambah diskon hampir 30rb lagi. Pantesan orang-orang bilang ini life hack biar makin iritðð» https://t.co/8XsurSI8re",relevan_kontekstual
3,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja",relevan_kontekstual
85,"@_Hrst amin bang, tapi tiap ada flash sale jempolnya jalan sendiri wkwk",relevan_kontekstual
101,SHOPEE LIVE LEBIH CANTIK &amp; HEMAT DI LIVE XTRA. Pasti DISKON 20% s/d 50 RB Untuk Semua Produk Fashion Beauty. KLAIM Vouchernya di sini ð\nhttps://t.co/l2BoZ9N3Ee\n----------,relevan_kontekstual
11,"ini pelayanan sebesar xiaomi ngehadapin customer dikasih cs bot terus ? gila kali ya paket gua ga gerak dari pagi ? gua chat di ig juga sama aja disuruh tunggu tanpa ada tindakan nyatanya, emang karyawannya pada ngapain sampe packing aja keteteran ? prasaan bukan tanggal kembar tpi bilangnya overloa terus, gua beli jam tangan juga di brand lain di hari yg sama sudah berangkat dari pagi, ini xiaomi kenapa gini ya pelaynannya ? gbsa ngegaji karyawan sebagai admin apa gimana sampe pake bot ?",perlu_konteks
143,DAU!\nEdisi Teman Malam UTS by Kopi Ukut.\n\nSpecial Offers!!\nOnly 18k\n\nOpen: 17.00 - 02.00\n\n(+) GRATIS ONGKIR ALL AROUND NANGOR ya gengs. https://t.co/aEPcOcycLn,relevan_kontekstual
82,"SHOPEE FOOD PIZZA HUT Delivery ð Pesan sekarang di ShopeeFood, langsung diantar â¨\nhttps://t.co/MWGsdWuqEP\n=====",relevan_kontekstual
2,btw kalo abis tanggal kembar emang gini yaa? susah banget naik viewss,perlu_konteks
164,â¼ï¸Voucher shopeefood diskon 90% max 19rb + Gratis ongkir 9rb â¨\n\nKlaim di resto sebelum habis ððð\nhttps://t.co/KpFtHU1fPp\nhttps://t.co/KpFtHU1fPp\n\nt. gofood grabfood kode promo go grab shopee food sfood voucher gacoan daget gojek gratis ongkir https://t.co/HIRNWc5ewE,relevan_kontekstual
174,"@hdupsdiih @miawgumo sebenernya gratong ttep dari shopee kakk cmiiw, tapi seller ada biaya adm krn daftar gratis ongkir gituuu (bbrp persen tergantung kategori produk) \n\njadi walaupun ongkir pembeli misal cuman 20k, tapi krn persenan adm tadi dikali harga barang jadi yaa WKWKWKWK",relevan_kontekstual
57,"SHOPEE FOOD Promo DISKON McDonald's ððð¦ [ BUKA 24 JAM ] Pesan di ShopeeFood Sekarang, langsung diantar â¨\nhttps://t.co/iRlFzRtqEc\n----------",relevan_kontekstual
24,@ayrzz_ biasanya pas tanggal kembar aja kak,perlu_konteks

In [95]:
print("Jumlah seluruh tweet:", len(df_cleaning))
print("\nDistribusi label relevansi:")
display(
    df_cleaning["relevansi_manual"]
    .value_counts(dropna=False)
    .to_frame("jumlah_tweet")
)

# Periksa tweet yang dianggap relevan langsung
display(
    df_cleaning.loc[
        df_cleaning["relevansi_manual"] == "relevan_langsung",
        ["original_text", "relevansi_manual"]
    ].head(15)
)

Jumlah seluruh tweet: 234

Distribusi label relevansi:

                     jumlah_tweet
relevansi_manual
relevan_kontekstual           177
relevan_langsung               30
perlu_konteks                  26
tidak_relevan                   1

,original_text,relevansi_manual
7,"Ges mau nanyað\nShopee kalian kalau lagi ga event tanggal kembar atau tanggal 25, tetep bisa freeong?\n\n((Nanya dulu, kali aja tiba2 aku mau sale lagi))",relevan_langsung
8,"Tes kekencangan si Jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. Tapi jisulife 5 cuma ada 3 tingkatan angin \n\nBeli pas tanggal kembar oke banget diskon nya ð¥° https://t.co/5E17pVy4YR",relevan_langsung
9,@riorkha Diskon tanggal kembar oren dong 9.9,relevan_langsung
10,"@Weist9953 aku ð­âï¸ tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong gak sih?",relevan_langsung
13,"siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampe 7 turunan",relevan_langsung
15,@snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\n\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD,relevan_langsung
16,"Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKeranjang belanjaan tanggal kembar besok udah penuh, tapi saldo e-wallet masih kosong melompong? Top up e-wallet favoritmu di Orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!ðï¸ð https://t.co/VYdb3cw5Zn",relevan_langsung
17,@usedtob3me Cetaphil bisa murah kalau beli di Lazada (watsons)\nKalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar)\nLebih murah lagi ada hadalabo gokujyun (agak berbusa dikit),relevan_langsung
18,Help RT or repost tweet di bawah ini guyss ð¥º #zonauang\n\nAku ada optip open titip layout dalam rangka tanggal kembar 10.10 dengan harga spesial special price promo diskon 6k aja!!\n\nBisa sampai tanggal 17 Oktober yaaa ð,relevan_langsung
19,"Hidup tuh jangan terlalu serius, nanti cepat tua. Tapi kalau terlalu santai, takut miskin. Mau kerja capek, nggak kerja nggak punya duit. Mau hemat, banyak godaan. Mau kaya, rebahan mulu. Ya Allah, sebenarnya aku ini maunya hidup atau cuma mau menikmati promo tanggal kembar? ð­",relevan_langsung
20,"mending beli pb ugreen 20.000mAh sekarang 310rb,atau nanti 11.11? waktu bayarnya sampe jam 1 ini, bayar aja apa nunggu 11.11 ya? tapi kadang tanggal kembar jg promonya yaudah aja",relevan_langsung
21,@Boyvulations Ga pas tanggal kembar biar tiap anniv bisa CO dapet diskon?,relevan_langsung
22,@usedtob3me Cetaphil murah kak kalau belinya tanggal kembar pake koin di lazada + voucher beauty\nJangan di oren karena mahal,relevan_langsung
25,@broystv nggak sampe semenit kak 10.500 aja lagi promo 10.10 kakak,relevan_langsung
26,"@watermewlons_ 169 lagi, ga ada bonus promo 10.10 kah",relevan_langsung

In [96]:
label_dipakai = [
    "relevan_langsung",
    "relevan_kontekstual"
]

df_relevan = df_cleaning[
    df_cleaning["relevansi_manual"].isin(label_dipakai)
].copy()

print("Jumlah data relevan sementara:", len(df_relevan))

display(
    df_relevan[
        ["original_text", "relevansi_manual", "normalized_text"]
    ].head(10)
)

Jumlah data relevan sementara: 207

,original_text,relevansi_manual,normalized_text
0,"@afrkml ak kemarin beli 3 hp di shopee aman aman aja. tapi lihat postingan kaya gini harus hati2 juga sih\n\nsebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik",relevan_kontekstual,"ak kemarin beli 3 hp di shopee aman aman saja. tapi lihat postingan kaya begini harus hati2 juga sih sebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik"
3,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja",relevan_kontekstual,"ya online kan banyak diskonannyaa terus banyak bonusnya juga, apalagi tanggal kembar, aplg kalau punya paylater yang dari toko onlinenya, dapat cicilan 0% nya juga. di toko fisik jarang dapat benefit sebanyak itu. lagi pula itu kejadian juga cuma 0 koma sekian persen lah, aku slalu beli online dan aman saja"
7,"Ges mau nanyað\nShopee kalian kalau lagi ga event tanggal kembar atau tanggal 25, tetep bisa freeong?\n\n((Nanya dulu, kali aja tiba2 aku mau sale lagi))",relevan_langsung,"ges mau nanya shopee kalian kalau lagi tidak event tanggal kembar atau tanggal 25, tetep bisa freeong? ((nanya dulu, kali saja tiba2 aku mau sale lagi))"
8,"Tes kekencangan si Jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. Tapi jisulife 5 cuma ada 3 tingkatan angin \n\nBeli pas tanggal kembar oke banget diskon nya ð¥° https://t.co/5E17pVy4YR",relevan_langsung,"tes kekencangan si jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. tapi jisulife 5 cuma ada 3 tingkatan angin beli pas tanggal kembar oke banget diskon nya"
9,@riorkha Diskon tanggal kembar oren dong 9.9,relevan_langsung,diskon tanggal kembar oren dong 9.9
10,"@Weist9953 aku ð­âï¸ tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong gak sih?",relevan_langsung,"aku tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong tidak sih?"
13,"siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampe 7 turunan",relevan_langsung,"siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampai 7 turunan"
15,@snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\n\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD,relevan_langsung,kan ngenes baru kemaren saja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya sudah kebeli satu set dicoba dulu nanti kalau ada duit dan pen beli lagi ya nunggu tanggal kembar xddd
16,"Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKeranjang belanjaan tanggal kembar besok udah penuh, tapi saldo e-wallet masih kosong melompong? Top up e-wallet favoritmu di Orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!ðï¸ð https://t.co/VYdb3cw5Zn",relevan_langsung,"jangan biarin saldo e-wallet kosong! keranjang belanjaan tanggal kembar besok sudah penuh, tapi saldo e-wallet masih kosong melompong? top up e-wallet favoritmu di orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!"
17,@usedtob3me Cetaphil bisa murah kalau beli di Lazada (watsons)\nKalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar)\nLebih murah lagi ada hadalabo gokujyun (agak berbusa dikit),relevan_langsung,cetaphil bisa murah kalau beli di lazada (watsons) kalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar) lebih murah lagi ada hadalabo gokujyun (agak berbusa dikit)

Stopword removal

In [97]:
!pip -q install Sastrawi

import re
import nltk
from nltk.corpus import stopwords

nltk.download("stopwords", quiet=True)

stopword_id = set(stopwords.words("indonesian"))

# Jangan hapus kata yang dapat membalikkan makna sentimen
kata_penting = {
    "tidak", "bukan", "belum", "jangan", "kurang", "tanpa"
}
stopword_id = stopword_id - kata_penting

def hapus_stopword(teks):
    kata = str(teks).split()
    hasil = [k for k in kata if k not in stopword_id]
    return " ".join(hasil)

df_relevan["text_no_stopword"] = (
    df_relevan["normalized_text"].apply(hapus_stopword)
)

display(
    df_relevan[
        ["normalized_text", "text_no_stopword"]
    ].head(10)
)

,normalized_text,text_no_stopword
0,"ak kemarin beli 3 hp di shopee aman aman saja. tapi lihat postingan kaya begini harus hati2 juga sih sebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik","ak kemarin beli 3 hp shopee aman aman saja. lihat postingan kaya hati2 sih harga diskon beli tanggal kembar tanggal 25, beli mall beli toko hp harganya"
3,"ya online kan banyak diskonannyaa terus banyak bonusnya juga, apalagi tanggal kembar, aplg kalau punya paylater yang dari toko onlinenya, dapat cicilan 0% nya juga. di toko fisik jarang dapat benefit sebanyak itu. lagi pula itu kejadian juga cuma 0 koma sekian persen lah, aku slalu beli online dan aman saja","ya online diskonannyaa bonusnya juga, tanggal kembar, aplg paylater toko onlinenya, cicilan 0% nya juga. toko fisik jarang benefit itu. kejadian 0 koma sekian persen lah, slalu beli online aman"
7,"ges mau nanya shopee kalian kalau lagi tidak event tanggal kembar atau tanggal 25, tetep bisa freeong? ((nanya dulu, kali saja tiba2 aku mau sale lagi))","ges nanya shopee tidak event tanggal kembar tanggal 25, tetep freeong? ((nanya dulu, kali tiba2 sale lagi))"
8,"tes kekencangan si jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. tapi jisulife 5 cuma ada 3 tingkatan angin beli pas tanggal kembar oke banget diskon nya","tes kekencangan si jisulife 10 oke sih, 5 tingkatan, ya suaranya emang berisik dibanding jisulife 5. jisulife 5 3 tingkatan angin beli pas tanggal kembar oke banget diskon nya"
9,diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren 9.9
10,"aku tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong tidak sih?","tanyaa deh, toko kl diluar payday sale tanggal kembar freeong tidak sih?"
13,"siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampai 7 turunan","menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir 7 turunan"
15,kan ngenes baru kemaren saja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya sudah kebeli satu set dicoba dulu nanti kalau ada duit dan pen beli lagi ya nunggu tanggal kembar xddd,ngenes kemaren haaaaaaaaaa mbak kasirnya tanggal kembar tsubakinya promo (ini superindo) ya kebeli set dicoba duit pen beli ya nunggu tanggal kembar xddd
16,"jangan biarin saldo e-wallet kosong! keranjang belanjaan tanggal kembar besok sudah penuh, tapi saldo e-wallet masih kosong melompong? top up e-wallet favoritmu di orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!","jangan biarin saldo e-wallet kosong! keranjang belanjaan tanggal kembar besok penuh, saldo e-wallet kosong melompong? top up e-wallet favoritmu orderkuota juga, klik langsung masuk, biaya admin hemat ramah kantong!"
17,cetaphil bisa murah kalau beli di lazada (watsons) kalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar) lebih murah lagi ada hadalabo gokujyun (agak berbusa dikit),cetaphil murah beli lazada (watsons) ganti simple refreshing gel (beli shopee tanggal kembar) murah hadalabo gokujyun (agak berbusa dikit)

In [98]:
print("Jumlah data relevan:", len(df_relevan))
print(
    "Teks kosong setelah stopword removal:",
    df_relevan["text_no_stopword"].str.strip().eq("").sum()
)

display(
    df_relevan["text_no_stopword"]
    .head(20)
    .to_frame("teks_setelah_stopword")
)

Jumlah data relevan: 207
Teks kosong setelah stopword removal: 0

                                                                                                                                                                                                     teks_setelah_stopword
0                                                                  ak kemarin beli 3 hp shopee aman aman saja. lihat postingan kaya hati2 sih harga diskon beli tanggal kembar tanggal 25, beli mall beli toko hp harganya
3                        ya online diskonannyaa bonusnya juga, tanggal kembar, aplg paylater toko onlinenya, cicilan 0% nya juga. toko fisik jarang benefit itu. kejadian 0 koma sekian persen lah, slalu beli online aman
7                                                                                                              ges nanya shopee tidak event tanggal kembar tanggal 25, tetep freeong? ((nanya dulu, kali tiba2 sale lagi))
8                                          tes kekencangan si jisulife 10 oke sih, 5 tingkatan, ya suaranya emang berisik dibanding jisulife 5. jisulife 5 3 tingkatan angin beli pas tanggal kembar oke banget diskon nya
9                                                                                                                                                                                           diskon tanggal kembar oren 9.9
10                                                                                                                                                tanyaa deh, toko kl diluar payday sale tanggal kembar freeong tidak sih?
13                                                                                                                                            menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir 7 turunan
15                                                               ngenes kemaren haaaaaaaaaa mbak kasirnya tanggal kembar tsubakinya promo (ini superindo) ya kebeli set dicoba duit pen beli ya nunggu tanggal kembar xddd
16  jangan biarin saldo e-wallet kosong! keranjang belanjaan tanggal kembar besok penuh, saldo e-wallet kosong melompong? top up e-wallet favoritmu orderkuota juga, klik langsung masuk, biaya admin hemat ramah kantong!
17                                                                              cetaphil murah beli lazada (watsons) ganti simple refreshing gel (beli shopee tanggal kembar) murah hadalabo gokujyun (agak berbusa dikit)
18                                                 help rt or repost tweet guyss o zonauang optip open titip layout rangka tanggal kembar 10.10 harga spesial special price promo diskon 6k saja!! tanggal 17 oktober yaaa
19                                hidup tuh jangan serius, cepat tua. santai, takut miskin. kerja capek, tidak kerja tidak duit. hemat, godaan. kaya, rebahan mulu. ya allah, maunya hidup menikmati promo tanggal kembar?
20                                                                                     mending beli pb ugreen 20.000mah 310rb,atau 11.11? bayarnya jam 1 ini, bayar nunggu 11.11 ya? kadang tanggal kembar promonya yaudah
21                                                                                                                                                                    tidak pas tanggal kembar biar anniv co dapet diskon?
22                                                                                                                             cetaphil murah kak belinya tanggal kembar pake koin lazada voucher beauty jangan oren mahal
25                                                                                                                                                                              tidak semenit kak 10.500 promo 10.10 kakak
26                                                                                                                                                                                   169 lagi, tidak bonus promo 10.10 kah
27                                                                                                                                                                  maaf kak.. akuu lgi promo 10.10 tanggal 15 sih kak 1 4
28                                                                                                                                                                                             ketinggalan promo 10.10 :")
29                                                                                                                                                          beli toko official tiktoknya jisulife kak, promo 10.10 kemarin

Melakukan stemming dengan Sastrawi

In [99]:
!pip -q install Sastrawi

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def lakukan_stemming(teks):
    if not isinstance(teks, str):
        return ""
    return stemmer.stem(teks)

df_relevan = df_relevan.copy()

df_relevan["stemmed_text"] = (
    df_relevan["text_no_stopword"].apply(lakukan_stemming)
)

display(
    df_relevan[
        ["text_no_stopword", "stemmed_text"]
    ].head(20)
)

,text_no_stopword,stemmed_text
0,"ak kemarin beli 3 hp shopee aman aman saja. lihat postingan kaya hati2 sih harga diskon beli tanggal kembar tanggal 25, beli mall beli toko hp harganya",ak kemarin beli 3 hp shopee aman aman saja lihat postingan kaya hati2 sih harga diskon beli tanggal kembar tanggal 25 beli mall beli toko hp harga
3,"ya online diskonannyaa bonusnya juga, tanggal kembar, aplg paylater toko onlinenya, cicilan 0% nya juga. toko fisik jarang benefit itu. kejadian 0 koma sekian persen lah, slalu beli online aman",ya online diskonannyaa bonus juga tanggal kembar aplg paylater toko onlinenya cicil 0 nya juga toko fisik jarang benefit itu jadi 0 koma sekian persen lah slalu beli online aman
7,"ges nanya shopee tidak event tanggal kembar tanggal 25, tetep freeong? ((nanya dulu, kali tiba2 sale lagi))",ges nanya shopee tidak event tanggal kembar tanggal 25 tetep freeong nanya dulu kali tiba2 sale lagi
8,"tes kekencangan si jisulife 10 oke sih, 5 tingkatan, ya suaranya emang berisik dibanding jisulife 5. jisulife 5 3 tingkatan angin beli pas tanggal kembar oke banget diskon nya",tes kencang si jisulife 10 oke sih 5 tingkat ya suara emang berisik banding jisulife 5 jisulife 5 3 tingkat angin beli pas tanggal kembar oke banget diskon nya
9,diskon tanggal kembar oren 9.9,diskon tanggal kembar oren 9 9
10,"tanyaa deh, toko kl diluar payday sale tanggal kembar freeong tidak sih?",tanyaa deh toko kl luar payday sale tanggal kembar freeong tidak sih
13,"menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir 7 turunan",inisiasi tanggal kembar diskon besar rejekinya ngalir 7 turun
15,ngenes kemaren haaaaaaaaaa mbak kasirnya tanggal kembar tsubakinya promo (ini superindo) ya kebeli set dicoba duit pen beli ya nunggu tanggal kembar xddd,ngenes kemaren haaaaaaaaaa mbak kasir tanggal kembar tsubakinya promo ini superindo ya kebel set coba duit pen beli ya nunggu tanggal kembar xddd
16,"jangan biarin saldo e-wallet kosong! keranjang belanjaan tanggal kembar besok penuh, saldo e-wallet kosong melompong? top up e-wallet favoritmu orderkuota juga, klik langsung masuk, biaya admin hemat ramah kantong!",jangan biarin saldo e-wallet kosong keranjang belanja tanggal kembar besok penuh saldo e-wallet kosong melompong top up e-wallet favorit orderkuota juga klik langsung masuk biaya admin hemat ramah kantong
17,cetaphil murah beli lazada (watsons) ganti simple refreshing gel (beli shopee tanggal kembar) murah hadalabo gokujyun (agak berbusa dikit),cetaphil murah beli lazada watsons ganti simple refreshing gel beli shopee tanggal kembar murah hadalabo gokujyun agak busa dikit
18,help rt or repost tweet guyss o zonauang optip open titip layout rangka tanggal kembar 10.10 harga spesial special price promo diskon 6k saja!! tanggal 17 oktober yaaa,help rt or repost tweet guyss o zonauang optip open titip layout rangka tanggal kembar 10 10 harga spesial special price promo diskon 6k saja tanggal 17 oktober yaaa
19,"hidup tuh jangan serius, cepat tua. santai, takut miskin. kerja capek, tidak kerja tidak duit. hemat, godaan. kaya, rebahan mulu. ya allah, maunya hidup menikmati promo tanggal kembar?",hidup tuh jangan serius cepat tua santai takut miskin kerja capek tidak kerja tidak duit hemat goda kaya rebah mulu ya allah mau hidup nikmat promo tanggal kembar
20,"mending beli pb ugreen 20.000mah 310rb,atau 11.11? bayarnya jam 1 ini, bayar nunggu 11.11 ya? kadang tanggal kembar promonya yaudah",mending beli pb ugreen 20 000mah 310rb atau 11 11 bayar jam 1 ini bayar nunggu 11 11 ya kadang tanggal kembar promonya yaudah
21,tidak pas tanggal kembar biar anniv co dapet diskon?,tidak pas tanggal kembar biar anniv co dapet diskon
22,cetaphil murah kak belinya tanggal kembar pake koin lazada voucher beauty jangan oren mahal,cetaphil murah kak beli tanggal kembar pake koin lazada voucher beauty jangan oren mahal
25,tidak semenit kak 10.500 promo 10.10 kakak,tidak menit kak 10 500 promo 10 10 kakak
26,"169 lagi, tidak bonus promo 10.10 kah",169 lagi tidak bonus promo 10 10 kah
27,maaf kak.. akuu lgi promo 10.10 tanggal 15 sih kak 1 4,maaf kak akuu lgi promo 10 10 tanggal 15 sih kak 1 4
28,"ketinggalan promo 10.10 :"")",tinggal promo 10 10
29,"beli toko official tiktoknya jisulife kak, promo 10.10 kemarin",beli toko official tiktoknya jisulife kak promo 10 10 kemarin

In [100]:
print("Jumlah data:", len(df_relevan))
print(
    "Teks kosong setelah stemming:",
    df_relevan["stemmed_text"].str.strip().eq("").sum()
)

display(
    df_relevan[
        ["original_text", "normalized_text", "stemmed_text"]
    ].head(10)
)

Jumlah data: 207
Teks kosong setelah stemming: 0

,original_text,normalized_text,stemmed_text
0,"@afrkml ak kemarin beli 3 hp di shopee aman aman aja. tapi lihat postingan kaya gini harus hati2 juga sih\n\nsebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik","ak kemarin beli 3 hp di shopee aman aman saja. tapi lihat postingan kaya begini harus hati2 juga sih sebenarnya dapat harga diskon karena beli di tanggal kembar atau tanggal 25, beli di mall atau beli di toko hp harganya naik",ak kemarin beli 3 hp shopee aman aman saja lihat postingan kaya hati2 sih harga diskon beli tanggal kembar tanggal 25 beli mall beli toko hp harga
3,"Ya onlen kan banyak diskonannyaa terus byk bonusnya jg, aplgi tanggal kembar, aplg kalo punya paylater yg dr toko onlinenya, dpt cicilan 0% nya jg. Di toko fisik jarang dpt benefit sebanyk itu. Lg pula itu kejadian jg cm 0 koma sekian persen lah, w slalu beli online dan aman aja","ya online kan banyak diskonannyaa terus banyak bonusnya juga, apalagi tanggal kembar, aplg kalau punya paylater yang dari toko onlinenya, dapat cicilan 0% nya juga. di toko fisik jarang dapat benefit sebanyak itu. lagi pula itu kejadian juga cuma 0 koma sekian persen lah, aku slalu beli online dan aman saja",ya online diskonannyaa bonus juga tanggal kembar aplg paylater toko onlinenya cicil 0 nya juga toko fisik jarang benefit itu jadi 0 koma sekian persen lah slalu beli online aman
7,"Ges mau nanyað\nShopee kalian kalau lagi ga event tanggal kembar atau tanggal 25, tetep bisa freeong?\n\n((Nanya dulu, kali aja tiba2 aku mau sale lagi))","ges mau nanya shopee kalian kalau lagi tidak event tanggal kembar atau tanggal 25, tetep bisa freeong? ((nanya dulu, kali saja tiba2 aku mau sale lagi))",ges nanya shopee tidak event tanggal kembar tanggal 25 tetep freeong nanya dulu kali tiba2 sale lagi
8,"Tes kekencangan si Jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. Tapi jisulife 5 cuma ada 3 tingkatan angin \n\nBeli pas tanggal kembar oke banget diskon nya ð¥° https://t.co/5E17pVy4YR","tes kekencangan si jisulife 10 ini oke sih, ada 5 tingkatan, dan ya dari suaranya emang agak lebih berisik dibanding jisulife 5. tapi jisulife 5 cuma ada 3 tingkatan angin beli pas tanggal kembar oke banget diskon nya",tes kencang si jisulife 10 oke sih 5 tingkat ya suara emang berisik banding jisulife 5 jisulife 5 3 tingkat angin beli pas tanggal kembar oke banget diskon nya
9,@riorkha Diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren dong 9.9,diskon tanggal kembar oren 9 9
10,"@Weist9953 aku ð­âï¸ tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong gak sih?","aku tapi aku mau tanyaa deh, toko kamu kl diluar payday sale sama tanggal kembar bisa freeong tidak sih?",tanyaa deh toko kl luar payday sale tanggal kembar freeong tidak sih
13,"siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampe 7 turunan","siapapun yang menginisiasi tanggal kembar diskon besar-besaran, rejekinya ngalir sampai 7 turunan",inisiasi tanggal kembar diskon besar rejekinya ngalir 7 turun
15,@snowdropnikita KAN NGENES BARU KEMAREN AJA HAAAAAAAAAA\n\nkata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya udah kebeli satu set dicoba dulu ntar kalo ada duit dan pen beli lagi ya nunggu tanggal kembar xDDD,kan ngenes baru kemaren saja haaaaaaaaaa kata mbak kasirnya tiap tanggal kembar tsubakinya promo (ini di superindo) tapi ya sudah kebeli satu set dicoba dulu nanti kalau ada duit dan pen beli lagi ya nunggu tanggal kembar xddd,ngenes kemaren haaaaaaaaaa mbak kasir tanggal kembar tsubakinya promo ini superindo ya kebel set coba duit pen beli ya nunggu tanggal kembar xddd
16,"Jangan Biarin Saldo E-Wallet Kosong!ð­\n\nKeranjang belanjaan tanggal kembar besok udah penuh, tapi saldo e-wallet masih kosong melompong? Top up e-wallet favoritmu di Orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!ðï¸ð https://t.co/VYdb3cw5Zn","jangan biarin saldo e-wallet kosong! keranjang belanjaan tanggal kembar besok sudah penuh, tapi saldo e-wallet masih kosong melompong? top up e-wallet favoritmu di orderkuota sekarang juga, sekali klik langsung masuk, biaya admin paling hemat dan ramah kantong!",jangan biarin saldo e-wallet kosong keranjang belanja tanggal kembar besok penuh saldo e-wallet kosong melompong top up e-wallet favorit orderkuota juga klik langsung masuk biaya admin hemat ramah kantong
17,@usedtob3me Cetaphil bisa murah kalau beli di Lazada (watsons)\nKalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar)\nLebih murah lagi ada hadalabo gokujyun (agak berbusa dikit),cetaphil bisa murah kalau beli di lazada (watsons) kalau mau ganti paling mirip itu simple refreshing gel (beli di shopee tanggal kembar) lebih murah lagi ada hadalabo gokujyun (agak berbusa dikit),cetaphil murah beli lazada watsons ganti simple refreshing gel beli shopee tanggal kembar murah hadalabo gokujyun agak busa dikit

In [101]:
df_relevan.to_csv(
    "data_preprocessing_relevan.csv",
    index=False,
    encoding="utf-8-sig"
)

print("File berhasil disiapkan: data_preprocessing_relevan.csv")

File berhasil disiapkan: data_preprocessing_relevan.csv

In [102]:
from google.colab import files
files.download("data_preprocessing_relevan.csv")