In [1]:
!pip install apify-client pandas

Requirement already satisfied: apify-client in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (3.3.0)
Requirement already satisfied: pandas in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Requirement already satisfied: colorama>=0.4.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from apify-client) (0.4.6)
Requirement already satisfied: impit~=0.14.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from apify-client) (0.14.1)
Requirement already satisfied: more-itertools>=10.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from apify-client) (11.1.0)
Requirement already satisfied: pydantic>=2.11.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pydantic[email]>=2.11.0->apify-client) (2.14.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from apify-client) (4.16.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pydantic>=2.11.0->pydantic[email]>=2.11.0->apify-client) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pydantic>=2.11.0->pydantic[email]>=2.11.0->apify-client) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pydantic>=2.11.0->pydantic[email]>=2.11.0->apify-client) (0.4.4)
Requirement already satisfied: email-validator>=2.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from pydantic[email]>=2.11.0->apify-client) (2.3.0)
Requirement already satisfied: dnspython>=2.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from email-validator>=2.0.0->pydantic[email]>=2.11.0->apify-client) (2.9.0)
Requirement already satisfied: idna>=2.0.0 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from email-validator>=2.0.0->pydantic[email]>=2.11.0->apify-client) (3.20)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from apify_client import ApifyClient
import pandas as pd
from pathlib import Path

# Initialize the ApifyClient with your API token
client = ApifyClient(os.getenv("APIFY_API_TOKEN"))

# Prepare the Actor input
run_input = {
    "filter:blue_verified": False,
    "filter:consumer_video": False,
    "filter:has_engagement": False,
    "filter:hashtags": False,
    "filter:images": False,
    "filter:links": False,
    "filter:media": False,
    "filter:mentions": False,
    "filter:native_video": False,
    "filter:nativeretweets": False,
    "filter:news": False,
    "filter:pro_video": False,
    "filter:quote": False,
    "filter:replies": False,
    "filter:safe": False,
    "filter:spaces": False,
    "filter:twimg": False,
    "filter:videos": False,
    "filter:vine": False,
    "from": "elonmusk",
    "include:nativeretweets": False,
    "lang": "in",
    "maxItems": 7000,
    "searchTerms": [
        "\"tanggal kembar\" lang:id since:2026-06-01 until:2026-10-19",
        "\"promo tanggal kembar\" lang:id since:2026-06-01 until:2026-10-19",
        "(\"promo 6.6\" OR \"promo 7.7\" OR \"diskon 6.6\" OR \"diskon 7.7\") lang:id since:2026-06-01 until:2026-08-01",
        "(\"promo 8.8\" OR \"promo 9.9\" OR \"diskon 8.8\" OR \"diskon 9.9\") lang:id since:2026-08-01 until:2026-10-01",
        "(\"promo 10.10\" OR \"diskon 10.10\" OR \"flash sale 10.10\") lang:id since:2026-10-01 until:2026-10-19",
        "(\"flash sale\" OR \"gratis ongkir\" OR \"voucher belanja\") lang:id since:2026-06-01 until:2026-10-19"
    ],
    "tweetIDs": [
        "1846987139428634858"
    ]
}



# Jalankan Actor Apify
run = client.actor("CJdippxWmn9uRfooo").call(
    run_input=run_input
)



# Ambil ID dataset dari objek Run
dataset_id = run.default_dataset_id

# Ambil hasil scraping dari Apify
items = list(
    client.dataset(dataset_id).iterate_items()
)

# Ubah hasil menjadi DataFrame
df = pd.DataFrame(items)

# Simpan CSV di folder notebook saat ini
output_file = Path("data_tanggal_kembar.csv")

df.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("Scraping selesai!")
print("Jumlah data:", len(df))
print("Jumlah kolom:", len(df.columns))
print("Lokasi file:", output_file.resolve())

# Tampilkan 5 data pertama
display(df.head())

[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> Status: RUNNING, Message:
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:00.702Z ACTOR: Pulling container image of build 4Brk1WofhHkPghqyi from registry.
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:00.709Z ACTOR: Creating container.
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:00.797Z ACTOR: Starting container.
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:00.799Z ACTOR: Running under "LIMITED_PERMISSIONS".
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:06.968Z Actor is running on the Apify platform, `disable_browser_sandbox` was changed to True.
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:06.972Z [apify] INFO  Initializing Actor ({"apify_sdk_version": "3.0.3", "apify_client_version": "2.5.1", "crawlee_version": "1.11.0", "python_version": "3.12.15", "os": "linux"})
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.199Z ACTOR_MAX_PAID_DATASET_ITEMS is : 19984
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.200Z actor_input is :
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.201Z {'filter:blue_verified': False, 'filter:consumer_video': False, 'filter:has_engagement': False, 'filter:hashtags': False, 'filter:images': False, 'filter:links': False, 'filter:media': False, 'filter:mentions': False, 'filter:native_video': False, 'filter:nativeretweets': False, 'filter:news': False, 'filter:pro_video': False, 'filter:quote': False, 'filter:replies': False, 'filter:safe': False, 'filter:spaces': False, 'filter:twimg': False, 'filter:videos': False, 'filter:vine': False, 'from': 'elonmusk', 'include:nativeretweets': False, 'lang': 'in', 'maxItems': 7000, 'searchTerms': ['"tanggal kembar" lang:id since:2026-06-01 until:2026-10-19', '"promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-19', '("promo 6.6" OR "promo 7.7" OR "diskon 6.6" OR "diskon 7.7") lang:id since:2026-06-01 until:2026-08-01', '("promo 8.8" OR "promo 9.9" OR "diskon 8.8" OR "diskon 9.9") lang:id since:2026-08-01 until:2026-10-01', '("promo 10.10" OR "diskon 10.10" OR "flash sale 10.10") lang:id sinc... [line-too-long]
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.201Z apify_token is *********,apify_user_id is 553YzFgJcQS9C1LGa,actor_id is CJdippxWmn9uRfooo,actor_run_id is fYVaMsvhbbqQHarKj
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.252Z [apify] ERROR Failed to get user info, status code: 404
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.253Z username is ,isPaying is -1
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.272Z build_query done ,query is :,tweet_ids is ['1846987139428634858']. searchTerms is None
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.693Z get_tweet_by_id:response.json() is {'data': {'tweet_results': {'rest_id': '1846987139428634858', 'result': {'__typename': 'TweetUnavailable', 'unavailable_reason': 'Suspended'}}}}
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.695Z Fetched 1 valid tweets out of 1 requests in 0.4117708206176758 seconds
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:07.784Z mock_tweets's len is 14
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:10.827Z log fail error
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> 2026-10-20T00:41:10.827Z [apify] INFO  Exiting Actor ({"exit_code": 0})
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:fYVaMsvhbbqQHarKj] -> Status: SUCCEEDED, Message:

Scraping selesai!
Jumlah data: 15
Jumlah kolom: 30
Lokasi file: C:\Scraping data tgl kembar\data_tanggal_kembar.csv

,type,id,url,twitterUrl,text,source,retweetCount,replyCount,likeCount,quoteCount,...,author,extendedEntities,card,place,entities,isRetweet,isQuote,isConversationControlled,quoted_tweet,retweeted_tweet
0,tweet,,,,,,0.0,0.0,0.0,0.0,...,{},{},{},{},{},False,False,False,NaN,NaN
1,mock_tweet,-1,NaN,NaN,"From KaitoEasyAPI, a reminder:Our API pricing ...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mock_tweet,-1,NaN,NaN,"From KaitoEasyAPI, a reminder:Our API pricing ...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mock_tweet,-1,NaN,NaN,"From KaitoEasyAPI, a reminder:Our API pricing ...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mock_tweet,-1,NaN,NaN,"From KaitoEasyAPI, a reminder:Our API pricing ...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:

import pandas as pd
from pathlib import Path
from apify_client import ApifyClient

# ==========================================
# 1. KONFIGURASI
# ==========================================

APIFY_TOKEN = ApifyClient(os.getenv("APIFY_API_TOKEN"))

ACTOR_ID = "CJdippxWmn9uRfooo"

OUTPUT_FILE = Path("data_tanggal_kembar.csv")

TARGET_DATA = 3000

client = ApifyClient(APIFY_TOKEN)

# ==========================================
# 2. KATA KUNCI PENCARIAN
# ==========================================

search_terms = [
    '"tanggal kembar" lang:id since:2026-06-01 until:2026-10-21',
    '"promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-21',
    '"diskon tanggal kembar" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 6.6" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 7.7" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 8.8" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 9.9" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 10.10" lang:id since:2026-10-01 until:2026-10-21',
    '"flash sale" lang:id since:2026-06-01 until:2026-10-21',
    '"gratis ongkir" lang:id since:2026-06-01 until:2026-10-21',
    '"voucher belanja" lang:id since:2026-06-01 until:2026-10-21'
]

# ==========================================
# 3. CEK INPUT ACTOR
# ==========================================
# Penting:
# Struktur input setiap Actor bisa berbeda.
# Ambil schema dari Console Apify untuk memastikan
# nama parameter searchTerms dan maxItems benar.

# Periksa Actor Apify
actor = client.actor(ACTOR_ID)

actor_details = actor.get()

print("Actor ID:", ACTOR_ID)
print("Detail Actor:")
print(actor_details)
print("Kata kunci disiapkan:", len(search_terms))
print("Target data:", TARGET_DATA)

print("\nPeriksa dahulu Input Schema Actor di Apify Console.")
print("Jangan menjalankan scraping sebelum nama parameter")
print("pencarian dan batas item dipastikan benar.")

Actor ID: CJdippxWmn9uRfooo
Detail Actor:
id='CJdippxWmn9uRfooo' user_id='IXuNT7FWLw9TjPPu8' name='twitter-x-data-tweet-scraper-pay-per-result-cheapest' username='kaitoeasyapi' description='Only $0.18/1000 tweets for Twitter scraping,  100% reliability, swift data retrieval.This incredible low price is almost too good to be true.Thanks to our large-scale operations and efficient servers, we can offer you rock-bottom prices that no competitors can match.' restart_on_error=None is_public=True actor_permission_level='LIMITED_PERMISSIONS' created_at=datetime.datetime(2024, 10, 14, 16, 20, 36, 738000, tzinfo=TzInfo(0)) modified_at=datetime.datetime(2026, 10, 19, 7, 57, 0, 186000, tzinfo=TzInfo(0)) stats=ActorStats(total_builds=606, total_runs=50632262, total_users=33596, total_users7_days=2580, total_users30_days=4932, total_users90_days=7840, total_metamorphs=None, last_run_started_at=datetime.datetime(2026, 10, 20, 0, 50, 8, 15000, tzinfo=TzInfo(0)), actor_review_count=86, actor_review_rating=4.332717346322648, bookmark_count=425, public_actor_run_stats30_days=PublicActorRunStats30Days(aborted=42593, failed=59, succeeded=2669047, timed_out=4889, total=2716588)) versions=[Version(version_number='0.0', source_type='SOURCE_FILES', env_vars=None, apply_env_vars_to_build=None, build_tag=None, source_files=None, git_repo_url=None, tarball_url=None, github_gist_url=None), Version(version_number='0.1', source_type='SOURCE_FILES', env_vars=None, apply_env_vars_to_build=None, build_tag=None, source_files=None, git_repo_url=None, tarball_url=None, github_gist_url=None), Version(version_number='1.0', source_type='SOURCE_FILES', env_vars=None, apply_env_vars_to_build=None, build_tag='latest0225', source_files=None, git_repo_url=None, tarball_url=None, github_gist_url=None)] pricing_infos=[PricePerDatasetItemActorPricingInfo(apify_margin_percentage=0.2, created_at=datetime.datetime(2024, 10, 15, 12, 1, 28, 330000, tzinfo=TzInfo(0)), started_at=datetime.datetime(2024, 10, 15, 12, 1, 28, 330000, tzinfo=TzInfo(0)), notified_about_future_change_at=None, notified_about_change_at=datetime.datetime(2024, 10, 15, 14, 9, 17, 796000, tzinfo=TzInfo(0)), reason_for_change='Introducing our new actor at a highly competitive price. We aim to provide top-quality services at the lowest cost. Enjoy superior web scraping and automation tools without breaking the bank.', is_price_change_notification_suppressed=None, force_contains_significant_price_change=None, pricing_model='PRICE_PER_DATASET_ITEM', unit_name='Tweet', price_per_unit_usd=0.00025, tiered_pricing=None), PayPerEventActorPricingInfo(apify_margin_percentage=0.2, created_at=datetime.datetime(2026, 3, 3, 15, 7, 42, 724000, tzinfo=TzInfo(0)), started_at=datetime.datetime(2026, 3, 3, 15, 7, 42, 724000, tzinfo=TzInfo(0)), notified_about_future_change_at=None, notified_about_change_at=None, reason_for_change='Migration from Pay Per Result to Pay Per Event with apify-default-dataset-item event', is_price_change_notification_suppressed=True, force_contains_significant_price_change=False, pricing_model='PAY_PER_EVENT', pricing_per_event=PricingPerEvent(actor_charge_events={'apify-default-dataset-item': ActorChargeEvent(event_title='tweet', event_description='Single tweet in the default dataset.', event_price_usd=0.00025, event_tiered_pricing_usd=None, is_primary_event=True, is_one_time_event=None)}), minimal_max_total_charge_usd=None), PayPerEventActorPricingInfo(apify_margin_percentage=0.2, created_at=datetime.datetime(2026, 5, 22, 13, 2, 58, 617000, tzinfo=TzInfo(0)), started_at=datetime.datetime(2026, 6, 5, 13, 2, 57, 450000, tzinfo=TzInfo(0)), notified_about_future_change_at=datetime.datetime(2026, 5, 22, 13, 3, 34, 816000, tzinfo=TzInfo(0)), notified_about_change_at=None, reason_for_change='New: automatic volume discounts! No price increase—standard rate unchanged. Higher Apify plans now save up to 28%, down to $0.18 per 1K tweets. Discounts apply automatically. Happy scraping!', is_price_change_notification_suppressed=False, force_contains_significant_price_change=None, pricing_model='PAY_PER_EVENT', pricing_per_event=PricingPerEvent(actor_charge_events={'apify-default-dataset-item': ActorChargeEvent(event_title='tweet', event_description='Single tweet in the default dataset.', event_price_usd=None, event_tiered_pricing_usd={'FREE': TieredPricingPerEventEntry(tiered_event_price_usd=0.00025), 'BRONZE': TieredPricingPerEventEntry(tiered_event_price_usd=0.00022), 'GOLD': TieredPricingPerEventEntry(tiered_event_price_usd=0.00018), 'PLATINUM': TieredPricingPerEventEntry(tiered_event_price_usd=0.00018), 'DIAMOND': TieredPricingPerEventEntry(tiered_event_price_usd=0.00018), 'SILVER': TieredPricingPerEventEntry(tiered_event_price_usd=0.0002)}, is_primary_event=True, is_one_time_event=False)}), minimal_max_total_charge_usd=None)] default_run_options=DefaultRunOptions(build='latest0225', timeout_secs=0, memory_mbytes=256, restart_on_error=None, max_items=None, force_permission_level=None, maxTotalChargeUsd=None) example_run_input=ExampleRunInput(body='{ "helloWorld": 123 }', content_type='application/json; charset=utf-8') is_deprecated=False deployment_key='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkw0QzhhKXaY3SccodhfA/parhWFRU7WJccV7FKRJzCsvMjAllV7HlYXsrEK0W7H5P5WAqNuR022wM9XVn4+OKKts3M4SpVseHu4dxMZbCTXJn9kyYn0pt2PBaWkoaWcV3x2it56TusSJ2m7DSDTXKp1DOamep5135epKcMa2PVvQxfxHdRvkoaX8xgoDvaNNhMk+t6sxSEBM9c3Ka0PVB1QF2yLaXbShvbs/OJS+g1CFJMkPBonkukjHeA4iO9xtPOgFtBWFn7obOga2TrrYBZ7Cu69tjnS2I++VwkPxgRaA+fscgK+QgAFJf9+JyDLDm94eW1O531C7iByJlEl/b \n' title='Tweet Scraper|$0.18/1K Tweets | Pay-Per Result | No Rate Limits' tagged_builds={'latest': TaggedBuildInfo(build_id='xnR5xNQIZkk8zqw8N', build_number='0.0.68', build_number_int=68, finished_at=datetime.datetime(2024, 11, 12, 19, 50, 31, 288000, tzinfo=TzInfo(0))), 'latest0225': TaggedBuildInfo(build_id='4Brk1WofhHkPghqyi', build_number='1.0.522', build_number_int=10000522, finished_at=datetime.datetime(2026, 10, 19, 7, 57, 0, 186000, tzinfo=TzInfo(0)))} actor_standby=None readme_summary='## RealTime Twitter Data Scraper API\n\nA real-time X platform tweet data extraction Actor that collects and structures tweet content, author profile metadata, engagement metrics, media and link assets, geo and timestamp information, conversation threading, and network-related signals for large-scale social data analysis. The Actor exposes advanced filtering and query capabilities to target tweets by attributes and returns structured, machine-readable records suitable for analytics, sentiment and trend detection, audience profiling, media analysis, and network mapping. Technical capabilities include high-throughput ingestion, real-time capture, rich per-tweet attributes (engagement counts, language, timestamps, media and link details), comprehensive author metadata, timeline and historical context, and outputs optimized for downstream analytics and machine learning workflows.\n\n## Use cases\n\n- Competitive intelligence and market-shift prediction using tweet-level signals and trend trajectories  \n- Market research and audience insight generation from aggregated engagement and profile data  \n- Influencer and micro-influencer discovery by analyzing engagement patterns and profile metrics  \n- Predictive modeling and sentiment analysis for early trend detection and forecasting  \n- Audience segmentation and lookalike modeling based on behavioral and network signals  \n- Content optimization and timing strategies using engagement velocity and resonance metrics  \n- Network intelligence: mapping follower/following relationships and influence pathways  \n- Campaign intelligence and performance marketing: building audiences, attribution modeling, and CAC projections  \n- Brand intelligence and reputation monitoring via sentiment and engagement trends  \n- Risk monitoring and early-warning systems for reputation or crisis detection  \n- Lead and pipeline generation using intent and engagement signals from social activity  \n- Research and academic studies of social behavior, timelines, and multimedia diffusion  \n- Partnership and opportunity discovery through network overlap and influence scoring' seo_title='Cheapest Twitter Scraper | $0.25 per 1000 Tweets' seo_description='Most affordable Twitter scraping API: Just $0.25/1000 tweets! Lightning-fast speed (150/sec), real-time data, and 99.9% uptime. Best price guaranteed.' picture_url='https://apify-image-uploads-prod.s3.us-east-1.amazonaws.com/CJdippxWmn9uRfooo/SiVFfg8fLbxTTQPyE-218163ba66142ac0a16e40ecb48114da.jpeg' standby_url=None notice=<ActorNotice.NONE: 'NONE'> categories=['SOCIAL_MEDIA', 'LEAD_GENERATION'] is_critical=False is_generic=False is_source_code_hidden=True has_no_dataset=False
Kata kunci disiapkan: 11
Target data: 3000

Periksa dahulu Input Schema Actor di Apify Console.
Jangan menjalankan scraping sebelum nama parameter
pencarian dan batas item dipastikan benar.

In [ ]:
import pandas as pd
from pathlib import Path
from apify_client import ApifyClient

# Koneksi ke Apify
APIFY_TOKEN = (APIFY_TOKEN)
ACTOR_ID = "CJdippxWmn9uRfooo"

client = load_dotenv()
client = ApifyClient(os.getenv("APIFY_API_TOKEN"))

# Kata kunci pencarian
search_terms = [
    '"tanggal kembar" lang:id since:2026-06-01 until:2026-10-21',
    '"promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-21',
    '"diskon tanggal kembar" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 6.6" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 7.7" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 8.8" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 9.9" lang:id since:2026-06-01 until:2026-10-21',
    '"promo 10.10" lang:id since:2026-10-01 until:2026-10-21',
    '"flash sale" lang:id since:2026-06-01 until:2026-10-21',
    '"gratis ongkir" lang:id since:2026-06-01 until:2026-10-21',
    '"voucher belanja" lang:id since:2026-06-01 until:2026-10-21'
]

# Input scraping
run_input = {
    "searchTerms": search_terms,
    "maxItems": 7000
}

# Jalankan Actor
run = client.actor(ACTOR_ID).call(run_input=run_input)
# Tampilkan status dan ID dataset
print("Status scraping:", run.status)
print("ID dataset:", run.default_dataset_id)

print("Status scraping:", run.status)
print("ID dataset:", run.default_dataset_id)

[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> Status: RUNNING, Message:
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:14.080Z ACTOR: Pulling container image of build 4Brk1WofhHkPghqyi from registry.
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:14.082Z ACTOR: Creating container.
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:14.182Z ACTOR: Starting container.
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:14.191Z ACTOR: Running under "LIMITED_PERMISSIONS".
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.727Z Actor is running on the Apify platform, `disable_browser_sandbox` was changed to True.
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.729Z [apify] INFO  Initializing Actor ({"apify_sdk_version": "3.0.3", "apify_client_version": "2.5.1", "crawlee_version": "1.11.0", "python_version": "3.12.15", "os": "linux"})
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.923Z ACTOR_MAX_PAID_DATASET_ITEMS is : 19480
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.924Z actor_input is :
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.926Z {'searchTerms': ['"tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', '"promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', '"diskon tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', '"promo 6.6" lang:id since:2026-06-01 until:2026-10-21', '"promo 7.7" lang:id since:2026-06-01 until:2026-10-21', '"promo 8.8" lang:id since:2026-06-01 until:2026-10-21', '"promo 9.9" lang:id since:2026-06-01 until:2026-10-21', '"promo 10.10" lang:id since:2026-10-01 until:2026-10-21', '"flash sale" lang:id since:2026-06-01 until:2026-10-21', '"gratis ongkir" lang:id since:2026-06-01 until:2026-10-21', '"voucher belanja" lang:id since:2026-06-01 until:2026-10-21'], 'maxItems': 7000, 'queryType': 'Latest', 'filter:blue_verified': False, 'filter:nativeretweets': False, 'include:nativeretweets': False, 'filter:replies': False, 'filter:quote': False, 'filter:has_engagement': False, 'min_retweets': 0, 'min_faves': 0, 'min_replies': 0, '-min_retweets': 0, '-min_faves': 0, '-min_repli... [line-too-long]
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.927Z apify_token is *********,apify_user_id is 553YzFgJcQS9C1LGa,actor_id is CJdippxWmn9uRfooo,actor_run_id is 5f98CmZq0jFIEYfW8
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.950Z [apify] ERROR Failed to get user info, status code: 404
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.952Z username is ,isPaying is -1
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.960Z build_query done ,query is :,tweet_ids is None. searchTerms is ['"tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', '"promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', '"diskon tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', '"promo 6.6" lang:id since:2026-06-01 until:2026-10-21', '"promo 7.7" lang:id since:2026-06-01 until:2026-10-21', '"promo 8.8" lang:id since:2026-06-01 until:2026-10-21', '"promo 9.9" lang:id since:2026-06-01 until:2026-10-21', '"promo 10.10" lang:id since:2026-10-01 until:2026-10-21', '"flash sale" lang:id since:2026-06-01 until:2026-10-21', '"gratis ongkir" lang:id since:2026-06-01 until:2026-10-21', '"voucher belanja" lang:id since:2026-06-01 until:2026-10-21']
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.962Z searchTerms is not none.will search by searchTerms:['"tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', '"promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', '"diskon tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', '"promo 6.6" lang:id since:2026-06-01 until:2026-10-21', '"promo 7.7" lang:id since:2026-06-01 until:2026-10-21', '"promo 8.8" lang:id since:2026-06-01 until:2026-10-21', '"promo 9.9" lang:id since:2026-06-01 until:2026-10-21', '"promo 10.10" lang:id since:2026-10-01 until:2026-10-21', '"flash sale" lang:id since:2026-06-01 until:2026-10-21', '"gratis ongkir" lang:id since:2026-06-01 until:2026-10-21', '"voucher belanja" lang:id since:2026-06-01 until:2026-10-21']
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:20.964Z begin search twitter's api querystring is {'q': '"tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', 'type': 'Latest', 'count': 20}
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:21.442Z advanced_search_tweets redirect ,invoke api success ,cost time: 482.457 milliseconds
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:21.444Z {"data":{"search_by_raw_query":{"id":"U2VhcmNoUXVlcnk6InRhbmdnYWwga2VtYmFyIiBsYW5nOmlkIHNpbmNlOjIwMjYtMDYtMDEgdW50aWw6MjAyNi0xMC0yMQ==","rest_id":"\"tanggal kembar\" lang:id since:2026-06-01 until:2026-10-21","search_timeline":{"id":"VGltZWxpbmU6DAB+CwABAAAAOiJ0YW5nZ2FsIGtlbWJhciIgbGFuZzppZCBzaW5jZToyMDI2LTA2LTAxIHVudGlsOjIwMjYtMTAtMjEIAAIAAAABAAA=","timeline":{"id":"LatestTabSrpProduct-Timeline","instructions":[{"__typename":"TimelineAddEntries","entries":[{"content":{"__typename":"TimelineTimelineItem","client_event_info":{"component":"latest_nightowl_recency","details":{"timelines_details":{"controller_data":"DAACDAAFDAABDAABDAABCgABAAAAAEAAAAAAAAwAAgoAAQAAAAAAAAABCgACC0HX5c9ryjwKAAVaarR9hoYUxAgABgAAAAEKAAd5e6iSHJwwjwoACAAAAaFW0e8OAAAAAAA="}},"element":"tweet"},"content":{"__typename":"TimelineTweet","highlights":{"text_highlights":[{"end_index":166,"start_index":152}]},"timeline_tweet_display_type":"Tweet","tweet_results":{"rest_id":"2110049779162153142","result":{"__typename":"Tweet",... [line-too-long]
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:21.446Z e_count":0,"reply_count":0,"retweet_count":0,"retweeted":false,"user_id_str":"2062436860300083200"},"rest_id":"2109925742343839766","unmention_data":{"id":"VW5tZW50aW9uczoKAAEdR\/ZIpttgFg8AAgoAAAAAAA=="},"view_count_info":{"count":"97","state":"EnabledWithCount"}}}}},"entry_id":"tweet-2109925742343839766","sort_index":"2112347907473539059"},{"content":{"__typename":"TimelineTimelineItem","client_event_info":{"component":"latest_nightowl_recency","details":{"timelines_details":{"controller_data":"DAACDAAFDAABDAABDAABCgABAAAAAEAAAAAAAAwAAgoAAQAAAAAAAAABCgACC0HX5c9ryjwKAAVaarR9hoYUxAgABgAAAAEKAAd5e6iSHJwwjwoACAAAAaFW0e8OAAAAAAA="}},"element":"tweet"},"content":{"__typename":"TimelineTweet","highlights":{"text_highlights":[{"end_index":64,"start_index":50}]},"timeline_tweet_display_type":"Tweet","tweet_results":{"rest_id":"2109922315643580669","result":{"__typename":"Tweet","core":{"user_results":{"rest_id":"3064341332","result":{"__typename":"User","action_counts":{"favorites_count":5084},"av... [line-too-long]
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:21.570Z begin search twitter's api querystring is {'q': '"tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', 'type': 'Latest', 'count': 20, 'cursor': 'DAADDAABCgABHUhnGDlaALYKAAIdR8HFOptQTgAIAAIAAAACCAADAAAAAAgABAAAAAAKAAUdUJE66wAnEAoABh1QkTrq_9jwCwAHAAAA8EVtUEM2d0FBQWZRL2dHSk4wdkdwL0FBQUFCUWRSL2tIYWRzQUZ4MUlaeGc1V2dDMkhVZ2M0ajhhWVlRZFIrR2lCOXJnangxSVBmdFZteEVsSFVnY3pMOGFNT1VkU0J0Q2o5dXgraDFJWEJXVDJ0RU1IVWYyU0tiYllCWWRTRnZKRU5keFlSMUh3Y1U2bTFCT0hVZzU3K0thb004ZFNBMFJ1Qm9oaFIxSVEyZ2lHb0J2SFVmVjd3YmIwRUVkUi9NcXo1cncvUjFJQWE4dG1sQW9IVWZlTXdyYmdiRWRTQzlzelp2Uk1oMUg0K1VaMjVEVQAA'}
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.028Z advanced_search_tweets redirect ,invoke api success ,cost time: 458.079 milliseconds
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.030Z {"data":{"search_by_raw_query":{"id":"U2VhcmNoUXVlcnk6InRhbmdnYWwga2VtYmFyIiBsYW5nOmlkIHNpbmNlOjIwMjYtMDYtMDEgdW50aWw6MjAyNi0xMC0yMQ==","rest_id":"\"tanggal kembar\" lang:id since:2026-06-01 until:2026-10-21","search_timeline":{"id":"VGltZWxpbmU6DAB+CwABAAAAOiJ0YW5nZ2FsIGtlbWJhciIgbGFuZzppZCBzaW5jZToyMDI2LTA2LTAxIHVudGlsOjIwMjYtMTAtMjEIAAIAAAABAAA=","timeline":{"id":"LatestTabSrpProduct-Timeline","instructions":[{"__typename":"TimelineAddEntries","entries":[{"content":{"__typename":"TimelineTimelineItem","client_event_info":{"component":"latest_nightowl_recency","details":{"timelines_details":{"controller_data":"DAACDAAFDAABDAABDAABCgABAAAAAEAAAAAAAAwAAgoAAQAAAAAAAAABCgACTu4nssc94CAKAAUOClAbDu+\/0ggABgAAAAEKAAfD5FFNpAelCAoACAAAAaFW0fFoAAAAAAA="}},"element":"tweet"},"content":{"__typename":"TimelineTweet","highlights":{"text_highlights":[{"end_index":155,"start_index":141}]},"timeline_tweet_display_type":"Tweet","tweet_results":{"rest_id":"2109865827751370820","result":{"__typename":"Tweet"... [line-too-long]
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.060Z begin search twitter's api querystring is {'q': '"tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', 'type': 'Latest', 'count': 20, 'cursor': 'DAADDAABCgABHUhnGDlaALYKAAIdR49BilvARgAIAAIAAAACCAADAAAAAAgABAAAAAEKAAUdUJE66wAnEAoABh1QkTrq_7HgCwAHAAABKEVtUEM2d0FBQWZRL2dHSk4wdkdwL0FBQUFCa2RSL2tIYWRzQUZ4MUlIT0kvR21HRUhVZS95ckxiSUVRZFNEMzdWWnNSSlIxSHRRUE1HaUJHSFVnY3pMOGFNT1VkU0J0Q2o5dXgraDFJWEJXVDJ0RU1IVWUrNDJMYUVJY2RTRnZKRU5keFlSMUh3Y1U2bTFCT0hVZzU3K0thb004ZFNBMFJ1Qm9oaFIxSGowR0tXOEJHSFVmVjd3YmIwRUVkUi9NcXo1cncvUjFJTDJ6Tm05RXlIVWhuR0RsYUFMWWRSK0dpQjlyZ2p4MUg5a2ltMjJBV0hVaERhQ0lhZ0c4ZFNBR3ZMWnBRS0IxSDNqTUsyNEd4SFVmajVSbmJrTlFkUjV0d1Yxb2dDdz09AAA'}
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.199Z advanced_search_tweets redirect ,invoke api success ,cost time: 136.514 milliseconds
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.201Z {"data":{"search_by_raw_query":{"id":"U2VhcmNoUXVlcnk6InRhbmdnYWwga2VtYmFyIiBsYW5nOmlkIHNpbmNlOjIwMjYtMDYtMDEgdW50aWw6MjAyNi0xMC0yMQ==","rest_id":"\"tanggal kembar\" lang:id since:2026-06-01 until:2026-10-21","search_timeline":{"id":"VGltZWxpbmU6DAB+CwABAAAAOiJ0YW5nZ2FsIGtlbWJhciIgbGFuZzppZCBzaW5jZToyMDI2LTA2LTAxIHVudGlsOjIwMjYtMTAtMjEIAAIAAAABAAA=","timeline":{"id":"LatestTabSrpProduct-Timeline","instructions":[{"__typename":"TimelineReplaceEntry","entry":{"content":{"__typename":"TimelineTimelineCursor","cursor_type":"Top","value":"DAADDAABCgABHUhnGDlaALYKAAIdR49BilvARgAIAAIAAAABCAADAAAAAAgABAAAAAIKAAUdUJE66wAnEAoABh1QkTrq_4rQCwAHAAABKEVtUEM2d0FBQWZRL2dHSk4wdkdwL0FBQUFCa2RSL2tIYWRzQUZ4MUlIT0kvR21HRUhVZS95ckxiSUVRZFNEMzdWWnNSSlIxSHRRUE1HaUJHSFVnY3pMOGFNT1VkU0J0Q2o5dXgraDFJWEJXVDJ0RU1IVWUrNDJMYUVJY2RTRnZKRU5keFlSMUh3Y1U2bTFCT0hVZzU3K0thb004ZFNBMFJ1Qm9oaFIxSGowR0tXOEJHSFVmVjd3YmIwRUVkUi9NcXo1cncvUjFJTDJ6Tm05RXlIVWhuR0RsYUFMWWRSK0dpQjlyZ2p4MUg5a2ltMjJBV0hVaERhQ0lhZ0c4ZFNBR3ZMWnBRS0IxSDNqTUsy... [line-too-long]
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.203Z has_TimelineAddEntries_in_instructions or no cursor,will break.query is "tanggal kembar" lang:id since:2026-06-01 until:2026-10-21,cursor is DAADDAABCgABHUhnGDlaALYKAAIdR49BilvARgAIAAIAAAACCAADAAAAAAgABAAAAAIKAAUdUJE66wAnEAoABh1QkTrq_4rQCwAHAAABKEVtUEM2d0FBQWZRL2dHSk4wdkdwL0FBQUFCa2RSL2tIYWRzQUZ4MUlIT0kvR21HRUhVZS95ckxiSUVRZFNEMzdWWnNSSlIxSHRRUE1HaUJHSFVnY3pMOGFNT1VkU0J0Q2o5dXgraDFJWEJXVDJ0RU1IVWUrNDJMYUVJY2RTRnZKRU5keFlSMUh3Y1U2bTFCT0hVZzU3K0thb004ZFNBMFJ1Qm9oaFIxSGowR0tXOEJHSFVmVjd3YmIwRUVkUi9NcXo1cncvUjFJTDJ6Tm05RXlIVWhuR0RsYUFMWWRSK0dpQjlyZ2p4MUg5a2ltMjJBV0hVaERhQ0lhZ0c4ZFNBR3ZMWnBRS0IxSDNqTUsyNEd4SFVmajVSbmJrTlFkUjV0d1Yxb2dDdz09AAA
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.205Z begin search twitter's api querystring is {'q': '"promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', 'type': 'Latest', 'count': 20}
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.412Z advanced_search_tweets redirect ,invoke api success ,cost time: 214.831 milliseconds
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.416Z {"data":{"search_by_raw_query":{"id":"U2VhcmNoUXVlcnk6InByb21vIHRhbmdnYWwga2VtYmFyIiBsYW5nOmlkIHNpbmNlOjIwMjYtMDYtMDEgdW50aWw6MjAyNi0xMC0yMQ==","rest_id":"\"promo tanggal kembar\" lang:id since:2026-06-01 until:2026-10-21","search_timeline":{"id":"VGltZWxpbmU6DAB+CwABAAAAQCJwcm9tbyB0YW5nZ2FsIGtlbWJhciIgbGFuZzppZCBzaW5jZToyMDI2LTA2LTAxIHVudGlsOjIwMjYtMTAtMjEIAAIAAAABAAA=","timeline":{"id":"LatestTabSrpProduct-Timeline","instructions":[{"__typename":"TimelineAddEntries","entries":[{"content":{"__typename":"TimelineTimelineItem","client_event_info":{"component":"latest_nightowl_recency","details":{"timelines_details":{"controller_data":"DAACDAAFDAABDAABDAABCgABAAAAAEAAAAAAAAwAAgoAAQAAAAAAAAABCgACG5hx7Vb2J44KAAVtYjoNnLzxlwgABgAAAAEKAAcrJGyBhlw3GgoACAAAAaFW0fNcAAAAAAA="}},"element":"tweet"},"content":{"__typename":"TimelineTweet","highlights":{"text_highlights":[{"end_index":274,"start_index":254}]},"timeline_tweet_display_type":"Tweet","tweet_results":{"rest_id":"2109868003282341966","result":... [line-too-long]
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.468Z begin search twitter's api querystring is {'q': '"promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', 'type': 'Latest', 'count': 20, 'cursor': 'DAADDAABCgABHUfBxTqbUE4KAAIdR8HFOptQTgAIAAIAAAACCAADAAAAAAgABAAAAAAKAAUdUJE774AnEAoABh1QkTvvf9jwCwAHAAAAKEVtUEM2d0FBQWZRL2dHSk4wdkdwL0FBQUFBRWRSOEhGT3B0UVRnPT0AAA'}
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.582Z advanced_search_tweets redirect ,invoke api success ,cost time: 111.195 milliseconds
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.583Z {"data":{"search_by_raw_query":{"id":"U2VhcmNoUXVlcnk6InByb21vIHRhbmdnYWwga2VtYmFyIiBsYW5nOmlkIHNpbmNlOjIwMjYtMDYtMDEgdW50aWw6MjAyNi0xMC0yMQ==","rest_id":"\"promo tanggal kembar\" lang:id since:2026-06-01 until:2026-10-21","search_timeline":{"id":"VGltZWxpbmU6DAB+CwABAAAAQCJwcm9tbyB0YW5nZ2FsIGtlbWJhciIgbGFuZzppZCBzaW5jZToyMDI2LTA2LTAxIHVudGlsOjIwMjYtMTAtMjEIAAIAAAABAAA=","timeline":{"id":"LatestTabSrpProduct-Timeline","instructions":[{"__typename":"TimelineReplaceEntry","entry":{"content":{"__typename":"TimelineTimelineCursor","cursor_type":"Top","value":"DAADDAABCgABHUfBxTqbUE4KAAIdR8HFOptQTgAIAAIAAAABCAADAAAAAAgABAAAAAEKAAUdUJE774AnEAoABh1QkTvvf7HgCwAHAAAAKEVtUEM2d0FBQWZRL2dHSk4wdkdwL0FBQUFBRWRSOEhGT3B0UVRnPT0AAA"},"entry_id":"cursor-top-9223372036854775807","sort_index":"9223372036854775807"},"entry_id_to_replace":"cursor-top-9223372036854775807"},{"__typename":"TimelineReplaceEntry","entry":{"content":{"__typename":"TimelineTimelineCursor","cursor_type":"Bottom","value":"DAADDAABCgABHU... [line-too-long]
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.585Z has_TimelineAddEntries_in_instructions or no cursor,will break.query is "promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-21,cursor is DAADDAABCgABHUfBxTqbUE4KAAIdR8HFOptQTgAIAAIAAAACCAADAAAAAAgABAAAAAEKAAUdUJE774AnEAoABh1QkTvvf7HgCwAHAAAAKEVtUEM2d0FBQWZRL2dHSk4wdkdwL0FBQUFBRWRSOEhGT3B0UVRnPT0AAA
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.587Z begin search twitter's api querystring is {'q': '"diskon tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', 'type': 'Latest', 'count': 20}
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.897Z advanced_search_tweets redirect ,invoke api success ,cost time: 317.439 milliseconds
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.899Z {"data":{"search_by_raw_query":{"id":"U2VhcmNoUXVlcnk6ImRpc2tvbiB0YW5nZ2FsIGtlbWJhciIgbGFuZzppZCBzaW5jZToyMDI2LTA2LTAxIHVudGlsOjIwMjYtMTAtMjE=","rest_id":"\"diskon tanggal kembar\" lang:id since:2026-06-01 until:2026-10-21","search_timeline":{"id":"VGltZWxpbmU6DAB+CwABAAAAQSJkaXNrb24gdGFuZ2dhbCBrZW1iYXIiIGxhbmc6aWQgc2luY2U6MjAyNi0wNi0wMSB1bnRpbDoyMDI2LTEwLTIxCAACAAAAAQAA","timeline":{"id":"LatestTabSrpProduct-Timeline","instructions":[{"__typename":"TimelineAddEntries","entries":[{"content":{"__typename":"TimelineTimelineItem","client_event_info":{"component":"latest_nightowl_recency","details":{"timelines_details":{"controller_data":"DAACDAAFDAABDAABDAABCgABAAAAAEAAAAAAAAwAAgoAAQAAAAAAAAABCgACqyz+HskgaucKAAVRHHWnqpKGGAgABgAAAAEKAAfln7H25vUjRwoACAAAAaFW0fU4AAAAAAA="}},"element":"tweet"},"content":{"__typename":"TimelineTweet","highlights":{"text_highlights":[{"end_index":30,"start_index":9}]},"timeline_tweet_display_type":"Tweet","tweet_results":{"rest_id":"2109966398118408698","result":{"... [line-too-long]
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:22.922Z begin search twitter's api querystring is {'q': '"diskon tanggal kembar" lang:id since:2026-06-01 until:2026-10-21', 'type': 'Latest', 'count': 20, 'cursor': 'DAADDAABCgABHUgbQo_bsfoKAAIdSBtCj9ux-gAIAAIAAAACCAADAAAAAAgABAAAAAAKAAUdUJE8YQAnEAoABh1QkTxg_9jwCwAHAAAAKEVtUEM2d0FBQWZRL2dHSk4wdkdwL0FBQUFBRWRTQnRDajl1eCtnPT0AAA'}
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:23.048Z advanced_search_tweets redirect ,invoke api success ,cost time: 125.127 milliseconds
[apify.twitter-x-data-tweet-scraper-pay-per-result-cheapest runId:5f98CmZq0jFIEYfW8] -> 2026-10-20T00:59:23.049Z {"data":{"search_by_raw_query":{"id":"U2VhcmNoUXVlcnk6ImRpc2tvbiB0YW5nZ2FsIGtlbWJhciIgbGFuZzppZCBzaW5jZToyMDI2LTA2LTAxIHVudGlsOjIwMjYtMTAtMjE=","rest_id":"\"diskon tanggal kembar\" lang:id since:2026-06-01 until:2026-10-21","search_timeline":{"id":"VGltZWxpbmU6DAB+CwABAAAAQSJkaXNrb24gdGFuZ2dhbCBrZW1iYXIiIGxhbmc6aWQgc2luY2U6MjAyNi0wNi0wMSB1bnRpbDoyMDI2LTEwLTIxCAACAAAAAQAA","timeline":{"id":"LatestTabSrpProduct-Timeline","instructions":[{"__typename":"TimelineReplaceEntry","entry":{"content":{"__typename":"TimelineTimelineCursor","cursor_type":"Top","value":"DAADDAABCgABHUgbQo_bsfoKAAIdSBtCj9ux-gAIAAIAAAABCAADAAAAAAgABAAAAAEKAAUdUJE8YQAnEAoABh1QkTxg_7HgCwAHAAAAKEVtUEM2d0FBQWZRL2dHSk4wdkdwL0FBQUFBRWRTQnRDajl1eCtnPT0AAA"},"entry_id":"cursor-top-9223372036854775807","sort_index":"9223372036854775807"},"entry_id_to_replace":"cursor-top-9223372036854775807"},{"__typename":"TimelineReplaceEntry","entry":{"content":{"__typename":"TimelineTimelineCursor","cursor_type":"Bottom","value":"DAADDAABCgABH... [line-too-long]

Status scraping: SUCCEEDED
ID dataset: mfvjnqzeYzw0kAEgI
Status scraping: SUCCEEDED
ID dataset: mfvjnqzeYzw0kAEgI

In [4]:
from apify_client import ApifyClient
import os
from dotenv import load_dotenv

load_dotenv()
client = ApifyClient(os.getenv("APIFY_API_TOKEN"))

run = client.actor("ID_ACTOR_KAMU").call(
    run_input={
        # Masukkan konfigurasi scraping yang kamu gunakan
    }
)

ApifyApiError: Request not authenticated. Add your Apify API token, or a PAYMENT-SIGNATURE header for x402 payment. See https://docs.apify.com/api/v2#/introduction/authentication

In [9]:
import pandas as pd
from pathlib import Path

# Ambil ulang seluruh data dari dataset Apify terbaru
items = list(
    client.dataset(run.default_dataset_id).iterate_items()
)

df = pd.DataFrame(items)

# Hapus duplikat berdasarkan ID postingan
if "id" in df.columns:
    df = df.drop_duplicates(subset="id")

# Simpan di folder kerja notebook
output_file = Path.cwd() / "data_tanggal_kembar.csv"
df.to_csv(output_file, index=False, encoding="utf-8-sig")

# Verifikasi hasil penyimpanan
df_cek = pd.read_csv(output_file)

print("Jumlah data dari Apify:", len(items))
print("Jumlah data unik:", len(df))
print("Jumlah baris di CSV:", len(df_cek))
print("Lokasi CSV:", output_file.resolve())

display(df_cek[["id", "createdAt", "lang", "text"]].head())

Jumlah data dari Apify: 237
Jumlah data unik: 234
Jumlah baris di CSV: 234
Lokasi CSV: C:\Scraping data tgl kembar\data_tanggal_kembar.csv

,id,createdAt,lang,text
0,2110049779162153142,Tue Oct 13 16:47:24 +0000 2026,in,@afrkml ak kemarin beli 3 hp di shopee aman am...
1,2110037673167737100,Tue Oct 13 15:59:18 +0000 2026,in,close yaa! timaacii yang sudah ikutan dan mera...
2,2110037344552186209,Tue Oct 13 15:58:00 +0000 2026,in,btw kalo abis tanggal kembar emang gini yaa? s...
3,2110010539950899311,Tue Oct 13 14:11:29 +0000 2026,in,Ya onlen kan banyak diskonannyaa terus byk bon...
4,2110004575105388837,Tue Oct 13 13:47:47 +0000 2026,in,"@delvkd Iya Iannn, pas tanggal kembar wkwkwk J..."

In [10]:
for i, kata in enumerate(search_terms):
    jumlah = df["searchTermIndex"].eq(i).sum()
    print(f"{kata} -> {jumlah} postingan")

"tanggal kembar" lang:id since:2026-06-01 until:2026-10-21 -> 25 postingan
"promo tanggal kembar" lang:id since:2026-06-01 until:2026-10-21 -> 0 postingan
"diskon tanggal kembar" lang:id since:2026-06-01 until:2026-10-21 -> 0 postingan
"promo 6.6" lang:id since:2026-06-01 until:2026-10-21 -> 0 postingan
"promo 7.7" lang:id since:2026-06-01 until:2026-10-21 -> 0 postingan
"promo 8.8" lang:id since:2026-06-01 until:2026-10-21 -> 0 postingan
"promo 9.9" lang:id since:2026-06-01 until:2026-10-21 -> 0 postingan
"promo 10.10" lang:id since:2026-10-01 until:2026-10-21 -> 23 postingan
"flash sale" lang:id since:2026-06-01 until:2026-10-21 -> 76 postingan
"gratis ongkir" lang:id since:2026-06-01 until:2026-10-21 -> 100 postingan
"voucher belanja" lang:id since:2026-06-01 until:2026-10-21 -> 10 postingan